#ifndef Dst2D0pi_Variables_Analysis_h
#define Dst2D0pi_Variables_Analysis_h

#include <iostream>
#include "TROOT.h"
#include "TTree.h"

#include "Variables.h"

namespace Dst2D0pi {

  class Variables_Analysis : public Variables {

    public:

      Variables_Analysis();
      ~Variables_Analysis();

      void setInputBranches(TTree *tree);
      void setOutputBranches(TTree *tree);

      // My Var
      Double_t             D0_LTIME_ps                             ;

      Double_t             Dst_BPVVDZ                              ;
      Double_t             Dst_DIRA_OWNPV                          ;
      Double_t             Dst_ENDVERTEX_CHI2                      ;
      Double_t             Dst_FD_CHI2                             ;
      Double_t             Dst_LTIME                               ;
      Double_t             Dst_MINIP                               ;
      Double_t             Dst_MINIPCHI2                           ;
      Double_t             Dst_P_Parallel                          ;
      Double_t             Dst_P_Perp                              ;
      Double_t             Dst_X_travelled                         ;
      Double_t             Dst_Y_travelled                         ;
      Double_t             Dst_Z_travelled                         ;
      Double_t             Dst_ENDVERTEX_X                         ;
      Double_t             Dst_ENDVERTEX_Y                         ;
      Double_t             Dst_ENDVERTEX_Z                         ;
      Double_t             Dst_ENDVERTEX_XERR                      ;
      Double_t             Dst_ENDVERTEX_YERR                      ;
      Double_t             Dst_ENDVERTEX_ZERR                      ;
      Int_t                Dst_ENDVERTEX_NDOF                      ;
      Float_t              Dst_ENDVERTEX_COV_[3][3]                ;
      Double_t             Dst_OWNPV_X                             ;
      Double_t             Dst_OWNPV_Y                             ;
      Double_t             Dst_OWNPV_Z                             ;
      Double_t             Dst_OWNPV_XERR                          ;
      Double_t             Dst_OWNPV_YERR                          ;
      Double_t             Dst_OWNPV_ZERR                          ;
      Double_t             Dst_OWNPV_CHI2                          ;
      Int_t                Dst_OWNPV_NDOF                          ;
      Float_t              Dst_OWNPV_COV_[3][3]                    ;
      Double_t             Dst_IP_OWNPV                            ;
      Double_t             Dst_IPCHI2_OWNPV                        ;
      Double_t             Dst_FD_OWNPV                            ;
      Double_t             Dst_FDCHI2_OWNPV                        ;
      Double_t             Dst_P                                   ;
      Double_t             Dst_PT                                  ;
      Double_t             Dst_PE                                  ;
      Double_t             Dst_PX                                  ;
      Double_t             Dst_PY                                  ;
      Double_t             Dst_PZ                                  ;
      Double_t             Dst_MM                                  ;
      Double_t             Dst_MMERR                               ;
      Double_t             Dst_M                                   ;
      Int_t                Dst_ID                                  ;
      Double_t             Dst_TAU                                 ;
      Double_t             Dst_TAUERR                              ;
      Double_t             Dst_TAUCHI2                             ;
      Bool_t               Dst_L0Global_Dec                        ;
      Bool_t               Dst_L0Global_TIS                        ;
      Bool_t               Dst_L0Global_TOS                        ;
      Bool_t               Dst_Hlt1Global_Dec                      ;
      Bool_t               Dst_Hlt1Global_TIS                      ;
      Bool_t               Dst_Hlt1Global_TOS                      ;
      Bool_t               Dst_Hlt1Phys_Dec                        ;
      Bool_t               Dst_Hlt1Phys_TIS                        ;
      Bool_t               Dst_Hlt1Phys_TOS                        ;
      Bool_t               Dst_Hlt2Global_Dec                      ;
      Bool_t               Dst_Hlt2Global_TIS                      ;
      Bool_t               Dst_Hlt2Global_TOS                      ;
      Bool_t               Dst_Hlt2Phys_Dec                        ;
      Bool_t               Dst_Hlt2Phys_TIS                        ;
      Bool_t               Dst_Hlt2Phys_TOS                        ;
      Bool_t               Dst_L0HadronDecision_Dec                ;
      Bool_t               Dst_L0HadronDecision_TIS                ;
      Bool_t               Dst_L0HadronDecision_TOS                ;
      Bool_t               Dst_L0ElectronDecision_Dec              ;
      Bool_t               Dst_L0ElectronDecision_TIS              ;
      Bool_t               Dst_L0ElectronDecision_TOS              ;
      Bool_t               Dst_L0PhotonDecision_Dec                ;
      Bool_t               Dst_L0PhotonDecision_TIS                ;
      Bool_t               Dst_L0PhotonDecision_TOS                ;
      Bool_t               Dst_L0MuonDecision_Dec                  ;
      Bool_t               Dst_L0MuonDecision_TIS                  ;
      Bool_t               Dst_L0MuonDecision_TOS                  ;
      Bool_t               Dst_L0DiMuonDecision_Dec                ;
      Bool_t               Dst_L0DiMuonDecision_TIS                ;
      Bool_t               Dst_L0DiMuonDecision_TOS                ;
      Bool_t               Dst_Hlt1TrackMVADecision_Dec            ;
      Bool_t               Dst_Hlt1TrackMVADecision_TIS            ;
      Bool_t               Dst_Hlt1TrackMVADecision_TOS            ;
      Bool_t               Dst_Hlt1TwoTrackMVADecision_Dec         ;
      Bool_t               Dst_Hlt1TwoTrackMVADecision_TIS         ;
      Bool_t               Dst_Hlt1TwoTrackMVADecision_TOS         ;
      Bool_t               Dst_Hlt1TrackMuonDecision_Dec           ;
      Bool_t               Dst_Hlt1TrackMuonDecision_TIS           ;
      Bool_t               Dst_Hlt1TrackMuonDecision_TOS           ;
      Bool_t               Dst_Hlt1CalibTrackingKPiDetachedDecision_Dec;
      Bool_t               Dst_Hlt1CalibTrackingKPiDetachedDecision_TIS;
      Bool_t               Dst_Hlt1CalibTrackingKPiDetachedDecision_TOS;
      Bool_t               Dst_Hlt1CalibTrackingKPiDecision_Dec    ;
      Bool_t               Dst_Hlt1CalibTrackingKPiDecision_TIS    ;
      Bool_t               Dst_Hlt1CalibTrackingKPiDecision_TOS    ;
      Bool_t               Dst_Hlt1CalibTrackingKKDecision_Dec     ;
      Bool_t               Dst_Hlt1CalibTrackingKKDecision_TIS     ;
      Bool_t               Dst_Hlt1CalibTrackingKKDecision_TOS     ;
      Bool_t               Dst_Hlt1CalibTrackingPiPiDecision_Dec   ;
      Bool_t               Dst_Hlt1CalibTrackingPiPiDecision_TIS   ;
      Bool_t               Dst_Hlt1CalibTrackingPiPiDecision_TOS   ;
      Bool_t               Dst_Hlt1B2GammaGammaDecision_Dec        ;
      Bool_t               Dst_Hlt1B2GammaGammaDecision_TIS        ;
      Bool_t               Dst_Hlt1B2GammaGammaDecision_TOS        ;
      Bool_t               Dst_Hlt1B2HH_LTUNB_KKDecision_Dec       ;
      Bool_t               Dst_Hlt1B2HH_LTUNB_KKDecision_TIS       ;
      Bool_t               Dst_Hlt1B2HH_LTUNB_KKDecision_TOS       ;
      Bool_t               Dst_Hlt1B2HH_LTUNB_KPiDecision_Dec      ;
      Bool_t               Dst_Hlt1B2HH_LTUNB_KPiDecision_TIS      ;
      Bool_t               Dst_Hlt1B2HH_LTUNB_KPiDecision_TOS      ;
      Bool_t               Dst_Hlt1B2HH_LTUNB_PiPiDecision_Dec     ;
      Bool_t               Dst_Hlt1B2HH_LTUNB_PiPiDecision_TIS     ;
      Bool_t               Dst_Hlt1B2HH_LTUNB_PiPiDecision_TOS     ;
      Bool_t               Dst_Hlt1B2PhiGamma_LTUNBDecision_Dec    ;
      Bool_t               Dst_Hlt1B2PhiGamma_LTUNBDecision_TIS    ;
      Bool_t               Dst_Hlt1B2PhiGamma_LTUNBDecision_TOS    ;
      Bool_t               Dst_Hlt1B2PhiPhi_LTUNBDecision_Dec      ;
      Bool_t               Dst_Hlt1B2PhiPhi_LTUNBDecision_TIS      ;
      Bool_t               Dst_Hlt1B2PhiPhi_LTUNBDecision_TOS      ;
      Bool_t               Dst_Hlt2CharmHadDstp2D0Pip_D02KmPip_LTUNBTurboDecision_Dec;
      Bool_t               Dst_Hlt2CharmHadDstp2D0Pip_D02KmPip_LTUNBTurboDecision_TIS;
      Bool_t               Dst_Hlt2CharmHadDstp2D0Pip_D02KmPip_LTUNBTurboDecision_TOS;
      Bool_t               Dst_Hlt2CharmHadDstp2D0Pip_D02KpPim_LTUNBTurboDecision_Dec;
      Bool_t               Dst_Hlt2CharmHadDstp2D0Pip_D02KpPim_LTUNBTurboDecision_TIS;
      Bool_t               Dst_Hlt2CharmHadDstp2D0Pip_D02KpPim_LTUNBTurboDecision_TOS;
      Bool_t               Dst_Hlt2CharmHadDstp2D0Pip_D02KmKp_LTUNBTurboDecision_Dec;
      Bool_t               Dst_Hlt2CharmHadDstp2D0Pip_D02KmKp_LTUNBTurboDecision_TIS;
      Bool_t               Dst_Hlt2CharmHadDstp2D0Pip_D02KmKp_LTUNBTurboDecision_TOS;
      Bool_t               Dst_Hlt2CharmHadDstp2D0Pip_D02PimPip_LTUNBTurboDecision_Dec;
      Bool_t               Dst_Hlt2CharmHadDstp2D0Pip_D02PimPip_LTUNBTurboDecision_TIS;
      Bool_t               Dst_Hlt2CharmHadDstp2D0Pip_D02PimPip_LTUNBTurboDecision_TOS;
      Double_t             D0_BPVVDZ                               ;
      Double_t             D0_DIRA_OWNPV                           ;
      Double_t             D0_ENDVERTEX_CHI2                       ;
      Double_t             D0_FD_CHI2                              ;
      Double_t             D0_LTIME                                ;
      Double_t             D0_MINIP                                ;
      Double_t             D0_MINIPCHI2                            ;
      Double_t             D0_P_Parallel                           ;
      Double_t             D0_P_Perp                               ;
      Double_t             D0_X_travelled                          ;
      Double_t             D0_Y_travelled                          ;
      Double_t             D0_Z_travelled                          ;
      Double_t             D0_ENDVERTEX_X                          ;
      Double_t             D0_ENDVERTEX_Y                          ;
      Double_t             D0_ENDVERTEX_Z                          ;
      Double_t             D0_ENDVERTEX_XERR                       ;
      Double_t             D0_ENDVERTEX_YERR                       ;
      Double_t             D0_ENDVERTEX_ZERR                       ;
      Int_t                D0_ENDVERTEX_NDOF                       ;
      Float_t              D0_ENDVERTEX_COV_[3][3]                 ;
      Double_t             D0_OWNPV_X                              ;
      Double_t             D0_OWNPV_Y                              ;
      Double_t             D0_OWNPV_Z                              ;
      Double_t             D0_OWNPV_XERR                           ;
      Double_t             D0_OWNPV_YERR                           ;
      Double_t             D0_OWNPV_ZERR                           ;
      Double_t             D0_OWNPV_CHI2                           ;
      Int_t                D0_OWNPV_NDOF                           ;
      Float_t              D0_OWNPV_COV_[3][3]                     ;
      Double_t             D0_IP_OWNPV                             ;
      Double_t             D0_IPCHI2_OWNPV                         ;
      Double_t             D0_FD_OWNPV                             ;
      Double_t             D0_FDCHI2_OWNPV                         ;
      Double_t             D0_ORIVX_X                              ;
      Double_t             D0_ORIVX_Y                              ;
      Double_t             D0_ORIVX_Z                              ;
      Double_t             D0_ORIVX_XERR                           ;
      Double_t             D0_ORIVX_YERR                           ;
      Double_t             D0_ORIVX_ZERR                           ;
      Double_t             D0_ORIVX_CHI2                           ;
      Int_t                D0_ORIVX_NDOF                           ;
      Float_t              D0_ORIVX_COV_[3][3]                     ;
      Double_t             D0_FD_ORIVX                             ;
      Double_t             D0_FDCHI2_ORIVX                         ;
      Double_t             D0_DIRA_ORIVX                           ;
      Double_t             D0_P                                    ;
      Double_t             D0_PT                                   ;
      Double_t             D0_PE                                   ;
      Double_t             D0_PX                                   ;
      Double_t             D0_PY                                   ;
      Double_t             D0_PZ                                   ;
      Double_t             D0_MM                                   ;
      Double_t             D0_MMERR                                ;
      Double_t             D0_M                                    ;
      Int_t                D0_ID                                   ;
      Double_t             D0_TAU                                  ;
      Double_t             D0_TAUERR                               ;
      Double_t             D0_TAUCHI2                              ;
      Bool_t               D0_L0Global_Dec                         ;
      Bool_t               D0_L0Global_TIS                         ;
      Bool_t               D0_L0Global_TOS                         ;
      Bool_t               D0_Hlt1Global_Dec                       ;
      Bool_t               D0_Hlt1Global_TIS                       ;
      Bool_t               D0_Hlt1Global_TOS                       ;
      Bool_t               D0_Hlt1Phys_Dec                         ;
      Bool_t               D0_Hlt1Phys_TIS                         ;
      Bool_t               D0_Hlt1Phys_TOS                         ;
      Bool_t               D0_Hlt2Global_Dec                       ;
      Bool_t               D0_Hlt2Global_TIS                       ;
      Bool_t               D0_Hlt2Global_TOS                       ;
      Bool_t               D0_Hlt2Phys_Dec                         ;
      Bool_t               D0_Hlt2Phys_TIS                         ;
      Bool_t               D0_Hlt2Phys_TOS                         ;
      Bool_t               D0_L0HadronDecision_Dec                 ;
      Bool_t               D0_L0HadronDecision_TIS                 ;
      Bool_t               D0_L0HadronDecision_TOS                 ;
      Bool_t               D0_L0ElectronDecision_Dec               ;
      Bool_t               D0_L0ElectronDecision_TIS               ;
      Bool_t               D0_L0ElectronDecision_TOS               ;
      Bool_t               D0_L0PhotonDecision_Dec                 ;
      Bool_t               D0_L0PhotonDecision_TIS                 ;
      Bool_t               D0_L0PhotonDecision_TOS                 ;
      Bool_t               D0_L0MuonDecision_Dec                   ;
      Bool_t               D0_L0MuonDecision_TIS                   ;
      Bool_t               D0_L0MuonDecision_TOS                   ;
      Bool_t               D0_L0DiMuonDecision_Dec                 ;
      Bool_t               D0_L0DiMuonDecision_TIS                 ;
      Bool_t               D0_L0DiMuonDecision_TOS                 ;
      Bool_t               D0_Hlt1TrackMVADecision_Dec             ;
      Bool_t               D0_Hlt1TrackMVADecision_TIS             ;
      Bool_t               D0_Hlt1TrackMVADecision_TOS             ;
      Bool_t               D0_Hlt1TwoTrackMVADecision_Dec          ;
      Bool_t               D0_Hlt1TwoTrackMVADecision_TIS          ;
      Bool_t               D0_Hlt1TwoTrackMVADecision_TOS          ;
      Bool_t               D0_Hlt1TrackMuonDecision_Dec            ;
      Bool_t               D0_Hlt1TrackMuonDecision_TIS            ;
      Bool_t               D0_Hlt1TrackMuonDecision_TOS            ;
      Bool_t               D0_Hlt1CalibTrackingKPiDetachedDecision_Dec;
      Bool_t               D0_Hlt1CalibTrackingKPiDetachedDecision_TIS;
      Bool_t               D0_Hlt1CalibTrackingKPiDetachedDecision_TOS;
      Bool_t               D0_Hlt1CalibTrackingKPiDecision_Dec     ;
      Bool_t               D0_Hlt1CalibTrackingKPiDecision_TIS     ;
      Bool_t               D0_Hlt1CalibTrackingKPiDecision_TOS     ;
      Bool_t               D0_Hlt1CalibTrackingKKDecision_Dec      ;
      Bool_t               D0_Hlt1CalibTrackingKKDecision_TIS      ;
      Bool_t               D0_Hlt1CalibTrackingKKDecision_TOS      ;
      Bool_t               D0_Hlt1CalibTrackingPiPiDecision_Dec    ;
      Bool_t               D0_Hlt1CalibTrackingPiPiDecision_TIS    ;
      Bool_t               D0_Hlt1CalibTrackingPiPiDecision_TOS    ;
      Bool_t               D0_Hlt1B2GammaGammaDecision_Dec         ;
      Bool_t               D0_Hlt1B2GammaGammaDecision_TIS         ;
      Bool_t               D0_Hlt1B2GammaGammaDecision_TOS         ;
      Bool_t               D0_Hlt1B2HH_LTUNB_KKDecision_Dec        ;
      Bool_t               D0_Hlt1B2HH_LTUNB_KKDecision_TIS        ;
      Bool_t               D0_Hlt1B2HH_LTUNB_KKDecision_TOS        ;
      Bool_t               D0_Hlt1B2HH_LTUNB_KPiDecision_Dec       ;
      Bool_t               D0_Hlt1B2HH_LTUNB_KPiDecision_TIS       ;
      Bool_t               D0_Hlt1B2HH_LTUNB_KPiDecision_TOS       ;
      Bool_t               D0_Hlt1B2HH_LTUNB_PiPiDecision_Dec      ;
      Bool_t               D0_Hlt1B2HH_LTUNB_PiPiDecision_TIS      ;
      Bool_t               D0_Hlt1B2HH_LTUNB_PiPiDecision_TOS      ;
      Bool_t               D0_Hlt1B2PhiGamma_LTUNBDecision_Dec     ;
      Bool_t               D0_Hlt1B2PhiGamma_LTUNBDecision_TIS     ;
      Bool_t               D0_Hlt1B2PhiGamma_LTUNBDecision_TOS     ;
      Bool_t               D0_Hlt1B2PhiPhi_LTUNBDecision_Dec       ;
      Bool_t               D0_Hlt1B2PhiPhi_LTUNBDecision_TIS       ;
      Bool_t               D0_Hlt1B2PhiPhi_LTUNBDecision_TOS       ;
      Bool_t               D0_Hlt2CharmHadDstp2D0Pip_D02KmPip_LTUNBTurboDecision_Dec;
      Bool_t               D0_Hlt2CharmHadDstp2D0Pip_D02KmPip_LTUNBTurboDecision_TIS;
      Bool_t               D0_Hlt2CharmHadDstp2D0Pip_D02KmPip_LTUNBTurboDecision_TOS;
      Bool_t               D0_Hlt2CharmHadDstp2D0Pip_D02KpPim_LTUNBTurboDecision_Dec;
      Bool_t               D0_Hlt2CharmHadDstp2D0Pip_D02KpPim_LTUNBTurboDecision_TIS;
      Bool_t               D0_Hlt2CharmHadDstp2D0Pip_D02KpPim_LTUNBTurboDecision_TOS;
      Bool_t               D0_Hlt2CharmHadDstp2D0Pip_D02KmKp_LTUNBTurboDecision_Dec;
      Bool_t               D0_Hlt2CharmHadDstp2D0Pip_D02KmKp_LTUNBTurboDecision_TIS;
      Bool_t               D0_Hlt2CharmHadDstp2D0Pip_D02KmKp_LTUNBTurboDecision_TOS;
      Bool_t               D0_Hlt2CharmHadDstp2D0Pip_D02PimPip_LTUNBTurboDecision_Dec;
      Bool_t               D0_Hlt2CharmHadDstp2D0Pip_D02PimPip_LTUNBTurboDecision_TIS;
      Bool_t               D0_Hlt2CharmHadDstp2D0Pip_D02PimPip_LTUNBTurboDecision_TOS;
      Double_t             Kminus_BPVVDZ                           ;
      Double_t             Kminus_DIRA_OWNPV                       ;
      Double_t             Kminus_ENDVERTEX_CHI2                   ;
      Double_t             Kminus_FD_CHI2                          ;
      Double_t             Kminus_LTIME                            ;
      Double_t             Kminus_MINIP                            ;
      Double_t             Kminus_MINIPCHI2                        ;
      Double_t             Kminus_P_Parallel                       ;
      Double_t             Kminus_P_Perp                           ;
      Double_t             Kminus_X_travelled                      ;
      Double_t             Kminus_Y_travelled                      ;
      Double_t             Kminus_Z_travelled                      ;
      Double_t             Kminus_MC12TuneV2_ProbNNe               ;
      Double_t             Kminus_MC12TuneV2_ProbNNmu              ;
      Double_t             Kminus_MC12TuneV2_ProbNNpi              ;
      Double_t             Kminus_MC12TuneV2_ProbNNk               ;
      Double_t             Kminus_MC12TuneV2_ProbNNp               ;
      Double_t             Kminus_MC12TuneV2_ProbNNghost           ;
      Double_t             Kminus_MC12TuneV3_ProbNNe               ;
      Double_t             Kminus_MC12TuneV3_ProbNNmu              ;
      Double_t             Kminus_MC12TuneV3_ProbNNpi              ;
      Double_t             Kminus_MC12TuneV3_ProbNNk               ;
      Double_t             Kminus_MC12TuneV3_ProbNNp               ;
      Double_t             Kminus_MC12TuneV3_ProbNNghost           ;
      Double_t             Kminus_OWNPV_X                          ;
      Double_t             Kminus_OWNPV_Y                          ;
      Double_t             Kminus_OWNPV_Z                          ;
      Double_t             Kminus_OWNPV_XERR                       ;
      Double_t             Kminus_OWNPV_YERR                       ;
      Double_t             Kminus_OWNPV_ZERR                       ;
      Double_t             Kminus_OWNPV_CHI2                       ;
      Int_t                Kminus_OWNPV_NDOF                       ;
      Float_t              Kminus_OWNPV_COV_[3][3]                 ;
      Double_t             Kminus_IP_OWNPV                         ;
      Double_t             Kminus_IPCHI2_OWNPV                     ;
      Double_t             Kminus_ORIVX_X                          ;
      Double_t             Kminus_ORIVX_Y                          ;
      Double_t             Kminus_ORIVX_Z                          ;
      Double_t             Kminus_ORIVX_XERR                       ;
      Double_t             Kminus_ORIVX_YERR                       ;
      Double_t             Kminus_ORIVX_ZERR                       ;
      Double_t             Kminus_ORIVX_CHI2                       ;
      Int_t                Kminus_ORIVX_NDOF                       ;
      Float_t              Kminus_ORIVX_COV_[3][3]                 ;
      Double_t             Kminus_P                                ;
      Double_t             Kminus_PT                               ;
      Double_t             Kminus_PE                               ;
      Double_t             Kminus_PX                               ;
      Double_t             Kminus_PY                               ;
      Double_t             Kminus_PZ                               ;
      Double_t             Kminus_M                                ;
      Int_t                Kminus_ID                               ;
      Double_t             Kminus_PIDe                             ;
      Double_t             Kminus_PIDmu                            ;
      Double_t             Kminus_PIDK                             ;
      Double_t             Kminus_PIDp                             ;
      Double_t             Kminus_ProbNNe                          ;
      Double_t             Kminus_ProbNNk                          ;
      Double_t             Kminus_ProbNNp                          ;
      Double_t             Kminus_ProbNNpi                         ;
      Double_t             Kminus_ProbNNmu                         ;
      Double_t             Kminus_ProbNNghost                      ;
      Bool_t               Kminus_hasMuon                          ;
      Bool_t               Kminus_isMuon                           ;
      Bool_t               Kminus_hasRich                          ;
      Bool_t               Kminus_hasCalo                          ;
      Double_t             piplus_BPVVDZ                           ;
      Double_t             piplus_DIRA_OWNPV                       ;
      Double_t             piplus_ENDVERTEX_CHI2                   ;
      Double_t             piplus_FD_CHI2                          ;
      Double_t             piplus_LTIME                            ;
      Double_t             piplus_MINIP                            ;
      Double_t             piplus_MINIPCHI2                        ;
      Double_t             piplus_P_Parallel                       ;
      Double_t             piplus_P_Perp                           ;
      Double_t             piplus_X_travelled                      ;
      Double_t             piplus_Y_travelled                      ;
      Double_t             piplus_Z_travelled                      ;
      Double_t             piplus_MC12TuneV2_ProbNNe               ;
      Double_t             piplus_MC12TuneV2_ProbNNmu              ;
      Double_t             piplus_MC12TuneV2_ProbNNpi              ;
      Double_t             piplus_MC12TuneV2_ProbNNk               ;
      Double_t             piplus_MC12TuneV2_ProbNNp               ;
      Double_t             piplus_MC12TuneV2_ProbNNghost           ;
      Double_t             piplus_MC12TuneV3_ProbNNe               ;
      Double_t             piplus_MC12TuneV3_ProbNNmu              ;
      Double_t             piplus_MC12TuneV3_ProbNNpi              ;
      Double_t             piplus_MC12TuneV3_ProbNNk               ;
      Double_t             piplus_MC12TuneV3_ProbNNp               ;
      Double_t             piplus_MC12TuneV3_ProbNNghost           ;
      Double_t             piplus_OWNPV_X                          ;
      Double_t             piplus_OWNPV_Y                          ;
      Double_t             piplus_OWNPV_Z                          ;
      Double_t             piplus_OWNPV_XERR                       ;
      Double_t             piplus_OWNPV_YERR                       ;
      Double_t             piplus_OWNPV_ZERR                       ;
      Double_t             piplus_OWNPV_CHI2                       ;
      Int_t                piplus_OWNPV_NDOF                       ;
      Float_t              piplus_OWNPV_COV_[3][3]                 ;
      Double_t             piplus_IP_OWNPV                         ;
      Double_t             piplus_IPCHI2_OWNPV                     ;
      Double_t             piplus_ORIVX_X                          ;
      Double_t             piplus_ORIVX_Y                          ;
      Double_t             piplus_ORIVX_Z                          ;
      Double_t             piplus_ORIVX_XERR                       ;
      Double_t             piplus_ORIVX_YERR                       ;
      Double_t             piplus_ORIVX_ZERR                       ;
      Double_t             piplus_ORIVX_CHI2                       ;
      Int_t                piplus_ORIVX_NDOF                       ;
      Float_t              piplus_ORIVX_COV_[3][3]                 ;
      Double_t             piplus_P                                ;
      Double_t             piplus_PT                               ;
      Double_t             piplus_PE                               ;
      Double_t             piplus_PX                               ;
      Double_t             piplus_PY                               ;
      Double_t             piplus_PZ                               ;
      Double_t             piplus_M                                ;
      Int_t                piplus_ID                               ;
      Double_t             piplus_PIDe                             ;
      Double_t             piplus_PIDmu                            ;
      Double_t             piplus_PIDK                             ;
      Double_t             piplus_PIDp                             ;
      Double_t             piplus_ProbNNe                          ;
      Double_t             piplus_ProbNNk                          ;
      Double_t             piplus_ProbNNp                          ;
      Double_t             piplus_ProbNNpi                         ;
      Double_t             piplus_ProbNNmu                         ;
      Double_t             piplus_ProbNNghost                      ;
      Bool_t               piplus_hasMuon                          ;
      Bool_t               piplus_isMuon                           ;
      Bool_t               piplus_hasRich                          ;
      Bool_t               piplus_hasCalo                          ;
      Double_t             PiBach_BPVVDZ                           ;
      Double_t             PiBach_DIRA_OWNPV                       ;
      Double_t             PiBach_ENDVERTEX_CHI2                   ;
      Double_t             PiBach_FD_CHI2                          ;
      Double_t             PiBach_LTIME                            ;
      Double_t             PiBach_MINIP                            ;
      Double_t             PiBach_MINIPCHI2                        ;
      Double_t             PiBach_P_Parallel                       ;
      Double_t             PiBach_P_Perp                           ;
      Double_t             PiBach_X_travelled                      ;
      Double_t             PiBach_Y_travelled                      ;
      Double_t             PiBach_Z_travelled                      ;
      Double_t             PiBach_MC12TuneV2_ProbNNe               ;
      Double_t             PiBach_MC12TuneV2_ProbNNmu              ;
      Double_t             PiBach_MC12TuneV2_ProbNNpi              ;
      Double_t             PiBach_MC12TuneV2_ProbNNk               ;
      Double_t             PiBach_MC12TuneV2_ProbNNp               ;
      Double_t             PiBach_MC12TuneV2_ProbNNghost           ;
      Double_t             PiBach_MC12TuneV3_ProbNNe               ;
      Double_t             PiBach_MC12TuneV3_ProbNNmu              ;
      Double_t             PiBach_MC12TuneV3_ProbNNpi              ;
      Double_t             PiBach_MC12TuneV3_ProbNNk               ;
      Double_t             PiBach_MC12TuneV3_ProbNNp               ;
      Double_t             PiBach_MC12TuneV3_ProbNNghost           ;
      Double_t             PiBach_OWNPV_X                          ;
      Double_t             PiBach_OWNPV_Y                          ;
      Double_t             PiBach_OWNPV_Z                          ;
      Double_t             PiBach_OWNPV_XERR                       ;
      Double_t             PiBach_OWNPV_YERR                       ;
      Double_t             PiBach_OWNPV_ZERR                       ;
      Double_t             PiBach_OWNPV_CHI2                       ;
      Int_t                PiBach_OWNPV_NDOF                       ;
      Float_t              PiBach_OWNPV_COV_[3][3]                 ;
      Double_t             PiBach_IP_OWNPV                         ;
      Double_t             PiBach_IPCHI2_OWNPV                     ;
      Double_t             PiBach_ORIVX_X                          ;
      Double_t             PiBach_ORIVX_Y                          ;
      Double_t             PiBach_ORIVX_Z                          ;
      Double_t             PiBach_ORIVX_XERR                       ;
      Double_t             PiBach_ORIVX_YERR                       ;
      Double_t             PiBach_ORIVX_ZERR                       ;
      Double_t             PiBach_ORIVX_CHI2                       ;
      Int_t                PiBach_ORIVX_NDOF                       ;
      Float_t              PiBach_ORIVX_COV_[3][3]                 ;
      Double_t             PiBach_P                                ;
      Double_t             PiBach_PT                               ;
      Double_t             PiBach_PE                               ;
      Double_t             PiBach_PX                               ;
      Double_t             PiBach_PY                               ;
      Double_t             PiBach_PZ                               ;
      Double_t             PiBach_M                                ;
      Int_t                PiBach_ID                               ;
      Double_t             PiBach_PIDe                             ;
      Double_t             PiBach_PIDmu                            ;
      Double_t             PiBach_PIDK                             ;
      Double_t             PiBach_PIDp                             ;
      Double_t             PiBach_ProbNNe                          ;
      Double_t             PiBach_ProbNNk                          ;
      Double_t             PiBach_ProbNNp                          ;
      Double_t             PiBach_ProbNNpi                         ;
      Double_t             PiBach_ProbNNmu                         ;
      Double_t             PiBach_ProbNNghost                      ;
      Bool_t               PiBach_hasMuon                          ;
      Bool_t               PiBach_isMuon                           ;
      Bool_t               PiBach_hasRich                          ;
      Bool_t               PiBach_hasCalo                          ;
      UInt_t               nCandidate                              ;
      ULong64_t            totCandidates                           ;
      ULong64_t            EventInSequence                         ;
      UInt_t               runNumber                               ;
      ULong64_t            eventNumber                             ;
      UInt_t               BCID                                    ;
      Int_t                BCType                                  ;
      UInt_t               OdinTCK                                 ;
      UInt_t               L0DUTCK                                 ;
      UInt_t               HLT1TCK                                 ;
      UInt_t               HLT2TCK                                 ;
      ULong64_t            GpsTime                                 ;
      Short_t              Polarity                                ;
      Int_t                nPV                                     ;
      Float_t              PVX[100]                                ;
      Float_t              PVY[100]                                ;
      Float_t              PVZ[100]                                ;
      Float_t              PVXERR[100]                             ;
      Float_t              PVYERR[100]                             ;
      Float_t              PVZERR[100]                             ;
      Float_t              PVCHI2[100]                             ;
      Float_t              PVNDOF[100]                             ;
      Float_t              PVNTRACKS[100]                          ;
      Int_t                nPVs                                    ;
      Int_t                nTracks                                 ;
      Int_t                nLongTracks                             ;
      Int_t                nDownstreamTracks                       ;
      Int_t                nUpstreamTracks                         ;
      Int_t                nVeloTracks                             ;
      Int_t                nTTracks                                ;
      Int_t                nBackTracks                             ;
      Int_t                nRich1Hits                              ;
      Int_t                nRich2Hits                              ;
      Int_t                nVeloClusters                           ;
      Int_t                nITClusters                             ;
      Int_t                nTTClusters                             ;
      Int_t                nOTClusters                             ;
      Int_t                nSPDHits                                ;
      Int_t                nMuonCoordsS0                           ;
      Int_t                nMuonCoordsS1                           ;
      Int_t                nMuonCoordsS2                           ;
      Int_t                nMuonCoordsS3                           ;
      Int_t                nMuonCoordsS4                           ;
      Int_t                nMuonTracks                             ;
  };

}
#endif

