#ifndef Dst2D0pi_Variables_Analysis_h
#define Dst2D0pi_Variables_Analysis_h

#include <iostream>
#include "TROOT.h"
#include "TTree.h"

#include "Variables.h"

namespace Dst2D0pi {

  class Variables_Analysis : public Variables {

    public:

      Variables_Analysis();
      ~Variables_Analysis();

      void setInputBranches(TTree *tree);
      void setOutputBranches(TTree *tree);

      Double_t             Dst_2010_plus_BPVVDZ                    ;
      Double_t             Dst_2010_plus_DIRA_OWNPV                ;
      Double_t             Dst_2010_plus_ENDVERTEX_CHI2            ;
      Double_t             Dst_2010_plus_FD_CHI2                   ;
      Double_t             Dst_2010_plus_LIFETIME                  ;
      Double_t             Dst_2010_plus_MINIP                     ;
      Double_t             Dst_2010_plus_MINIPCHI2                 ;
      Double_t             Dst_2010_plus_P_Parallel                ;
      Double_t             Dst_2010_plus_P_Perp                    ;
      Double_t             Dst_2010_plus_X_travelled               ;
      Double_t             Dst_2010_plus_Y_travelled               ;
      Double_t             Dst_2010_plus_Z_travelled               ;
      Double_t             Dst_2010_plus_P                         ;
      Double_t             Dst_2010_plus_PT                        ;
      Double_t             Dst_2010_plus_PE                        ;
      Double_t             Dst_2010_plus_PX                        ;
      Double_t             Dst_2010_plus_PY                        ;
      Double_t             Dst_2010_plus_PZ                        ;
      Double_t             Dst_2010_plus_MM                        ;
      Double_t             Dst_2010_plus_MMERR                     ;
      Double_t             Dst_2010_plus_M                         ;
      Int_t                Dst_2010_plus_ID                        ;
      Double_t             Dst_2010_plus_TAU                       ;
      Double_t             Dst_2010_plus_TAUERR                    ;
      Double_t             Dst_2010_plus_TAUCHI2                   ;
      Bool_t               Dst_2010_plus_L0Global_Dec              ;
      Bool_t               Dst_2010_plus_L0Global_TIS              ;
      Bool_t               Dst_2010_plus_L0Global_TOS              ;
      Bool_t               Dst_2010_plus_Hlt1Global_Dec            ;
      Bool_t               Dst_2010_plus_Hlt1Global_TIS            ;
      Bool_t               Dst_2010_plus_Hlt1Global_TOS            ;
      Bool_t               Dst_2010_plus_Hlt1Phys_Dec              ;
      Bool_t               Dst_2010_plus_Hlt1Phys_TIS              ;
      Bool_t               Dst_2010_plus_Hlt1Phys_TOS              ;
      Bool_t               Dst_2010_plus_Hlt2Global_Dec            ;
      Bool_t               Dst_2010_plus_Hlt2Global_TIS            ;
      Bool_t               Dst_2010_plus_Hlt2Global_TOS            ;
      Bool_t               Dst_2010_plus_Hlt2Phys_Dec              ;
      Bool_t               Dst_2010_plus_Hlt2Phys_TIS              ;
      Bool_t               Dst_2010_plus_Hlt2Phys_TOS              ;
      Bool_t               Dst_2010_plus_L0HadronDecision_Dec      ;
      Bool_t               Dst_2010_plus_L0HadronDecision_TIS      ;
      Bool_t               Dst_2010_plus_L0HadronDecision_TOS      ;
      Bool_t               Dst_2010_plus_L0MuonDecision_Dec        ;
      Bool_t               Dst_2010_plus_L0MuonDecision_TIS        ;
      Bool_t               Dst_2010_plus_L0MuonDecision_TOS        ;
      Bool_t               Dst_2010_plus_L0DiMuonDecision_Dec      ;
      Bool_t               Dst_2010_plus_L0DiMuonDecision_TIS      ;
      Bool_t               Dst_2010_plus_L0DiMuonDecision_TOS      ;
      Bool_t               Dst_2010_plus_L0ElectronDecision_Dec    ;
      Bool_t               Dst_2010_plus_L0ElectronDecision_TIS    ;
      Bool_t               Dst_2010_plus_L0ElectronDecision_TOS    ;
      Bool_t               Dst_2010_plus_L0PhotonDecision_Dec      ;
      Bool_t               Dst_2010_plus_L0PhotonDecision_TIS      ;
      Bool_t               Dst_2010_plus_L0PhotonDecision_TOS      ;
      Bool_t               Dst_2010_plus_Hlt1TrackMVADecision_Dec  ;
      Bool_t               Dst_2010_plus_Hlt1TrackMVADecision_TIS  ;
      Bool_t               Dst_2010_plus_Hlt1TrackMVADecision_TOS  ;
      Bool_t               Dst_2010_plus_Hlt1TwoTrackMVADecision_Dec;
      Bool_t               Dst_2010_plus_Hlt1TwoTrackMVADecision_TIS;
      Bool_t               Dst_2010_plus_Hlt1TwoTrackMVADecision_TOS;
      Bool_t               Dst_2010_plus_Hlt1CalibTrackingKPiDecision_Dec;
      Bool_t               Dst_2010_plus_Hlt1CalibTrackingKPiDecision_TIS;
      Bool_t               Dst_2010_plus_Hlt1CalibTrackingKPiDecision_TOS;
      Bool_t               Dst_2010_plus_Hlt1CalibTrackingKKDecision_Dec;
      Bool_t               Dst_2010_plus_Hlt1CalibTrackingKKDecision_TIS;
      Bool_t               Dst_2010_plus_Hlt1CalibTrackingKKDecision_TOS;
      Bool_t               Dst_2010_plus_Hlt1CalibTrackingPiPiDecision_Dec;
      Bool_t               Dst_2010_plus_Hlt1CalibTrackingPiPiDecision_TIS;
      Bool_t               Dst_2010_plus_Hlt1CalibTrackingPiPiDecision_TOS;
      Bool_t               Dst_2010_plus_Hlt1CalibTrackingKPiDetachedDecision_Dec;
      Bool_t               Dst_2010_plus_Hlt1CalibTrackingKPiDetachedDecision_TIS;
      Bool_t               Dst_2010_plus_Hlt1CalibTrackingKPiDetachedDecision_TOS;
      Double_t             D0_BPVVDZ                               ;
      Double_t             D0_DIRA_OWNPV                           ;
      Double_t             D0_ENDVERTEX_CHI2                       ;
      Double_t             D0_FD_CHI2                              ;
      Double_t             D0_LIFETIME                             ;
      Double_t             D0_MINIP                                ;
      Double_t             D0_MINIPCHI2                            ;
      Double_t             D0_P_Parallel                           ;
      Double_t             D0_P_Perp                               ;
      Double_t             D0_X_travelled                          ;
      Double_t             D0_Y_travelled                          ;
      Double_t             D0_Z_travelled                          ;
      Double_t             D0_CosTheta                             ;
      Double_t             D0_P                                    ;
      Double_t             D0_PT                                   ;
      Double_t             D0_PE                                   ;
      Double_t             D0_PX                                   ;
      Double_t             D0_PY                                   ;
      Double_t             D0_PZ                                   ;
      Double_t             D0_MM                                   ;
      Double_t             D0_MMERR                                ;
      Double_t             D0_M                                    ;
      Int_t                D0_ID                                   ;
      Double_t             D0_TAU                                  ;
      Double_t             D0_TAUERR                               ;
      Double_t             D0_TAUCHI2                              ;
      Bool_t               D0_L0Global_Dec                         ;
      Bool_t               D0_L0Global_TIS                         ;
      Bool_t               D0_L0Global_TOS                         ;
      Bool_t               D0_Hlt1Global_Dec                       ;
      Bool_t               D0_Hlt1Global_TIS                       ;
      Bool_t               D0_Hlt1Global_TOS                       ;
      Bool_t               D0_Hlt1Phys_Dec                         ;
      Bool_t               D0_Hlt1Phys_TIS                         ;
      Bool_t               D0_Hlt1Phys_TOS                         ;
      Bool_t               D0_Hlt2Global_Dec                       ;
      Bool_t               D0_Hlt2Global_TIS                       ;
      Bool_t               D0_Hlt2Global_TOS                       ;
      Bool_t               D0_Hlt2Phys_Dec                         ;
      Bool_t               D0_Hlt2Phys_TIS                         ;
      Bool_t               D0_Hlt2Phys_TOS                         ;
      Bool_t               D0_L0HadronDecision_Dec                 ;
      Bool_t               D0_L0HadronDecision_TIS                 ;
      Bool_t               D0_L0HadronDecision_TOS                 ;
      Bool_t               D0_L0MuonDecision_Dec                   ;
      Bool_t               D0_L0MuonDecision_TIS                   ;
      Bool_t               D0_L0MuonDecision_TOS                   ;
      Bool_t               D0_L0DiMuonDecision_Dec                 ;
      Bool_t               D0_L0DiMuonDecision_TIS                 ;
      Bool_t               D0_L0DiMuonDecision_TOS                 ;
      Bool_t               D0_L0ElectronDecision_Dec               ;
      Bool_t               D0_L0ElectronDecision_TIS               ;
      Bool_t               D0_L0ElectronDecision_TOS               ;
      Bool_t               D0_L0PhotonDecision_Dec                 ;
      Bool_t               D0_L0PhotonDecision_TIS                 ;
      Bool_t               D0_L0PhotonDecision_TOS                 ;
      Bool_t               D0_Hlt1TrackMVADecision_Dec             ;
      Bool_t               D0_Hlt1TrackMVADecision_TIS             ;
      Bool_t               D0_Hlt1TrackMVADecision_TOS             ;
      Bool_t               D0_Hlt1TwoTrackMVADecision_Dec          ;
      Bool_t               D0_Hlt1TwoTrackMVADecision_TIS          ;
      Bool_t               D0_Hlt1TwoTrackMVADecision_TOS          ;
      Bool_t               D0_Hlt1CalibTrackingKPiDecision_Dec     ;
      Bool_t               D0_Hlt1CalibTrackingKPiDecision_TIS     ;
      Bool_t               D0_Hlt1CalibTrackingKPiDecision_TOS     ;
      Bool_t               D0_Hlt1CalibTrackingKKDecision_Dec      ;
      Bool_t               D0_Hlt1CalibTrackingKKDecision_TIS      ;
      Bool_t               D0_Hlt1CalibTrackingKKDecision_TOS      ;
      Bool_t               D0_Hlt1CalibTrackingPiPiDecision_Dec    ;
      Bool_t               D0_Hlt1CalibTrackingPiPiDecision_TIS    ;
      Bool_t               D0_Hlt1CalibTrackingPiPiDecision_TOS    ;
      Bool_t               D0_Hlt1CalibTrackingKPiDetachedDecision_Dec;
      Bool_t               D0_Hlt1CalibTrackingKPiDetachedDecision_TIS;
      Bool_t               D0_Hlt1CalibTrackingKPiDetachedDecision_TOS;
      Double_t             Kminus_BPVVDZ                           ;
      Double_t             Kminus_DIRA_OWNPV                       ;
      Double_t             Kminus_ENDVERTEX_CHI2                   ;
      Double_t             Kminus_FD_CHI2                          ;
      Double_t             Kminus_LIFETIME                         ;
      Double_t             Kminus_MINIP                            ;
      Double_t             Kminus_MINIPCHI2                        ;
      Double_t             Kminus_P_Parallel                       ;
      Double_t             Kminus_P_Perp                           ;
      Double_t             Kminus_X_travelled                      ;
      Double_t             Kminus_Y_travelled                      ;
      Double_t             Kminus_Z_travelled                      ;
      Double_t             Kminus_CosTheta                         ;
      Double_t             Kminus_P                                ;
      Double_t             Kminus_PT                               ;
      Double_t             Kminus_PE                               ;
      Double_t             Kminus_PX                               ;
      Double_t             Kminus_PY                               ;
      Double_t             Kminus_PZ                               ;
      Double_t             Kminus_M                                ;
      Int_t                Kminus_ID                               ;
      Double_t             Kminus_PIDe                             ;
      Double_t             Kminus_PIDmu                            ;
      Double_t             Kminus_PIDK                             ;
      Double_t             Kminus_PIDp                             ;
      Double_t             Kminus_ProbNNe                          ;
      Double_t             Kminus_ProbNNk                          ;
      Double_t             Kminus_ProbNNp                          ;
      Double_t             Kminus_ProbNNpi                         ;
      Double_t             Kminus_ProbNNmu                         ;
      Double_t             Kminus_ProbNNghost                      ;
      Bool_t               Kminus_hasMuon                          ;
      Bool_t               Kminus_isMuon                           ;
      Bool_t               Kminus_hasRich                          ;
      Bool_t               Kminus_hasCalo                          ;
      Bool_t               Kminus_L0Global_Dec                     ;
      Bool_t               Kminus_L0Global_TIS                     ;
      Bool_t               Kminus_L0Global_TOS                     ;
      Bool_t               Kminus_Hlt1Global_Dec                   ;
      Bool_t               Kminus_Hlt1Global_TIS                   ;
      Bool_t               Kminus_Hlt1Global_TOS                   ;
      Bool_t               Kminus_Hlt1Phys_Dec                     ;
      Bool_t               Kminus_Hlt1Phys_TIS                     ;
      Bool_t               Kminus_Hlt1Phys_TOS                     ;
      Bool_t               Kminus_Hlt2Global_Dec                   ;
      Bool_t               Kminus_Hlt2Global_TIS                   ;
      Bool_t               Kminus_Hlt2Global_TOS                   ;
      Bool_t               Kminus_Hlt2Phys_Dec                     ;
      Bool_t               Kminus_Hlt2Phys_TIS                     ;
      Bool_t               Kminus_Hlt2Phys_TOS                     ;
      Bool_t               Kminus_L0HadronDecision_Dec             ;
      Bool_t               Kminus_L0HadronDecision_TIS             ;
      Bool_t               Kminus_L0HadronDecision_TOS             ;
      Bool_t               Kminus_L0MuonDecision_Dec               ;
      Bool_t               Kminus_L0MuonDecision_TIS               ;
      Bool_t               Kminus_L0MuonDecision_TOS               ;
      Bool_t               Kminus_L0DiMuonDecision_Dec             ;
      Bool_t               Kminus_L0DiMuonDecision_TIS             ;
      Bool_t               Kminus_L0DiMuonDecision_TOS             ;
      Bool_t               Kminus_L0ElectronDecision_Dec           ;
      Bool_t               Kminus_L0ElectronDecision_TIS           ;
      Bool_t               Kminus_L0ElectronDecision_TOS           ;
      Bool_t               Kminus_L0PhotonDecision_Dec             ;
      Bool_t               Kminus_L0PhotonDecision_TIS             ;
      Bool_t               Kminus_L0PhotonDecision_TOS             ;
      Bool_t               Kminus_Hlt1TrackMVADecision_Dec         ;
      Bool_t               Kminus_Hlt1TrackMVADecision_TIS         ;
      Bool_t               Kminus_Hlt1TrackMVADecision_TOS         ;
      Bool_t               Kminus_Hlt1TwoTrackMVADecision_Dec      ;
      Bool_t               Kminus_Hlt1TwoTrackMVADecision_TIS      ;
      Bool_t               Kminus_Hlt1TwoTrackMVADecision_TOS      ;
      Bool_t               Kminus_Hlt1CalibTrackingKPiDecision_Dec ;
      Bool_t               Kminus_Hlt1CalibTrackingKPiDecision_TIS ;
      Bool_t               Kminus_Hlt1CalibTrackingKPiDecision_TOS ;
      Bool_t               Kminus_Hlt1CalibTrackingKKDecision_Dec  ;
      Bool_t               Kminus_Hlt1CalibTrackingKKDecision_TIS  ;
      Bool_t               Kminus_Hlt1CalibTrackingKKDecision_TOS  ;
      Bool_t               Kminus_Hlt1CalibTrackingPiPiDecision_Dec;
      Bool_t               Kminus_Hlt1CalibTrackingPiPiDecision_TIS;
      Bool_t               Kminus_Hlt1CalibTrackingPiPiDecision_TOS;
      Bool_t               Kminus_Hlt1CalibTrackingKPiDetachedDecision_Dec;
      Bool_t               Kminus_Hlt1CalibTrackingKPiDetachedDecision_TIS;
      Bool_t               Kminus_Hlt1CalibTrackingKPiDetachedDecision_TOS;
      Int_t                Kminus_TRACK_Type                       ;
      Int_t                Kminus_TRACK_Key                        ;
      Double_t             Kminus_TRACK_CHI2NDOF                   ;
      Double_t             Kminus_TRACK_PCHI2                      ;
      Double_t             Kminus_TRACK_MatchCHI2                  ;
      Double_t             Kminus_TRACK_GhostProb                  ;
      Double_t             Kminus_TRACK_CloneDist                  ;
      Double_t             Kminus_TRACK_Likelihood                 ;
      Double_t             piplus_BPVVDZ                           ;
      Double_t             piplus_DIRA_OWNPV                       ;
      Double_t             piplus_ENDVERTEX_CHI2                   ;
      Double_t             piplus_FD_CHI2                          ;
      Double_t             piplus_LIFETIME                         ;
      Double_t             piplus_MINIP                            ;
      Double_t             piplus_MINIPCHI2                        ;
      Double_t             piplus_P_Parallel                       ;
      Double_t             piplus_P_Perp                           ;
      Double_t             piplus_X_travelled                      ;
      Double_t             piplus_Y_travelled                      ;
      Double_t             piplus_Z_travelled                      ;
      Double_t             piplus_CosTheta                         ;
      Double_t             piplus_P                                ;
      Double_t             piplus_PT                               ;
      Double_t             piplus_PE                               ;
      Double_t             piplus_PX                               ;
      Double_t             piplus_PY                               ;
      Double_t             piplus_PZ                               ;
      Double_t             piplus_M                                ;
      Int_t                piplus_ID                               ;
      Double_t             piplus_PIDe                             ;
      Double_t             piplus_PIDmu                            ;
      Double_t             piplus_PIDK                             ;
      Double_t             piplus_PIDp                             ;
      Double_t             piplus_ProbNNe                          ;
      Double_t             piplus_ProbNNk                          ;
      Double_t             piplus_ProbNNp                          ;
      Double_t             piplus_ProbNNpi                         ;
      Double_t             piplus_ProbNNmu                         ;
      Double_t             piplus_ProbNNghost                      ;
      Bool_t               piplus_hasMuon                          ;
      Bool_t               piplus_isMuon                           ;
      Bool_t               piplus_hasRich                          ;
      Bool_t               piplus_hasCalo                          ;
      Bool_t               piplus_L0Global_Dec                     ;
      Bool_t               piplus_L0Global_TIS                     ;
      Bool_t               piplus_L0Global_TOS                     ;
      Bool_t               piplus_Hlt1Global_Dec                   ;
      Bool_t               piplus_Hlt1Global_TIS                   ;
      Bool_t               piplus_Hlt1Global_TOS                   ;
      Bool_t               piplus_Hlt1Phys_Dec                     ;
      Bool_t               piplus_Hlt1Phys_TIS                     ;
      Bool_t               piplus_Hlt1Phys_TOS                     ;
      Bool_t               piplus_Hlt2Global_Dec                   ;
      Bool_t               piplus_Hlt2Global_TIS                   ;
      Bool_t               piplus_Hlt2Global_TOS                   ;
      Bool_t               piplus_Hlt2Phys_Dec                     ;
      Bool_t               piplus_Hlt2Phys_TIS                     ;
      Bool_t               piplus_Hlt2Phys_TOS                     ;
      Bool_t               piplus_L0HadronDecision_Dec             ;
      Bool_t               piplus_L0HadronDecision_TIS             ;
      Bool_t               piplus_L0HadronDecision_TOS             ;
      Bool_t               piplus_L0MuonDecision_Dec               ;
      Bool_t               piplus_L0MuonDecision_TIS               ;
      Bool_t               piplus_L0MuonDecision_TOS               ;
      Bool_t               piplus_L0DiMuonDecision_Dec             ;
      Bool_t               piplus_L0DiMuonDecision_TIS             ;
      Bool_t               piplus_L0DiMuonDecision_TOS             ;
      Bool_t               piplus_L0ElectronDecision_Dec           ;
      Bool_t               piplus_L0ElectronDecision_TIS           ;
      Bool_t               piplus_L0ElectronDecision_TOS           ;
      Bool_t               piplus_L0PhotonDecision_Dec             ;
      Bool_t               piplus_L0PhotonDecision_TIS             ;
      Bool_t               piplus_L0PhotonDecision_TOS             ;
      Bool_t               piplus_Hlt1TrackMVADecision_Dec         ;
      Bool_t               piplus_Hlt1TrackMVADecision_TIS         ;
      Bool_t               piplus_Hlt1TrackMVADecision_TOS         ;
      Bool_t               piplus_Hlt1TwoTrackMVADecision_Dec      ;
      Bool_t               piplus_Hlt1TwoTrackMVADecision_TIS      ;
      Bool_t               piplus_Hlt1TwoTrackMVADecision_TOS      ;
      Bool_t               piplus_Hlt1CalibTrackingKPiDecision_Dec ;
      Bool_t               piplus_Hlt1CalibTrackingKPiDecision_TIS ;
      Bool_t               piplus_Hlt1CalibTrackingKPiDecision_TOS ;
      Bool_t               piplus_Hlt1CalibTrackingKKDecision_Dec  ;
      Bool_t               piplus_Hlt1CalibTrackingKKDecision_TIS  ;
      Bool_t               piplus_Hlt1CalibTrackingKKDecision_TOS  ;
      Bool_t               piplus_Hlt1CalibTrackingPiPiDecision_Dec;
      Bool_t               piplus_Hlt1CalibTrackingPiPiDecision_TIS;
      Bool_t               piplus_Hlt1CalibTrackingPiPiDecision_TOS;
      Bool_t               piplus_Hlt1CalibTrackingKPiDetachedDecision_Dec;
      Bool_t               piplus_Hlt1CalibTrackingKPiDetachedDecision_TIS;
      Bool_t               piplus_Hlt1CalibTrackingKPiDetachedDecision_TOS;
      Int_t                piplus_TRACK_Type                       ;
      Int_t                piplus_TRACK_Key                        ;
      Double_t             piplus_TRACK_CHI2NDOF                   ;
      Double_t             piplus_TRACK_PCHI2                      ;
      Double_t             piplus_TRACK_MatchCHI2                  ;
      Double_t             piplus_TRACK_GhostProb                  ;
      Double_t             piplus_TRACK_CloneDist                  ;
      Double_t             piplus_TRACK_Likelihood                 ;
      Double_t             piplus0_BPVVDZ                          ;
      Double_t             piplus0_DIRA_OWNPV                      ;
      Double_t             piplus0_ENDVERTEX_CHI2                  ;
      Double_t             piplus0_FD_CHI2                         ;
      Double_t             piplus0_LIFETIME                        ;
      Double_t             piplus0_MINIP                           ;
      Double_t             piplus0_MINIPCHI2                       ;
      Double_t             piplus0_P_Parallel                      ;
      Double_t             piplus0_P_Perp                          ;
      Double_t             piplus0_X_travelled                     ;
      Double_t             piplus0_Y_travelled                     ;
      Double_t             piplus0_Z_travelled                     ;
      Double_t             piplus0_CosTheta                        ;
      Double_t             piplus0_P                               ;
      Double_t             piplus0_PT                              ;
      Double_t             piplus0_PE                              ;
      Double_t             piplus0_PX                              ;
      Double_t             piplus0_PY                              ;
      Double_t             piplus0_PZ                              ;
      Double_t             piplus0_M                               ;
      Int_t                piplus0_ID                              ;
      Double_t             piplus0_PIDe                            ;
      Double_t             piplus0_PIDmu                           ;
      Double_t             piplus0_PIDK                            ;
      Double_t             piplus0_PIDp                            ;
      Double_t             piplus0_ProbNNe                         ;
      Double_t             piplus0_ProbNNk                         ;
      Double_t             piplus0_ProbNNp                         ;
      Double_t             piplus0_ProbNNpi                        ;
      Double_t             piplus0_ProbNNmu                        ;
      Double_t             piplus0_ProbNNghost                     ;
      Bool_t               piplus0_hasMuon                         ;
      Bool_t               piplus0_isMuon                          ;
      Bool_t               piplus0_hasRich                         ;
      Bool_t               piplus0_hasCalo                         ;
      Bool_t               piplus0_L0Global_Dec                    ;
      Bool_t               piplus0_L0Global_TIS                    ;
      Bool_t               piplus0_L0Global_TOS                    ;
      Bool_t               piplus0_Hlt1Global_Dec                  ;
      Bool_t               piplus0_Hlt1Global_TIS                  ;
      Bool_t               piplus0_Hlt1Global_TOS                  ;
      Bool_t               piplus0_Hlt1Phys_Dec                    ;
      Bool_t               piplus0_Hlt1Phys_TIS                    ;
      Bool_t               piplus0_Hlt1Phys_TOS                    ;
      Bool_t               piplus0_Hlt2Global_Dec                  ;
      Bool_t               piplus0_Hlt2Global_TIS                  ;
      Bool_t               piplus0_Hlt2Global_TOS                  ;
      Bool_t               piplus0_Hlt2Phys_Dec                    ;
      Bool_t               piplus0_Hlt2Phys_TIS                    ;
      Bool_t               piplus0_Hlt2Phys_TOS                    ;
      Bool_t               piplus0_L0HadronDecision_Dec            ;
      Bool_t               piplus0_L0HadronDecision_TIS            ;
      Bool_t               piplus0_L0HadronDecision_TOS            ;
      Bool_t               piplus0_L0MuonDecision_Dec              ;
      Bool_t               piplus0_L0MuonDecision_TIS              ;
      Bool_t               piplus0_L0MuonDecision_TOS              ;
      Bool_t               piplus0_L0DiMuonDecision_Dec            ;
      Bool_t               piplus0_L0DiMuonDecision_TIS            ;
      Bool_t               piplus0_L0DiMuonDecision_TOS            ;
      Bool_t               piplus0_L0ElectronDecision_Dec          ;
      Bool_t               piplus0_L0ElectronDecision_TIS          ;
      Bool_t               piplus0_L0ElectronDecision_TOS          ;
      Bool_t               piplus0_L0PhotonDecision_Dec            ;
      Bool_t               piplus0_L0PhotonDecision_TIS            ;
      Bool_t               piplus0_L0PhotonDecision_TOS            ;
      Bool_t               piplus0_Hlt1TrackMVADecision_Dec        ;
      Bool_t               piplus0_Hlt1TrackMVADecision_TIS        ;
      Bool_t               piplus0_Hlt1TrackMVADecision_TOS        ;
      Bool_t               piplus0_Hlt1TwoTrackMVADecision_Dec     ;
      Bool_t               piplus0_Hlt1TwoTrackMVADecision_TIS     ;
      Bool_t               piplus0_Hlt1TwoTrackMVADecision_TOS     ;
      Bool_t               piplus0_Hlt1CalibTrackingKPiDecision_Dec;
      Bool_t               piplus0_Hlt1CalibTrackingKPiDecision_TIS;
      Bool_t               piplus0_Hlt1CalibTrackingKPiDecision_TOS;
      Bool_t               piplus0_Hlt1CalibTrackingKKDecision_Dec ;
      Bool_t               piplus0_Hlt1CalibTrackingKKDecision_TIS ;
      Bool_t               piplus0_Hlt1CalibTrackingKKDecision_TOS ;
      Bool_t               piplus0_Hlt1CalibTrackingPiPiDecision_Dec;
      Bool_t               piplus0_Hlt1CalibTrackingPiPiDecision_TIS;
      Bool_t               piplus0_Hlt1CalibTrackingPiPiDecision_TOS;
      Bool_t               piplus0_Hlt1CalibTrackingKPiDetachedDecision_Dec;
      Bool_t               piplus0_Hlt1CalibTrackingKPiDetachedDecision_TIS;
      Bool_t               piplus0_Hlt1CalibTrackingKPiDetachedDecision_TOS;
      Int_t                piplus0_TRACK_Type                      ;
      Int_t                piplus0_TRACK_Key                       ;
      Double_t             piplus0_TRACK_CHI2NDOF                  ;
      Double_t             piplus0_TRACK_PCHI2                     ;
      Double_t             piplus0_TRACK_MatchCHI2                 ;
      Double_t             piplus0_TRACK_GhostProb                 ;
      Double_t             piplus0_TRACK_CloneDist                 ;
      Double_t             piplus0_TRACK_Likelihood                ;
      UInt_t               nCandidate                              ;
      ULong64_t            totCandidates                           ;
      ULong64_t            EventInSequence                         ;
      UInt_t               runNumber                               ;
      ULong64_t            eventNumber                             ;
      UInt_t               BCID                                    ;
      Int_t                BCType                                  ;
      UInt_t               OdinTCK                                 ;
      UInt_t               L0DUTCK                                 ;
      UInt_t               HLT1TCK                                 ;
      UInt_t               HLT2TCK                                 ;
      ULong64_t            GpsTime                                 ;
      Short_t              Polarity                                ;
      Int_t                nPVs                                    ;
      Int_t                nTracks                                 ;
      Int_t                nLongTracks                             ;
      Int_t                nDownstreamTracks                       ;
      Int_t                nUpstreamTracks                         ;
      Int_t                nVeloTracks                             ;
      Int_t                nTTracks                                ;
      Int_t                nBackTracks                             ;
      Int_t                nRich1Hits                              ;
      Int_t                nRich2Hits                              ;
      Int_t                nVeloClusters                           ;
      Int_t                nITClusters                             ;
      Int_t                nTTClusters                             ;
      Int_t                nOTClusters                             ;
      Int_t                nSPDHits                                ;
      Int_t                nMuonCoordsS0                           ;
      Int_t                nMuonCoordsS1                           ;
      Int_t                nMuonCoordsS2                           ;
      Int_t                nMuonCoordsS3                           ;
      Int_t                nMuonCoordsS4                           ;
      Int_t                nMuonTracks                             ;
      Int_t                L0Global                                ;
      UInt_t               Hlt1Global                              ;
      UInt_t               Hlt2Global                              ;
      Int_t                L0HadronDecision                        ;
      Int_t                L0MuonDecision                          ;
      Int_t                L0DiMuonDecision                        ;
      Int_t                L0ElectronDecision                      ;
      Int_t                L0PhotonDecision                        ;
      UInt_t               L0nSelections                           ;
      Int_t                Hlt1TrackMVADecision                    ;
      Int_t                Hlt1TwoTrackMVADecision                 ;
      Int_t                Hlt1CalibTrackingKPiDecision            ;
      Int_t                Hlt1CalibTrackingKKDecision             ;
      Int_t                Hlt1CalibTrackingPiPiDecision           ;
      Int_t                Hlt1CalibTrackingKPiDetachedDecision    ;
      UInt_t               Hlt1nSelections                         ;
      UInt_t               Hlt2nSelections                         ;
      Int_t                MaxRoutingBits                          ;
      Float_t              RoutingBits[100]                        ;
  };

}
#endif

