// Class: Read2012_BDT_1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::2012_BDT_1
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/29       [336413]
Creator        : matt
Date           : Mon Oct 26 13:57:43 2015
Host           : Darwin pc7.home 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
Dir            : /Users/matt/Scratch/lhcb/LHCbAnalysis/Bc2Dmunu
Training events: 210151
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "-1" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
NegWeightTreatment: "ignorenegweightsintraining" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
Bplus_LOGMINIPCHI2            Bplus_LOGMINIPCHI2            Bplus_LOGMINIPCHI2            Bplus_LOGMINIPCHI2                                              'F'    [-10.281165123,11.2229137421]
Bplus_DIRA_OWNPV              Bplus_DIRA_OWNPV              Bplus_DIRA_OWNPV              Bplus_DIRA_OWNPV                                                'F'    [0.999000012875,1]
Bplus_TAU                     Bplus_TAU                     Bplus_TAU                     Bplus_TAU                                                       'F'    [1.3247626157e-05,0.0955683887005]
D0_LOGMINIPCHI2               D0_LOGMINIPCHI2               D0_LOGMINIPCHI2               D0_LOGMINIPCHI2                                                 'F'    [-7.94591331482,11.4622821808]
D0_PT                         D0_PT                         D0_PT                         D0_PT                                                           'F'    [7.85547876358,37620.3164062]
D0_ENDVERTEX_CHI2             D0_ENDVERTEX_CHI2             D0_ENDVERTEX_CHI2             D0_ENDVERTEX_CHI2                                               'F'    [1.90863126627e-13,5.99969148636]
Bplus_ENDVERTEX_CHI2          Bplus_ENDVERTEX_CHI2          Bplus_ENDVERTEX_CHI2          Bplus_ENDVERTEX_CHI2                                            'F'    [8.1991173833e-13,5.99978017807]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new 2012_BDT_1Node
   
#ifndef 2012_BDT_1Node__def
#define 2012_BDT_1Node__def
   
class 2012_BDT_1Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   2012_BDT_1Node ( 2012_BDT_1Node* left,2012_BDT_1Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~2012_BDT_1Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   2012_BDT_1Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   2012_BDT_1Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   2012_BDT_1Node*   fLeft;     // pointer to the left daughter node
   2012_BDT_1Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   2012_BDT_1Node::~2012_BDT_1Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool 2012_BDT_1Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool 2012_BDT_1Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Read2012_BDT_1 : public IClassifierReader {

 public:

   // constructor
   Read2012_BDT_1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Read2012_BDT_1" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Bplus_LOGMINIPCHI2", "Bplus_DIRA_OWNPV", "Bplus_TAU", "D0_LOGMINIPCHI2", "D0_PT", "D0_ENDVERTEX_CHI2", "Bplus_ENDVERTEX_CHI2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Read2012_BDT_1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<2012_BDT_1Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Read2012_BDT_1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      2012_BDT_1Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(2012_BDT_1Node*)current->GetRight();
         else current=(2012_BDT_1Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void Read2012_BDT_1::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.413236067628461);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.92851, 1, 1, 0.67346,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.227097,-99) , 
2, 0.0019387, 1, 0, 0.632906,-99) , 
NN(
0, 
0, 
-1, 0.00308969, 1, -1, 0.284695,-99) , 
0, 3.75927, 1, 0, 0.493736,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.244313);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.84368, 1, 1, 0.573772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.105853,-99) , 
2, 0.00299502, 1, 0, 0.553405,-99) , 
NN(
0, 
0, 
-1, 0.0020871, 1, -1, 0.233526,-99) , 
0, 4.95559, 1, 0, 0.496024,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.284091);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.000927484, 1, 1, 0.676348,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376238,-99) , 
2, 0.00115436, 1, 0, 0.547453,-99) , 
0, 1.7571, 1, 0, 0.609743,-99) , 
NN(
0, 
0, 
-1, 0.00402934, 1, -1, 0.369367,-99) , 
0, 2.94475, 1, 0, 0.473489,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.183406);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.140522,-99) , 
2, 0.00278529, 1, 0, 0.527963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.292948,-99) , 
0, 5.30176, 1, 0, 0.507498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0479092,-99) , 
2, 0.00386034, 1, 0, 0.482228,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.160666);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2483.78, 0, 1, 0.588198,-99) , 
NN(
0, 
0, 
-1, 4.64079, 1, -1, 0.454578,-99) , 
0, 2.1483, 1, 0, 0.491782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0768775,-99) , 
2, 0.00366195, 1, 0, 0.466469,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.146924);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.36489, 1, 1, 0.542362,-99) , 
NN(
0, 
0, 
-1, 4.64542, 1, -1, 0.443503,-99) , 
4, 2507.94, 0, 0, 0.511126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0581816,-99) , 
2, 0.00346773, 1, 0, 0.481186,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.119374);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492177,-99) , 
4, 5735.99, 0, 0, 0.509345,-99) , 
NN(
0, 
0, 
-1, 0.00266489, 1, -1, 0.361948,-99) , 
0, 4.73378, 1, 0, 0.485321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0524399,-99) , 
2, 0.00396296, 1, 0, 0.465787,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.170739);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.197716,-99) , 
2, 0.00241503, 1, 0, 0.530098,-99) , 
NN(
0, 
0, 
-1, 0.00300478, 1, -1, 0.401787,-99) , 
0, 4.3788, 1, 0, 0.501789,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0628699,-99) , 
2, 0.00376505, 1, 0, 0.479154,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.118071);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572576,-99) , 
NN(
0, 
0, 
-1, 4.50397, 1, -1, 0.465781,-99) , 
0, 1.54986, 1, 0, 0.485301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0813511,-99) , 
2, 0.00388091, 1, 0, 0.466536,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0962018);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.157582,-99) , 
2, 0.0031625, 1, 0, 0.508753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.291305,-99) , 
0, 5.88958, 1, 0, 0.500679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0789007,-99) , 
2, 0.00399622, 1, 0, 0.483354,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0864171);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485478,-99) , 
0, 1.1181, 1, 0, 0.495816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302431,-99) , 
0, 6.06319, 1, 0, 0.490541,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0716361,-99) , 
2, 0.00386046, 1, 0, 0.472596,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.107251);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.227323,-99) , 
2, 0.00223947, 1, 0, 0.520707,-99) , 
NN(
0, 
0, 
-1, 2132.55, 0, -1, 0.477769,-99) , 
3, 5.03486, 1, 0, 0.505532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.10538,-99) , 
2, 0.00374381, 1, 0, 0.486523,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0782488);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447076,-99) , 
0, 5.65438, 1, 0, 0.506031,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264982,-99) , 
2, 0.00195432, 1, 0, 0.439431,-99) , 
4, 1663.24, 0, 0, 0.496176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.119468,-99) , 
2, 0.00357286, 1, 0, 0.476201,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0605197);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406815,-99) , 
0, 5.9981, 1, 0, 0.496886,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.252115,-99) , 
2, 0.0021433, 1, 0, 0.448198,-99) , 
4, 2049.48, 0, 0, 0.485747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0859953,-99) , 
2, 0.00398345, 1, 0, 0.47081,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0987304);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.18985,-99) , 
2, 0.00263311, 1, 0, 0.494582,-99) , 
NN(
0, 
0, 
-1, 4.01306, 1, -1, 0.450561,-99) , 
4, 2879.22, 0, 0, 0.476934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.123857,-99) , 
2, 0.00392495, 1, 0, 0.462959,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0829388);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47776,-99) , 
0, 0.847336, 1, 0, 0.482062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389706,-99) , 
0, 5.404, 1, 0, 0.475461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0832411,-99) , 
2, 0.00405482, 1, 0, 0.462187,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0687487);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486644,-99) , 
4, 6176.16, 0, 0, 0.491476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353636,-99) , 
0, 6.02308, 1, 0, 0.48799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0888378,-99) , 
2, 0.0036999, 1, 0, 0.471239,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0592851);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486973,-99) , 
5, 0.168183, 1, 0, 0.496127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392635,-99) , 
0, 6.14002, 1, 0, 0.493506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0933678,-99) , 
2, 0.00406028, 1, 0, 0.48016,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0620494);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456261,-99) , 
0, 5.41292, 1, 0, 0.50337,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442721,-99) , 
6, 0.00933754, 0, 0, 0.49944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.132532,-99) , 
2, 0.00339914, 1, 0, 0.479826,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0493428);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.00401252, 1, -1, 0.475349,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0582665);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.00392248, 1, -1, 0.4709,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0589431);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449912,-99) , 
5, 0.0082383, 0, 0, 0.503544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432735,-99) , 
0, 5.80504, 1, 0, 0.501158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.113991,-99) , 
2, 0.00348179, 1, 0, 0.482712,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0486788);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465627,-99) , 
3, 2.34454, 0, 0, 0.501187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450855,-99) , 
0, 5.3204, 1, 0, 0.497367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.148944,-99) , 
2, 0.00379226, 1, 0, 0.483951,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0498816);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456721,-99) , 
4, 1877.13, 0, 0, 0.492869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390979,-99) , 
3, 6.95771, 1, 0, 0.489389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.116664,-99) , 
2, 0.0040123, 1, 0, 0.477319,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0604773);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535776,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470406,-99) , 
5, 0.936544, 0, 0, 0.482892,-99) , 
4, 7418.5, 0, 0, 0.487175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.108547,-99) , 
2, 0.00433084, 1, 0, 0.477513,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0580088);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486204,-99) , 
6, 0.0358586, 1, 0, 0.490377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439627,-99) , 
4, 887.204, 0, 0, 0.488088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0931806,-99) , 
2, 0.00392617, 1, 0, 0.475141,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0411019);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496118,-99) , 
0, 5.26003, 0, 0, 0.499889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404952,-99) , 
0, 6.06694, 1, 0, 0.497517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.163695,-99) , 
2, 0.00391234, 1, 0, 0.486053,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0649429);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475868,-99) , 
3, 3.253, 0, 0, 0.503135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446971,-99) , 
3, 6.23546, 1, 0, 0.497515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.124064,-99) , 
2, 0.00367486, 1, 0, 0.482798,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0459418);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577704,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458397,-99) , 
0, 4.53635, 1, 0, 0.494751,-99) , 
0, 5.69535, 0, 0, 0.49914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.208152,-99) , 
2, 0.00356542, 1, 0, 0.486178,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0684129);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0027585, 1, -1, 0.489535,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313348,-99) , 
2, 0.00226417, 1, 0, 0.447665,-99) , 
3, 6.16094, 1, 0, 0.484733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.13513,-99) , 
2, 0.00386031, 1, 0, 0.473118,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.109702);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342674,-99) , 
2, 0.00307303, 1, 0, 0.512617,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287792,-99) , 
2, 0.00164015, 1, 0, 0.480509,-99) , 
5, 1.02409, 1, 0, 0.501503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.100727,-99) , 
2, 0.00395605, 1, 0, 0.489757,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0644852);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527686,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478574,-99) , 
3, 7.02527, 0, 0, 0.481121,-99) , 
3, 1.9167, 1, 0, 0.48453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.167386,-99) , 
2, 0.00396635, 1, 0, 0.474793,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0418115);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.191054,-99) , 
2, 0.00309013, 1, 0, 0.496973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446353,-99) , 
3, 6.68907, 1, 0, 0.494158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.143588,-99) , 
2, 0.0040123, 1, 0, 0.484308,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0856198);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392789,-99) , 
2, 0.00199715, 1, 0, 0.545454,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479696,-99) , 
5, 1.8846, 0, 0, 0.486117,-99) , 
0, 5.06976, 0, 0, 0.493402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.209012,-99) , 
2, 0.00388079, 1, 0, 0.484153,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0473906);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571895,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465395,-99) , 
5, 1.37974, 1, 0, 0.492293,-99) , 
3, 6.91744, 0, 0, 0.495989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.156922,-99) , 
2, 0.00396289, 1, 0, 0.486208,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0703612);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538686,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477102,-99) , 
5, 1.5621, 1, 0, 0.524647,-99) , 
NN(
0, 
0, 
-1, 0.00199311, 1, -1, 0.484888,-99) , 
0, 3.74198, 0, 0, 0.499043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.214011,-99) , 
2, 0.0033151, 1, 0, 0.485103,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0577314);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479086,-99) , 
4, 5653.24, 1, 0, 0.5153,-99) , 
NN(
0, 
0, 
-1, 2270.16, 0, -1, 0.484421,-99) , 
0, 3.47888, 1, 0, 0.502504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.112288,-99) , 
2, 0.00406139, 1, 0, 0.492918,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0392908);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499258,-99) , 
5, 0.883799, 0, 0, 0.50856,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46339,-99) , 
5, 3.86952, 1, 0, 0.506059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.164571,-99) , 
2, 0.00398878, 1, 0, 0.496979,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0460304);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574131,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481796,-99) , 
5, 0.833143, 1, 0, 0.497133,-99) , 
3, 6.95198, 0, 0, 0.500348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.20756,-99) , 
2, 0.00379157, 1, 0, 0.490952,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.056655);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495611,-99) , 
6, 0.305526, 1, 0, 0.504188,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309574,-99) , 
2, 0.00122046, 1, 0, 0.478032,-99) , 
4, 6153, 1, 0, 0.500601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.148053,-99) , 
2, 0.00391221, 1, 0, 0.491105,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0490978);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451793,-99) , 
4, 7398.54, 1, 0, 0.507246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463419,-99) , 
6, 0.0227493, 0, 0, 0.502645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.191618,-99) , 
2, 0.00390988, 1, 0, 0.494016,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0408608);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481647,-99) , 
6, 0.156615, 0, 0, 0.499587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437934,-99) , 
0, 5.36794, 1, 0, 0.495281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.21323,-99) , 
2, 0.00406138, 1, 0, 0.487852,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0475909);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53231,-99) , 
NN(
0, 
0, 
-1, 0.213148, 0, -1, 0.486507,-99) , 
6, 0.011707, 1, 0, 0.490269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.159944,-99) , 
2, 0.00390079, 1, 0, 0.481388,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0498226);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543865,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488482,-99) , 
3, 3.64824, 1, 0, 0.495747,-99) , 
3, 6.50419, 0, 0, 0.49943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.228673,-99) , 
2, 0.00338735, 1, 0, 0.487651,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0334897);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375414,-99) , 
2, 0.00291026, 1, 0, 0.498279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442203,-99) , 
0, 5.20497, 1, 0, 0.493506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.202148,-99) , 
2, 0.00407609, 1, 0, 0.486371,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0807577);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321736,-99) , 
2, 0.00251819, 1, 0, 0.510555,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295216,-99) , 
2, 0.00228494, 1, 0, 0.485975,-99) , 
6, 0.52304, 0, 0, 0.498846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.198622,-99) , 
2, 0.0040614, 1, 0, 0.491672,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0503521);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559044,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497281,-99) , 
0, 5.54038, 0, 0, 0.502416,-99) , 
NN(
0, 
0, 
-1, 0.0016437, 1, -1, 0.473248,-99) , 
3, 4.25392, 0, 0, 0.489553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.282346,-99) , 
2, 0.00335837, 1, 0, 0.480082,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0595932);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493791,-99) , 
0, 3.58882, 0, 0, 0.512373,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.242454,-99) , 
2, 0.00129787, 1, 0, 0.471552,-99) , 
3, 3.70673, 0, 0, 0.500165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.239533,-99) , 
2, 0.00400903, 1, 0, 0.493595,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0411936);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408309,-99) , 
0, 6.06673, 1, 0, 0.502627,-99) , 
NN(
0, 
0, 
-1, 0.0012042, 1, -1, 0.467877,-99) , 
3, 3.49232, 0, 0, 0.493737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.231478,-99) , 
2, 0.00399707, 1, 0, 0.487183,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0475034);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543001,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483636,-99) , 
0, 2.83194, 1, 0, 0.493575,-99) , 
0, 5.56628, 0, 0, 0.496074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260728,-99) , 
2, 0.00321056, 1, 0, 0.484616,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0746679);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34472,-99) , 
2, 0.00284501, 1, 0, 0.506121,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342861,-99) , 
2, 0.00163805, 1, 0, 0.470503,-99) , 
6, 0.215102, 0, 0, 0.494877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.153426,-99) , 
2, 0.0041264, 1, 0, 0.488048,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0576043);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557351,-99) , 
NN(
0, 
0, 
-1, 0.194384, 1, -1, 0.479335,-99) , 
3, 7.02015, 0, 0, 0.482283,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.154756,-99) , 
2, 0.00407082, 1, 0, 0.475474,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0499387);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484458,-99) , 
0, 3.66957, 0, 0, 0.495447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423679,-99) , 
0, 5.35497, 1, 0, 0.490513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287026,-99) , 
2, 0.00406532, 1, 0, 0.485632,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0932282);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583482,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371395,-99) , 
2, 0.00142299, 1, 0, 0.517243,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47214,-99) , 
4, 2566.35, 1, 0, 0.483967,-99) , 
5, 0.103197, 1, 0, 0.492255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.115194,-99) , 
2, 0.00401627, 1, 0, 0.484789,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0538008);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394012,-99) , 
2, 0.00315738, 1, 0, 0.508323,-99) , 
NN(
0, 
0, 
-1, 0.00182004, 1, -1, 0.478039,-99) , 
3, 4.43579, 0, 0, 0.493812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.181943,-99) , 
2, 0.00430553, 1, 0, 0.488331,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0283542);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496093,-99) , 
5, 0.0288668, 1, 0, 0.500438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379966,-99) , 
0, 6.21136, 1, 0, 0.498185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.205535,-99) , 
2, 0.00433481, 1, 0, 0.493208,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0367005);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492705,-99) , 
4, 4125.71, 0, 0, 0.501668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432629,-99) , 
0, 5.72884, 1, 0, 0.49898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.259875,-99) , 
2, 0.00399649, 1, 0, 0.493539,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0467444);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334441,-99) , 
2, 0.00291023, 1, 0, 0.505639,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431545,-99) , 
0, 5.76038, 1, 0, 0.502934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.205369,-99) , 
2, 0.00392645, 1, 0, 0.496372,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0600197);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471481,-99) , 
4, 2136.92, 0, 0, 0.503159,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327287,-99) , 
2, 0.00226022, 1, 0, 0.452621,-99) , 
3, 6.17701, 1, 0, 0.497431,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343088,-99) , 
2, 0.00410104, 1, 0, 0.49388,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0555197);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411667,-99) , 
2, 0.00178988, 1, 0, 0.516145,-99) , 
NN(
0, 
0, 
-1, 0.00332869, 1, -1, 0.484985,-99) , 
4, 1511.88, 1, 0, 0.489163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.238884,-99) , 
2, 0.00432129, 1, 0, 0.484743,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0802088);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494597,-99) , 
3, 5.27608, 0, 0, 0.509734,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30234,-99) , 
2, 0.00154995, 1, 0, 0.486384,-99) , 
4, 3772.58, 1, 0, 0.500184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.301414,-99) , 
2, 0.0036763, 1, 0, 0.494334,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0353785);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 6.64661, 0, 1, 0.509613,-99) , 
NN(
0, 
0, 
-1, 0.00200104, 1, -1, 0.474084,-99) , 
4, 4260.95, 1, 0, 0.497948,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361711,-99) , 
2, 0.00414312, 1, 0, 0.494947,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0299607);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549575,-99) , 
NN(
0, 
0, 
-1, 5880.59, 1, -1, 0.491863,-99) , 
0, 5.69513, 0, 0, 0.494299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365183,-99) , 
2, 0.00340951, 1, 0, 0.489039,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.065403);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482618,-99) , 
3, 4.03356, 0, 0, 0.506267,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509575,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296536,-99) , 
2, 0.00155028, 1, 0, 0.47057,-99) , 
4, 4273.14, 1, 0, 0.494855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.216149,-99) , 
2, 0.00389811, 1, 0, 0.488831,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0991278);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310832,-99) , 
2, 0.00223958, 1, 0, 0.506734,-99) , 
NN(
0, 
0, 
-1, 0.00232304, 1, -1, 0.468632,-99) , 
4, 3616.82, 1, 0, 0.490189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.261089,-99) , 
2, 0.00419889, 1, 0, 0.48608,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0283103);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534136,-99) , 
NN(
0, 
0, 
-1, 6.21086, 1, -1, 0.491906,-99) , 
0, 5.24524, 0, 0, 0.495771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.256432,-99) , 
2, 0.00432724, 1, 0, 0.491998,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.030089);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543784,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493011,-99) , 
3, 3.90639, 1, 0, 0.500464,-99) , 
6, 0.00746241, 1, 0, 0.503358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.300531,-99) , 
2, 0.0042438, 1, 0, 0.499843,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0357604);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586628,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481617,-99) , 
4, 3023.39, 0, 0, 0.494171,-99) , 
3, 6.92169, 0, 0, 0.498275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.280812,-99) , 
2, 0.00393163, 1, 0, 0.493656,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0674214);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474554,-99) , 
5, 0.0551978, 0, 0, 0.520357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34135,-99) , 
2, 0.0015311, 1, 0, 0.488735,-99) , 
0, 3.14179, 0, 0, 0.504849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.199627,-99) , 
2, 0.00409685, 1, 0, 0.49982,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0720709);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362002,-99) , 
2, 0.00167806, 1, 0, 0.514192,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481503,-99) , 
3, 6.92175, 0, 0, 0.485114,-99) , 
5, 1.69575, 0, 0, 0.492037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323155,-99) , 
2, 0.00431225, 1, 0, 0.489157,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0485394);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487965,-99) , 
0, 4.80765, 0, 0, 0.495805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421731,-99) , 
6, 3.94394, 1, 0, 0.492097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.218879,-99) , 
2, 0.00392618, 1, 0, 0.486903,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0386463);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554035,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487549,-99) , 
4, 4111.33, 0, 0, 0.499796,-99) , 
4, 1012.65, 1, 0, 0.503402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355891,-99) , 
2, 0.00453804, 1, 0, 0.501232,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0233577);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580186,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454723,-99) , 
3, 2.24072, 0, 0, 0.496922,-99) , 
3, 7.04193, 0, 0, 0.500026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.28987,-99) , 
2, 0.00397337, 1, 0, 0.495942,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.052264);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493712,-99) , 
0, 4.59066, 1, 0, 0.520913,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384391,-99) , 
2, 0.00163798, 1, 0, 0.494622,-99) , 
0, 2.9207, 0, 0, 0.509304,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305558,-99) , 
2, 0.00372895, 1, 0, 0.504345,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0355332);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.59161, 0, 1, 0.518662,-99) , 
NN(
0, 
0, 
-1, 0.00277219, 1, -1, 0.487493,-99) , 
4, 2946.68, 1, 0, 0.50079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344856,-99) , 
2, 0.00408867, 1, 0, 0.497865,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0259682);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612081,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494189,-99) , 
3, 6.51739, 0, 0, 0.498486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.169581,-99) , 
2, 0.0041577, 1, 0, 0.496078,-99) , 
2, 0.00531459, 0, 0, 0.49776,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0508143);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.14669, 1, 1, 0.507749,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359959,-99) , 
2, 0.00109941, 1, 0, 0.471381,-99) , 
5, 2.1348, 1, 0, 0.501593,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313183,-99) , 
2, 0.00401896, 1, 0, 0.498118,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0322403);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546797,-99) , 
NN(
0, 
0, 
-1, 6.3105, 1, -1, 0.489549,-99) , 
3, 6.84977, 0, 0, 0.492213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310586,-99) , 
2, 0.00381564, 1, 0, 0.488143,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0592295);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373624,-99) , 
2, 0.00253064, 1, 0, 0.505699,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286458,-99) , 
2, 0.00223235, 1, 0, 0.484779,-99) , 
6, 0.216135, 0, 0, 0.499046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.231915,-99) , 
2, 0.00401222, 1, 0, 0.494545,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0502152);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485759,-99) , 
4, 3873.53, 0, 0, 0.508523,-99) , 
NN(
0, 
0, 
-1, 0.00241867, 1, -1, 0.477217,-99) , 
0, 4.35334, 0, 0, 0.484386,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388958,-99) , 
2, 0.0040124, 1, 0, 0.482451,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0255789);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559215,-99) , 
NN(
0, 
0, 
-1, 0.00371668, 1, -1, 0.492677,-99) , 
0, 5.61771, 0, 0, 0.496515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.230345,-99) , 
0, 6.7267, 1, 0, 0.49398,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0551509);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434241,-99) , 
2, 0.00110465, 1, 0, 0.518601,-99) , 
NN(
0, 
0, 
-1, 0.00344993, 1, -1, 0.49097,-99) , 
5, 0.0931149, 1, 0, 0.497383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303836,-99) , 
2, 0.00454857, 1, 0, 0.495008,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0461745);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.29189, 0, 1, 0.533107,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297084,-99) , 
2, 0.00280192, 1, 0, 0.49801,-99) , 
4, 2948.06, 1, 0, 0.513178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328969,-99) , 
2, 0.0043092, 1, 0, 0.510519,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0232718);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554434,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352064,-99) , 
2, 0.00306697, 1, 0, 0.500221,-99) , 
0, 5.57298, 0, 0, 0.503543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33597,-99) , 
2, 0.00411028, 1, 0, 0.500764,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0399618);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39085,-99) , 
2, 0.00248612, 1, 0, 0.533227,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356475,-99) , 
2, 0.00276539, 1, 0, 0.498323,-99) , 
3, 5.87128, 0, 0, 0.503457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422161,-99) , 
3, 6.9798, 1, 0, 0.500292,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.038191);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572771,-99) , 
NN(
0, 
0, 
-1, 2.29248, 1, -1, 0.48398,-99) , 
0, 6.20993, 0, 0, 0.486169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368219,-99) , 
2, 0.00438724, 1, 0, 0.484451,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0260024);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57317,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438797,-99) , 
0, 5.45079, 1, 0, 0.504733,-99) , 
0, 5.88418, 0, 0, 0.507437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356162,-99) , 
2, 0.00406114, 1, 0, 0.50482,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0569017);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570331,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495534,-99) , 
2, 0.00350488, 0, 0, 0.497995,-99) , 
0, 5.5715, 0, 0, 0.503639,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327084,-99) , 
2, 0.00113021, 1, 0, 0.468367,-99) , 
6, 2.27273, 1, 0, 0.498054,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0428511);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48391,-99) , 
5, 0.979118, 1, 0, 0.505563,-99) , 
NN(
0, 
0, 
-1, 0.00174343, 1, -1, 0.478971,-99) , 
3, 4.39452, 0, 0, 0.493082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.277721,-99) , 
2, 0.00430881, 1, 0, 0.490232,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0393716);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491948,-99) , 
4, 4292.43, 1, 0, 0.514471,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46769,-99) , 
3, 4.29476, 1, 0, 0.486644,-99) , 
0, 2.09171, 0, 0, 0.507159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37984,-99) , 
2, 0.00407081, 1, 0, 0.504921,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0278077);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615452,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466011,-99) , 
6, 2.55179, 1, 0, 0.49986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353573,-99) , 
3, 7.03437, 1, 0, 0.496753,-99) , 
3, 7.62003, 0, 0, 0.499032,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0551368);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450954,-99) , 
2, 0.00197366, 1, 0, 0.528167,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.236675,-99) , 
2, 0.00252634, 1, 0, 0.497345,-99) , 
3, 5.83722, 0, 0, 0.502857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.248422,-99) , 
2, 0.00396289, 1, 0, 0.498895,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0439877);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58768,-99) , 
NN(
0, 
0, 
-1, 0.00416941, 1, -1, 0.478819,-99) , 
2, 0.00530939, 0, 0, 0.480128,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0210784);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49634,-99) , 
2, 0.00450681, 0, 0, 0.497852,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462256,-99) , 
3, 2.65838, 0, 0, 0.493326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39921,-99) , 
3, 7.54654, 1, 0, 0.491972,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0266953);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604571,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492799,-99) , 
0, 4.80706, 0, 0, 0.497579,-99) , 
2, 0.00393071, 0, 0, 0.499567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413851,-99) , 
0, 6.34308, 1, 0, 0.497773,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0340943);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571347,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488419,-99) , 
6, 0.561833, 0, 0, 0.49972,-99) , 
0, 5.88974, 0, 0, 0.502557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.251871,-99) , 
2, 0.00400078, 1, 0, 0.49871,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0470072);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00334854, 0, 1, 0.509189,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.324515,-99) , 
2, 0.00208708, 1, 0, 0.454422,-99) , 
0, 5.00667, 1, 0, 0.502804,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0540839);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586796,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430033,-99) , 
2, 0.00206393, 1, 0, 0.520189,-99) , 
NN(
0, 
0, 
-1, 4.23051, 1, -1, 0.485944,-99) , 
3, 5.83215, 0, 0, 0.491471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442487,-99) , 
0, 5.42982, 1, 0, 0.487935,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0654187);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 6.8196, 0, 1, 0.511076,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374661,-99) , 
2, 0.00102015, 1, 0, 0.475901,-99) , 
6, 1.70373, 1, 0, 0.503104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352329,-99) , 
2, 0.00418372, 1, 0, 0.500865,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0452949);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670789,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387375,-99) , 
2, 0.00214927, 1, 0, 0.500628,-99) , 
NN(
0, 
0, 
-1, 0.00303216, 1, -1, 0.459957,-99) , 
0, 3.98111, 1, 0, 0.488893,-99) , 
2, 0.00530819, 0, 0, 0.491531,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.0251662);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542988,-99) , 
NN(
0, 
0, 
-1, 0.00305905, 1, -1, 0.48977,-99) , 
0, 5.583, 0, 0, 0.493589,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0322757);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403899,-99) , 
2, 0.00429028, 1, 0, 0.502839,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358249,-99) , 
2, 0.00075327, 1, 0, 0.464382,-99) , 
3, 2.84708, 0, 0, 0.49723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460416,-99) , 
5, 0.0195574, 0, 0, 0.493539,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.041116);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608787,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484852,-99) , 
3, 5.8408, 0, 0, 0.491784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296135,-99) , 
2, 0.00399588, 1, 0, 0.489654,-99) , 
3, 7.61648, 0, 0, 0.491812,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.0302792);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495968,-99) , 
0, 4.26296, 0, 0, 0.538597,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493363,-99) , 
2, 0.00351804, 0, 0, 0.496359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404154,-99) , 
0, 6.08144, 1, 0, 0.493625,-99) , 
4, 1259.68, 1, 0, 0.498152,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.0183436);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.625513,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38718,-99) , 
2, 0.00330378, 1, 0, 0.498838,-99) , 
0, 5.88415, 0, 0, 0.502323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38493,-99) , 
0, 6.32811, 1, 0, 0.500038,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.0275782);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540539,-99) , 
NN(
0, 
0, 
-1, 6.34305, 1, -1, 0.491893,-99) , 
4, 1498.78, 1, 0, 0.496737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421501,-99) , 
4, 808.92, 0, 0, 0.493993,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.0450774);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546253,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433947,-99) , 
2, 0.00284495, 1, 0, 0.499552,-99) , 
4, 1215.23, 1, 0, 0.504144,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296413,-99) , 
2, 0.00135396, 1, 0, 0.453575,-99) , 
6, 2.28982, 1, 0, 0.496427,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.0169335);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535138,-99) , 
NN(
0, 
0, 
-1, 5.99027, 1, -1, 0.493955,-99) , 
3, 6.5716, 0, 0, 0.497383,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0584083);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605427,-99) , 
NN(
NN(
0, 
0, 
-1, 3.51188, 0, 1, 0.507837,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364322,-99) , 
2, 0.00124279, 1, 0, 0.475509,-99) , 
6, 0.162271, 0, 0, 0.499175,-99) , 
3, 7.3766, 0, 0, 0.501989,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.0376204);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578712,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483133,-99) , 
0, 3.94476, 0, 0, 0.491778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37202,-99) , 
0, 6.29875, 1, 0, 0.489934,-99) , 
3, 7.37647, 0, 0, 0.492278,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.0858972);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423842,-99) , 
2, 0.0017757, 1, 0, 0.515469,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354194,-99) , 
2, 0.00193592, 1, 0, 0.48809,-99) , 
6, 0.418334, 1, 0, 0.498763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452441,-99) , 
6, 0.0156366, 0, 0, 0.494899,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.0450375);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54368,-99) , 
NN(
0, 
0, 
-1, 0.162878, 0, -1, 0.478593,-99) , 
0, 5.88973, 0, 0, 0.481798,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.0472798);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543357,-99) , 
NN(
0, 
0, 
-1, 7.12516, 1, -1, 0.494929,-99) , 
5, 0.749335, 0, 0, 0.500807,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486606,-99) , 
0, 4.07039, 0, 0, 0.502676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323244,-99) , 
2, 0.00184901, 1, 0, 0.471262,-99) , 
5, 1.0241, 1, 0, 0.490829,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.0741614);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618004,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340249,-99) , 
2, 0.00164044, 1, 0, 0.508487,-99) , 
3, 6.38363, 0, 0, 0.521201,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480367,-99) , 
3, 6.63374, 0, 0, 0.484636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397434,-99) , 
2, 0.00339914, 1, 0, 0.481774,-99) , 
6, 0.143039, 1, 0, 0.492545,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.0235282);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662648,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476856,-99) , 
3, 3.19926, 0, 0, 0.498568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.207244,-99) , 
2, 0.00413766, 1, 0, 0.49679,-99) , 
2, 0.00530116, 0, 0, 0.499078,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.0343869);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481793,-99) , 
3, 3.31746, 0, 0, 0.510372,-99) , 
NN(
0, 
0, 
-1, 0.00275916, 1, -1, 0.487734,-99) , 
6, 0.589763, 1, 0, 0.499417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369539,-99) , 
0, 6.46032, 1, 0, 0.497392,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.0125683);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 5.98636, 0, 1, 0.504863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407581,-99) , 
0, 6.45776, 1, 0, 0.503283,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.0217655);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495513,-99) , 
2, 0.00388788, 0, 0, 0.497308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402069,-99) , 
3, 7.33074, 1, 0, 0.495794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.19925,-99) , 
0, 6.52997, 1, 0, 0.492493,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.0271696);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492271,-99) , 
4, 2771.79, 1, 0, 0.499994,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456276,-99) , 
4, 1076.77, 0, 0, 0.497268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390593,-99) , 
2, 0.00430881, 1, 0, 0.495816,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.0308314);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536204,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382456,-99) , 
2, 0.00284347, 1, 0, 0.502688,-99) , 
4, 1207.17, 1, 0, 0.505709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407657,-99) , 
2, 0.00430882, 1, 0, 0.504323,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.0240172);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00366758, 0, 1, 0.505234,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32944,-99) , 
2, 0.00149416, 1, 0, 0.466842,-99) , 
5, 2.8594, 1, 0, 0.501137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345875,-99) , 
2, 0.00453786, 1, 0, 0.499439,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.0287441);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414269,-99) , 
2, 0.00257068, 1, 0, 0.501421,-99) , 
NN(
0, 
0, 
-1, 0.00430881, 1, -1, 0.46566,-99) , 
3, 6.03947, 1, 0, 0.496387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43342,-99) , 
5, 3.99537, 1, 0, 0.493467,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.0605144);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469363,-99) , 
2, 0.000872641, 1, 0, 0.522679,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483796,-99) , 
4, 1118.9, 1, 0, 0.487231,-99) , 
6, 1.53058, 0, 0, 0.496792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341354,-99) , 
2, 0.00433483, 1, 0, 0.494924,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.0166405);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565796,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468012,-99) , 
4, 1418.93, 0, 0, 0.497642,-99) , 
2, 0.00344787, 0, 0, 0.499701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361753,-99) , 
0, 6.50674, 1, 0, 0.497805,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.0429811);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2672.99, 1, 1, 0.543489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462956,-99) , 
6, 2.2443, 1, 0, 0.531622,-99) , 
NN(
0, 
0, 
-1, 1396.5, 0, -1, 0.485432,-99) , 
3, 5.57468, 0, 0, 0.496842,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.0483656);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357935,-99) , 
2, 0.00182029, 1, 0, 0.505826,-99) , 
NN(
0, 
0, 
-1, 0.00352998, 1, -1, 0.477486,-99) , 
3, 4.27882, 1, 0, 0.490533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.221889,-99) , 
0, 6.66895, 1, 0, 0.48814,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.0295552);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.689161,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467354,-99) , 
0, 5.08098, 1, 0, 0.504662,-99) , 
2, 0.00399723, 0, 0, 0.507444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441449,-99) , 
3, 6.84849, 1, 0, 0.504429,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.0240059);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541235,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597637,-99) , 
NN(
0, 
0, 
-1, 0.00313134, 1, -1, 0.491081,-99) , 
2, 0.00521104, 0, 0, 0.492313,-99) , 
5, 0.00642909, 1, 0, 0.495528,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.0264177);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539015,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480864,-99) , 
4, 4466.19, 1, 0, 0.498538,-99) , 
0, 5.52475, 0, 0, 0.501059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372093,-99) , 
2, 0.00430914, 1, 0, 0.499437,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.0270929);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634458,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493656,-99) , 
5, 0.0588759, 1, 0, 0.500081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.249187,-99) , 
2, 0.00401228, 1, 0, 0.498288,-99) , 
2, 0.0053077, 0, 0, 0.499907,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.0207789);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541219,-99) , 
NN(
0, 
0, 
-1, 6.02305, 1, -1, 0.497164,-99) , 
3, 6.38446, 0, 0, 0.501733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41719,-99) , 
5, 0.00494713, 0, 0, 0.49776,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.0416008);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483201,-99) , 
5, 2.42927, 1, 0, 0.51389,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4057,-99) , 
2, 0.00210186, 1, 0, 0.481672,-99) , 
4, 1396.94, 0, 0, 0.510351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390297,-99) , 
0, 6.51055, 1, 0, 0.508737,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.064818);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380962,-99) , 
2, 0.00321049, 1, 0, 0.531196,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453431,-99) , 
4, 1688.49, 0, 0, 0.495939,-99) , 
0, 3.78403, 0, 0, 0.508572,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560036,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486832,-99) , 
0, 3.4672, 0, 0, 0.51006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367823,-99) , 
2, 0.00163822, 1, 0, 0.475662,-99) , 
5, 0.139004, 0, 0, 0.499864,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0432465);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563056,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428331,-99) , 
3, 6.17698, 1, 0, 0.494246,-99) , 
0, 5.54624, 0, 0, 0.499342,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459977,-99) , 
3, 4.92385, 0, 0, 0.481518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384072,-99) , 
2, 0.00229954, 1, 0, 0.470698,-99) , 
6, 0.220228, 0, 0, 0.49022,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.0395114);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.704061,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48697,-99) , 
3, 6.66447, 0, 0, 0.491226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.241116,-99) , 
2, 0.00413732, 1, 0, 0.489778,-99) , 
2, 0.00531571, 0, 0, 0.492867,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.0218008);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659869,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49677,-99) , 
6, 0.0131851, 1, 0, 0.500269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428898,-99) , 
4, 837.213, 0, 0, 0.497573,-99) , 
2, 0.00499012, 0, 0, 0.500026,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.0390742);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571249,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487763,-99) , 
5, 1.97355, 0, 0, 0.494749,-99) , 
3, 6.7242, 0, 0, 0.499491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.324758,-99) , 
2, 0.00430881, 1, 0, 0.497509,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.0247135);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.74467,-99) , 
NN(
NN(
0, 
0, 
-1, 5.00006, 0, 1, 0.506831,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431736,-99) , 
0, 6.02026, 1, 0, 0.5049,-99) , 
2, 0.0053009, 0, 0, 0.508901,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.0423362);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487335,-99) , 
4, 2676.43, 1, 0, 0.522708,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486583,-99) , 
4, 4124.87, 0, 0, 0.496013,-99) , 
3, 5.37028, 0, 0, 0.503322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395461,-99) , 
2, 0.00413208, 1, 0, 0.501821,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.0284103);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573524,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492347,-99) , 
3, 5.89789, 0, 0, 0.497679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.27472,-99) , 
2, 0.00404209, 1, 0, 0.496147,-99) , 
0, 6.11403, 0, 0, 0.498818,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.0546133);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00384643, 0, 1, 0.528524,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515136,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47451,-99) , 
3, 3.05245, 0, 0, 0.506545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346997,-99) , 
2, 0.00239193, 1, 0, 0.496,-99) , 
4, 2977.86, 1, 0, 0.510385,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.0571327);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.664365,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440805,-99) , 
2, 0.00182652, 1, 0, 0.530258,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476867,-99) , 
5, 0.582024, 1, 0, 0.492675,-99) , 
0, 4.82169, 0, 0, 0.498271,-99) , 
2, 0.00498255, 0, 0, 0.50078,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.0462659);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416504,-99) , 
2, 0.00307388, 1, 0, 0.512279,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30657,-99) , 
2, 0.00184434, 1, 0, 0.48536,-99) , 
4, 4202.06, 1, 0, 0.503314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357977,-99) , 
0, 6.63948, 1, 0, 0.501824,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.0342703);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414144,-99) , 
2, 0.00330065, 1, 0, 0.521386,-99) , 
NN(
0, 
0, 
-1, 3.95306, 1, -1, 0.490039,-99) , 
0, 4.18339, 0, 0, 0.498238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380272,-99) , 
2, 0.00451265, 1, 0, 0.496945,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.0194239);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.95115, 0, 1, 0.505301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438896,-99) , 
0, 5.7288, 1, 0, 0.50328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445993,-99) , 
3, 6.69246, 1, 0, 0.499975,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.0221278);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55436,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426934,-99) , 
0, 5.80163, 1, 0, 0.49897,-99) , 
6, 3.08069, 0, 0, 0.505028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33506,-99) , 
2, 0.00423017, 1, 0, 0.503045,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.0382332);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554611,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481743,-99) , 
6, 0.0386643, 1, 0, 0.485627,-99) , 
3, 7.06143, 0, 0, 0.487831,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406171,-99) , 
2, 0.00407081, 1, 0, 0.486619,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.0379776);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629286,-99) , 
NN(
0, 
0, 
-1, 0.00254734, 1, -1, 0.491048,-99) , 
2, 0.00339906, 0, 0, 0.493311,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348751,-99) , 
2, 0.00230852, 1, 0, 0.445329,-99) , 
3, 6.0317, 1, 0, 0.486841,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.0335503);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644963,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486931,-99) , 
0, 4.68421, 0, 0, 0.492193,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.300404,-99) , 
2, 0.00404706, 1, 0, 0.490937,-99) , 
2, 0.00528393, 0, 0, 0.492763,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.0519137);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.73214, 0, 1, 0.519359,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528116,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455343,-99) , 
6, 0.370333, 1, 0, 0.482891,-99) , 
0, 4.00982, 1, 0, 0.508862,-99) , 
NN(
0, 
0, 
-1, 0.00159985, 1, -1, 0.464794,-99) , 
6, 0.0239588, 0, 0, 0.504207,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.0445043);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621204,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478292,-99) , 
4, 2269.29, 0, 0, 0.501039,-99) , 
2, 0.00338081, 0, 0, 0.50307,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388215,-99) , 
2, 0.00222102, 1, 0, 0.468814,-99) , 
3, 6.07577, 1, 0, 0.498443,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.0464244);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476083,-99) , 
4, 3120.86, 1, 0, 0.544433,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487858,-99) , 
3, 2.35678, 1, 0, 0.493867,-99) , 
0, 4.99785, 0, 0, 0.499878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356179,-99) , 
2, 0.00407894, 1, 0, 0.498013,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.0248222);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64067,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494763,-99) , 
5, 3.38602, 0, 0, 0.4989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.159281,-99) , 
2, 0.00451001, 1, 0, 0.497259,-99) , 
0, 6.63951, 0, 0, 0.499805,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.0375167);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637592,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477945,-99) , 
3, 3.11325, 0, 0, 0.514629,-99) , 
NN(
0, 
0, 
-1, 6.75579, 1, -1, 0.48961,-99) , 
6, 0.564342, 0, 0, 0.502348,-99) , 
0, 6.63849, 0, 0, 0.504706,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.0753522);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.35531, 0, 1, 0.515855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470318,-99) , 
4, 6277.54, 1, 0, 0.509826,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383266,-99) , 
2, 0.00194666, 1, 0, 0.492621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412368,-99) , 
3, 4.25395, 0, 0, 0.474628,-99) , 
0, 4.1681, 1, 0, 0.501028,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.0222208);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603077,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540412,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471036,-99) , 
6, 0.145297, 0, 0, 0.49517,-99) , 
6, 0.00883419, 1, 0, 0.498449,-99) , 
3, 7.60605, 0, 0, 0.500127,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.0403275);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481333,-99) , 
2, 0.00141489, 1, 0, 0.529764,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449012,-99) , 
3, 5.63273, 1, 0, 0.495003,-99) , 
4, 2041.38, 1, 0, 0.502953,-99) , 
NN(
0, 
0, 
-1, 0.00451239, 1, -1, 0.472566,-99) , 
0, 3.49163, 1, 0, 0.49087,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.0510183);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482343,-99) , 
0, 3.55536, 0, 0, 0.493285,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388385,-99) , 
2, 0.00215158, 1, 0, 0.464686,-99) , 
3, 6.02534, 1, 0, 0.489332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443177,-99) , 
6, 4.00184, 1, 0, 0.487102,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.0207409);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607799,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353107,-99) , 
0, 6.02326, 1, 0, 0.500213,-99) , 
3, 7.1397, 0, 0, 0.50351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.236618,-99) , 
2, 0.00431728, 1, 0, 0.501107,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.0272933);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534992,-99) , 
NN(
0, 
0, 
-1, 0.0133666, 0, -1, 0.490458,-99) , 
0, 5.22391, 0, 0, 0.494488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353943,-99) , 
3, 7.43304, 1, 0, 0.492604,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.0206403);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585847,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497041,-99) , 
6, 0.00693694, 1, 0, 0.500249,-99) , 
0, 5.91015, 0, 0, 0.503425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336533,-99) , 
2, 0.00433486, 1, 0, 0.50173,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.0291161);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661704,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496634,-99) , 
0, 3.95144, 0, 0, 0.505922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.228538,-99) , 
2, 0.00424304, 1, 0, 0.504193,-99) , 
0, 6.74177, 0, 0, 0.506654,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.0297506);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553545,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460053,-99) , 
0, 4.7683, 1, 0, 0.497586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257874,-99) , 
2, 0.00410127, 1, 0, 0.495043,-99) , 
5, 3.34258, 0, 0, 0.500384,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.045741);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.717147,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418855,-99) , 
2, 0.00250396, 1, 0, 0.507341,-99) , 
2, 0.00337562, 0, 0, 0.5118,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462597,-99) , 
0, 5.10429, 0, 0, 0.493242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331617,-99) , 
2, 0.00329593, 1, 0, 0.471799,-99) , 
3, 6.01265, 1, 0, 0.506198,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.0231469);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58133,-99) , 
NN(
0, 
0, 
-1, 5.49568, 1, -1, 0.491726,-99) , 
0, 6.1348, 0, 0, 0.49388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362539,-99) , 
2, 0.00410924, 1, 0, 0.492291,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.0338753);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607276,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482842,-99) , 
6, 0.264396, 1, 0, 0.4921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260779,-99) , 
2, 0.00409967, 1, 0, 0.490417,-99) , 
3, 7.62745, 0, 0, 0.492213,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.0668887);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00442024, 0, 1, 0.508557,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335813,-99) , 
2, 0.0015697, 1, 0, 0.471165,-99) , 
5, 0.147602, 0, 0, 0.498556,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331884,-99) , 
2, 0.00122788, 1, 0, 0.461096,-99) , 
6, 0.0727547, 0, 0, 0.491667,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.0231454);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627519,-99) , 
NN(
0, 
0, 
-1, 7.38754, 1, -1, 0.490116,-99) , 
0, 6.74714, 0, 0, 0.492087,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.0384252);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656918,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533734,-99) , 
NN(
0, 
0, 
-1, 3.7675, 1, -1, 0.484736,-99) , 
4, 1233.05, 1, 0, 0.489331,-99) , 
0, 6.74886, 0, 0, 0.491974,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.0133276);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610458,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57091,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498147,-99) , 
2, 0.00344787, 0, 0, 0.500277,-99) , 
3, 7.22682, 0, 0, 0.502078,-99) , 
2, 0.00529421, 0, 0, 0.503163,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.0217679);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639695,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494627,-99) , 
3, 6.81982, 0, 0, 0.497208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.00407387, 1, 0, 0.495181,-99) , 
2, 0.00531504, 0, 0, 0.49678,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.0734627);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409489,-99) , 
2, 0.00142817, 1, 0, 0.522413,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439989,-99) , 
2, 0.00119929, 1, 0, 0.493883,-99) , 
5, 0.288257, 0, 0, 0.51179,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553284,-99) , 
NN(
0, 
0, 
-1, 0.00402213, 1, -1, 0.476241,-99) , 
3, 2.94696, 1, 0, 0.485639,-99) , 
0, 3.4842, 1, 0, 0.501224,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.0357017);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.678541,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4901,-99) , 
0, 4.45121, 0, 0, 0.498667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.236433,-99) , 
2, 0.0040123, 1, 0, 0.497139,-99) , 
2, 0.00530496, 0, 0, 0.499328,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.0385497);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648075,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480194,-99) , 
2, 0.00167183, 1, 0, 0.545997,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420904,-99) , 
4, 1779.8, 0, 0, 0.503182,-99) , 
4, 1522.44, 1, 0, 0.509125,-99) , 
3, 7.63071, 0, 0, 0.511402,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.0248511);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552975,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469079,-99) , 
5, 0.0239586, 0, 0, 0.500877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.246773,-99) , 
2, 0.00364026, 1, 0, 0.499051,-99) , 
0, 5.56628, 0, 0, 0.502756,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.0332036);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535423,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491154,-99) , 
4, 6538.15, 0, 0, 0.496783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34861,-99) , 
2, 0.00310054, 1, 0, 0.49441,-99) , 
3, 6.36834, 0, 0, 0.498527,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.0307374);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63075,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532413,-99) , 
NN(
0, 
0, 
-1, 0.00407921, 1, -1, 0.488501,-99) , 
4, 1211.15, 1, 0, 0.49248,-99) , 
3, 7.62178, 0, 0, 0.494801,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.0328518);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46414,-99) , 
2, 0.0015459, 1, 0, 0.524137,-99) , 
NN(
0, 
0, 
-1, 0.00291013, 1, -1, 0.496139,-99) , 
4, 1778.8, 1, 0, 0.50121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395034,-99) , 
3, 6.93163, 1, 0, 0.497374,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.0360465);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466702,-99) , 
2, 0.00208369, 1, 0, 0.566122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487698,-99) , 
0, 2.97557, 0, 0, 0.534467,-99) , 
NN(
NN(
0, 
0, 
-1, 0.0032278, 0, 1, 0.505977,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39055,-99) , 
0, 6.09857, 1, 0, 0.503065,-99) , 
4, 1839.52, 1, 0, 0.509122,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.0324767);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.761714,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529541,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495474,-99) , 
4, 2170.79, 1, 0, 0.504229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.220868,-99) , 
2, 0.00413033, 1, 0, 0.502934,-99) , 
2, 0.00532323, 0, 0, 0.507136,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.0375544);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459008,-99) , 
2, 0.00156552, 1, 0, 0.543734,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492997,-99) , 
3, 3.62746, 1, 0, 0.500316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405898,-99) , 
2, 0.00371797, 1, 0, 0.49851,-99) , 
5, 0.0288538, 1, 0, 0.504616,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.0306404);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.15151, 0, 1, 0.511864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374283,-99) , 
2, 0.00410343, 1, 0, 0.510236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441089,-99) , 
5, 0.00478188, 0, 0, 0.507053,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.0259402);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574553,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478168,-99) , 
0, 4.36471, 1, 0, 0.501909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303234,-99) , 
2, 0.00408871, 1, 0, 0.500742,-99) , 
0, 6.24108, 0, 0, 0.502773,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.0344003);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556344,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491823,-99) , 
5, 1.14425, 0, 0, 0.500387,-99) , 
3, 6.39366, 0, 0, 0.50551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290303,-99) , 
2, 0.00430881, 1, 0, 0.503564,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.0655403);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479168,-99) , 
5, 1.53641, 1, 0, 0.528407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375643,-99) , 
2, 0.00356219, 1, 0, 0.522506,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523952,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485635,-99) , 
0, 3.46593, 0, 0, 0.495912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356091,-99) , 
2, 0.00180322, 1, 0, 0.48747,-99) , 
3, 4.54515, 0, 0, 0.504662,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.0409066);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648258,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327917,-99) , 
2, 0.00391046, 1, 0, 0.522079,-99) , 
NN(
0, 
0, 
-1, 0.0022749, 1, -1, 0.489728,-99) , 
3, 5.1499, 0, 0, 0.500148,-99) , 
0, 6.2695, 0, 0, 0.504728,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.0378147);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673375,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490918,-99) , 
6, 0.892982, 1, 0, 0.509227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.283722,-99) , 
2, 0.00410432, 1, 0, 0.508185,-99) , 
2, 0.00530823, 0, 0, 0.510071,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.0331656);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591742,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422477,-99) , 
0, 5.14601, 1, 0, 0.502427,-99) , 
0, 5.72225, 0, 0, 0.505321,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372162,-99) , 
2, 0.0024084, 1, 0, 0.462397,-99) , 
3, 5.98465, 1, 0, 0.499299,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.0360008);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661503,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485403,-99) , 
6, 0.989939, 0, 0, 0.4957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445914,-99) , 
0, 5.39201, 1, 0, 0.492577,-99) , 
2, 0.00530955, 0, 0, 0.494474,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.0310897);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619534,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47487,-99) , 
3, 2.47247, 0, 0, 0.507602,-99) , 
2, 0.00510471, 0, 0, 0.508729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45002,-99) , 
4, 840.706, 0, 0, 0.506476,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.029004);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659726,-99) , 
NN(
0, 
0, 
-1, 0.0040123, 1, -1, 0.487205,-99) , 
2, 0.00532479, 0, 0, 0.489205,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.0347671);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431159,-99) , 
2, 0.00214462, 1, 0, 0.524957,-99) , 
NN(
0, 
0, 
-1, 0.0026715, 1, -1, 0.493268,-99) , 
4, 1883.37, 1, 0, 0.499448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.209074,-99) , 
2, 0.00439227, 1, 0, 0.497215,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.0383231);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451412,-99) , 
2, 0.00121061, 1, 0, 0.533689,-99) , 
NN(
NN(
0, 
0, 
-1, 1520.12, 1, 1, 0.50652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413066,-99) , 
4, 841.57, 0, 0, 0.503123,-99) , 
5, 2.37566, 0, 0, 0.507933,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.0171856);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584292,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498608,-99) , 
6, 0.0117013, 1, 0, 0.501819,-99) , 
3, 7.02645, 0, 0, 0.504755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359046,-99) , 
2, 0.00423958, 1, 0, 0.503255,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.0233966);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551278,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579323,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472646,-99) , 
4, 2014.52, 0, 0, 0.494387,-99) , 
3, 7.38706, 0, 0, 0.496335,-99) , 
5, 3.33911, 0, 0, 0.501333,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.0427966);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598851,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489986,-99) , 
5, 0.700669, 0, 0, 0.506292,-99) , 
NN(
0, 
0, 
-1, 0.00147815, 1, -1, 0.477003,-99) , 
3, 3.85309, 0, 0, 0.496316,-99) , 
0, 6.28666, 0, 0, 0.499097,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.0692433);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.00746, 0, 1, 0.51981,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361492,-99) , 
2, 0.00130465, 1, 0, 0.49244,-99) , 
4, 4261.45, 1, 0, 0.510778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303551,-99) , 
2, 0.00456815, 1, 0, 0.509163,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.0349737);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583254,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485383,-99) , 
5, 0.195196, 1, 0, 0.493421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373318,-99) , 
3, 6.84993, 1, 0, 0.490701,-99) , 
3, 7.32093, 0, 0, 0.493131,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.0512365);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.20323, 0, 1, 0.513388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396207,-99) , 
2, 0.00263579, 1, 0, 0.5058,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479801,-99) , 
0, 3.88954, 0, 0, 0.498735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393083,-99) , 
2, 0.00193594, 1, 0, 0.481915,-99) , 
5, 0.16228, 0, 0, 0.498975,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.0325044);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604778,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491803,-99) , 
6, 1.94396, 0, 0, 0.498718,-99) , 
NN(
0, 
0, 
-1, 0.00235149, 1, -1, 0.478445,-99) , 
4, 2292.71, 0, 0, 0.493384,-99) , 
2, 0.00386031, 0, 0, 0.49587,-99)    );
   return;
};
 
// Clean up
inline void Read2012_BDT_1::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double Read2012_BDT_1::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
