// Class: Read2012_BDT_0
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::2012_BDT_0
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/29       [336413]
Creator        : matt
Date           : Mon Oct 26 13:50:49 2015
Host           : Darwin pc7.home 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
Dir            : /Users/matt/Scratch/lhcb/LHCbAnalysis/Bc2Dmunu
Training events: 210377
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "-1" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
NegWeightTreatment: "ignorenegweightsintraining" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
Bplus_LOGMINIPCHI2            Bplus_LOGMINIPCHI2            Bplus_LOGMINIPCHI2            Bplus_LOGMINIPCHI2                                              'F'    [-8.37824058533,11.4891910553]
Bplus_DIRA_OWNPV              Bplus_DIRA_OWNPV              Bplus_DIRA_OWNPV              Bplus_DIRA_OWNPV                                                'F'    [0.999000072479,1]
Bplus_TAU                     Bplus_TAU                     Bplus_TAU                     Bplus_TAU                                                       'F'    [6.21366143605e-06,0.0603957101703]
D0_LOGMINIPCHI2               D0_LOGMINIPCHI2               D0_LOGMINIPCHI2               D0_LOGMINIPCHI2                                                 'F'    [-9.03855419159,11.7286300659]
D0_PT                         D0_PT                         D0_PT                         D0_PT                                                           'F'    [8.25849914551,31639.8769531]
D0_ENDVERTEX_CHI2             D0_ENDVERTEX_CHI2             D0_ENDVERTEX_CHI2             D0_ENDVERTEX_CHI2                                               'F'    [1.00863435659e-10,5.99996614456]
Bplus_ENDVERTEX_CHI2          Bplus_ENDVERTEX_CHI2          Bplus_ENDVERTEX_CHI2          Bplus_ENDVERTEX_CHI2                                            'F'    [6.7228125844e-11,5.99968194962]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new 2012_BDT_0Node
   
#ifndef 2012_BDT_0Node__def
#define 2012_BDT_0Node__def
   
class 2012_BDT_0Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   2012_BDT_0Node ( 2012_BDT_0Node* left,2012_BDT_0Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~2012_BDT_0Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   2012_BDT_0Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   2012_BDT_0Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   2012_BDT_0Node*   fLeft;     // pointer to the left daughter node
   2012_BDT_0Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   2012_BDT_0Node::~2012_BDT_0Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool 2012_BDT_0Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool 2012_BDT_0Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Read2012_BDT_0 : public IClassifierReader {

 public:

   // constructor
   Read2012_BDT_0( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Read2012_BDT_0" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Bplus_LOGMINIPCHI2", "Bplus_DIRA_OWNPV", "Bplus_TAU", "D0_LOGMINIPCHI2", "D0_PT", "D0_ENDVERTEX_CHI2", "Bplus_ENDVERTEX_CHI2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Read2012_BDT_0() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<2012_BDT_0Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Read2012_BDT_0::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      2012_BDT_0Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(2012_BDT_0Node*)current->GetRight();
         else current=(2012_BDT_0Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void Read2012_BDT_0::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.391972965829812);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.00239, 1, 1, 0.657863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.130099,-99) , 
2, 0.00232567, 1, 0, 0.630156,-99) , 
NN(
0, 
0, 
-1, 0.00341801, 1, -1, 0.283739,-99) , 
0, 3.89378, 1, 0, 0.501644,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.299016);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.80485, 1, 1, 0.68815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346043,-99) , 
2, 0.00152379, 1, 0, 0.645396,-99) , 
NN(
0, 
0, 
-1, 0.00368197, 1, -1, 0.382245,-99) , 
0, 2.88026, 1, 0, 0.491494,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.21863);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.62842, 1, 1, 0.570886,-99) , 
NN(
0, 
0, 
-1, 5.33475, 1, -1, 0.357063,-99) , 
0, 4.65234, 1, 0, 0.533077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0410497,-99) , 
2, 0.00371221, 1, 0, 0.501641,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.213817);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.686802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436774,-99) , 
2, 0.00110954, 1, 0, 0.631145,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424935,-99) , 
4, 3260.93, 0, 0, 0.476858,-99) , 
0, 2.13113, 1, 0, 0.519689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0487204,-99) , 
2, 0.00352448, 1, 0, 0.488073,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.184208);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.0828, 1, 1, 0.538579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0926231,-99) , 
2, 0.00290931, 1, 0, 0.519985,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562915,-99) , 
NN(
0, 
0, 
-1, 0.00256338, 1, -1, 0.130521,-99) , 
2, 0.00187718, 1, 0, 0.261595,-99) , 
0, 4.93866, 1, 0, 0.476895,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.17455);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.55484, 1, 1, 0.581927,-99) , 
NN(
0, 
0, 
-1, 5.53252, 1, -1, 0.436832,-99) , 
0, 2.29895, 1, 0, 0.481215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0629009,-99) , 
2, 0.00392649, 1, 0, 0.46134,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.123025);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593584,-99) , 
NN(
0, 
0, 
-1, 5.36599, 1, -1, 0.475878,-99) , 
0, 1.54342, 1, 0, 0.497105,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0957931,-99) , 
2, 0.00342258, 1, 0, 0.470295,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.151531);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.16984,-99) , 
2, 0.00253681, 1, 0, 0.515702,-99) , 
NN(
0, 
0, 
-1, 0.00250776, 1, -1, 0.37744,-99) , 
0, 5.07873, 1, 0, 0.500194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0789731,-99) , 
2, 0.00380523, 1, 0, 0.479284,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.112796);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.168177,-99) , 
2, 0.00317588, 1, 0, 0.50484,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.250943,-99) , 
2, 0.00170063, 1, 0, 0.415174,-99) , 
4, 1981.13, 0, 0, 0.485905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0975418,-99) , 
2, 0.00401853, 1, 0, 0.469954,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.118236);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466881,-99) , 
4, 4883.06, 0, 0, 0.483058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387358,-99) , 
0, 5.3216, 1, 0, 0.475369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0875493,-99) , 
2, 0.00355089, 1, 0, 0.454393,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0935153);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536657,-99) , 
NN(
0, 
0, 
-1, 5.79347, 1, -1, 0.474052,-99) , 
0, 1.55924, 1, 0, 0.485173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0776889,-99) , 
2, 0.00368411, 1, 0, 0.465782,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0712813);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436296,-99) , 
3, 6.32284, 1, 0, 0.499534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369052,-99) , 
0, 5.58478, 1, 0, 0.492068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0608326,-99) , 
2, 0.00376665, 1, 0, 0.473045,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.105509);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.206163,-99) , 
2, 0.00259293, 1, 0, 0.495827,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296458,-99) , 
2, 0.00195442, 1, 0, 0.44366,-99) , 
0, 4.9372, 1, 0, 0.489459,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0962186,-99) , 
2, 0.00347939, 1, 0, 0.468334,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0914875);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473238,-99) , 
4, 7415.11, 0, 0, 0.477437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371177,-99) , 
0, 5.97756, 1, 0, 0.474216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.147029,-99) , 
2, 0.00363932, 1, 0, 0.458105,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0670365);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459717,-99) , 
3, 5.29365, 1, 0, 0.49189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.241222,-99) , 
0, 6.16422, 1, 0, 0.486367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0732405,-99) , 
2, 0.00409712, 1, 0, 0.472724,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0843683);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517876,-99) , 
NN(
0, 
0, 
-1, 2.24782, 1, -1, 0.471869,-99) , 
0, 1.324, 1, 0, 0.478763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.121133,-99) , 
2, 0.00371212, 1, 0, 0.463037,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0871819);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.228204,-99) , 
2, 0.00303969, 1, 0, 0.504506,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.226468,-99) , 
2, 0.00207417, 1, 0, 0.442835,-99) , 
4, 2002.97, 0, 0, 0.491374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.116481,-99) , 
2, 0.00403363, 1, 0, 0.478489,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0768055);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.00402402, 1, -1, 0.461673,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0637635);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492318,-99) , 
0, 4.35367, 1, 0, 0.512032,-99) , 
NN(
0, 
0, 
-1, 0.00213419, 1, -1, 0.4854,-99) , 
0, 3.86077, 0, 0, 0.494576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.120664,-99) , 
2, 0.00371204, 1, 0, 0.479538,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.048429);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.00371211, 1, -1, 0.475804,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0918969);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377268,-99) , 
0, 5.72657, 1, 0, 0.518218,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310036,-99) , 
2, 0.00196908, 1, 0, 0.459245,-99) , 
4, 1777.84, 0, 0, 0.508161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.172725,-99) , 
2, 0.00391756, 1, 0, 0.495603,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0603498);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467885,-99) , 
3, 3.37332, 0, 0, 0.50058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428464,-99) , 
4, 1032.15, 0, 0, 0.496368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.120006,-99) , 
2, 0.00397724, 1, 0, 0.484189,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0567998);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536583,-99) , 
NN(
0, 
0, 
-1, 2178.5, 0, -1, 0.487611,-99) , 
5, 0.0135605, 1, 0, 0.492118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.139575,-99) , 
2, 0.00371214, 1, 0, 0.478097,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0690189);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5386,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489735,-99) , 
0, 5.16432, 0, 0, 0.495097,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.337819,-99) , 
2, 0.00140078, 1, 0, 0.46103,-99) , 
6, 2.27055, 1, 0, 0.489714,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.180618,-99) , 
2, 0.00373709, 1, 0, 0.477573,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0889301);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.266576,-99) , 
2, 0.00268486, 1, 0, 0.509489,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501655,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.247647,-99) , 
2, 0.00240322, 1, 0, 0.470115,-99) , 
4, 2199.64, 0, 0, 0.499576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.135687,-99) , 
2, 0.00371214, 1, 0, 0.485841,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0790951);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530283,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47102,-99) , 
3, 5.98037, 0, 0, 0.478005,-99) , 
4, 7669.36, 0, 0, 0.481972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.145363,-99) , 
2, 0.00366828, 1, 0, 0.469127,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0634622);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468626,-99) , 
4, 1987, 0, 0, 0.49683,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.198195,-99) , 
2, 0.00267691, 1, 0, 0.454306,-99) , 
0, 4.54596, 1, 0, 0.489201,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.162031,-99) , 
2, 0.00371215, 1, 0, 0.476826,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0541684);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499376,-99) , 
4, 3120.34, 1, 0, 0.529585,-99) , 
NN(
0, 
0, 
-1, 0.00241417, 1, -1, 0.487224,-99) , 
0, 4.62612, 0, 0, 0.495317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.196926,-99) , 
2, 0.00371211, 1, 0, 0.483941,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0681553);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472806,-99) , 
0, 5.04909, 1, 0, 0.50784,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.262167,-99) , 
2, 0.0015609, 1, 0, 0.449091,-99) , 
6, 2.25142, 1, 0, 0.498511,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.182596,-99) , 
2, 0.00371244, 1, 0, 0.486746,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0913126);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00250535, 1, -1, 0.489165,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339905,-99) , 
2, 0.00162005, 1, 0, 0.453319,-99) , 
0, 4.50429, 1, 0, 0.481868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0991144,-99) , 
2, 0.00456952, 1, 0, 0.474743,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0513518);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451352,-99) , 
3, 6.63986, 1, 0, 0.506698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467274,-99) , 
6, 2.95468, 1, 0, 0.502653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.140902,-99) , 
2, 0.00371211, 1, 0, 0.490711,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0667434);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485512,-99) , 
5, 0.70023, 1, 0, 0.500373,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320283,-99) , 
2, 0.00148318, 1, 0, 0.459168,-99) , 
5, 0.0440748, 0, 0, 0.494367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.226237,-99) , 
2, 0.00348018, 1, 0, 0.482673,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.076633);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.274165,-99) , 
2, 0.00241436, 1, 0, 0.50061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436774,-99) , 
5, 2.03774, 0, 0, 0.458938,-99) , 
0, 4.38752, 1, 0, 0.4918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.122984,-99) , 
2, 0.00366803, 1, 0, 0.47951,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0573398);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47154,-99) , 
4, 3434.96, 1, 0, 0.489048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407093,-99) , 
0, 5.60542, 1, 0, 0.485097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.216836,-99) , 
2, 0.00371216, 1, 0, 0.475788,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0965889);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340607,-99) , 
2, 0.00185439, 1, 0, 0.509025,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473014,-99) , 
3, 6.29967, 0, 0, 0.478952,-99) , 
6, 0.171151, 1, 0, 0.488032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.108602,-99) , 
2, 0.00402421, 1, 0, 0.478907,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0365848);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471426,-99) , 
6, 0.0491427, 0, 0, 0.497542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44342,-99) , 
4, 1043.03, 0, 0, 0.494501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.263577,-99) , 
2, 0.00355114, 1, 0, 0.485334,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0487397);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489172,-99) , 
3, 6.78936, 0, 0, 0.491978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421742,-99) , 
0, 6.04783, 1, 0, 0.490196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.162415,-99) , 
2, 0.00371214, 1, 0, 0.480007,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0478493);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49916,-99) , 
4, 6578.55, 0, 0, 0.502663,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352862,-99) , 
2, 0.00142003, 1, 0, 0.478243,-99) , 
6, 2.26535, 1, 0, 0.498789,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.220001,-99) , 
2, 0.00365956, 1, 0, 0.489275,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0396735);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465206,-99) , 
6, 2.1764, 1, 0, 0.498751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437071,-99) , 
3, 6.54913, 1, 0, 0.494253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.151146,-99) , 
2, 0.0045556, 1, 0, 0.488554,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0361728);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54379,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495815,-99) , 
4, 1258.36, 1, 0, 0.499292,-99) , 
6, 0.0100827, 1, 0, 0.502793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.165555,-99) , 
2, 0.00391709, 1, 0, 0.494153,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0664822);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.218021,-99) , 
2, 0.00272812, 1, 0, 0.507899,-99) , 
NN(
0, 
0, 
-1, 0.229334, 1, -1, 0.484747,-99) , 
5, 0.370834, 0, 0, 0.498313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.215705,-99) , 
2, 0.00343843, 1, 0, 0.487085,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0464051);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483947,-99) , 
4, 2062.34, 0, 0, 0.507248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464377,-99) , 
5, 3.27027, 1, 0, 0.503607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.254317,-99) , 
2, 0.0038216, 1, 0, 0.496066,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0468851);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492209,-99) , 
0, 3.83696, 0, 0, 0.502209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459558,-99) , 
4, 7126.16, 1, 0, 0.498466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.25135,-99) , 
2, 0.00355614, 1, 0, 0.489455,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0467009);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479062,-99) , 
3, 5.95017, 1, 0, 0.509169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459883,-99) , 
0, 5.3092, 1, 0, 0.505672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306663,-99) , 
2, 0.00347967, 1, 0, 0.497589,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0556056);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450918,-99) , 
2, 0.00185061, 1, 0, 0.536,-99) , 
NN(
0, 
0, 
-1, 3.53745, 1, -1, 0.487184,-99) , 
4, 1396.42, 1, 0, 0.492903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.183143,-99) , 
2, 0.00371209, 1, 0, 0.484065,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0533913);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493364,-99) , 
0, 4.76089, 0, 0, 0.510439,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240811,-99) , 
2, 0.00188119, 1, 0, 0.487309,-99) , 
3, 4.70752, 0, 0, 0.497423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.284173,-99) , 
2, 0.00329355, 1, 0, 0.487572,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0311636);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596637,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498673,-99) , 
0, 5.82159, 0, 0, 0.501402,-99) , 
3, 6.86137, 0, 0, 0.506119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257805,-99) , 
2, 0.00371211, 1, 0, 0.49865,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0488978);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549392,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480579,-99) , 
4, 2986.2, 0, 0, 0.499727,-99) , 
4, 1251.32, 1, 0, 0.504447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.237967,-99) , 
2, 0.00368218, 1, 0, 0.496456,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0304452);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496951,-99) , 
0, 4.81502, 0, 0, 0.502859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346022,-99) , 
2, 0.00371211, 1, 0, 0.500082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0998481,-99) , 
2, 0.00484082, 1, 0, 0.495347,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0303464);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1302.07, 1, 1, 0.506384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447931,-99) , 
4, 901.165, 0, 0, 0.503907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257423,-99) , 
2, 0.00371211, 1, 0, 0.496701,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0569627);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310108,-99) , 
2, 0.00247543, 1, 0, 0.506121,-99) , 
NN(
0, 
0, 
-1, 0.00332481, 1, -1, 0.462437,-99) , 
0, 4.574, 1, 0, 0.498217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.277863,-99) , 
2, 0.00409609, 1, 0, 0.493016,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0641808);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368427,-99) , 
2, 0.00232032, 1, 0, 0.532274,-99) , 
NN(
0, 
0, 
-1, 0.00282691, 1, -1, 0.489253,-99) , 
0, 5.03594, 0, 0, 0.49459,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0950818,-99) , 
2, 0.00415745, 1, 0, 0.487783,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0636852);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467216,-99) , 
4, 3707.71, 1, 0, 0.529808,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486875,-99) , 
5, 1.89952, 0, 0, 0.495168,-99) , 
3, 5.95479, 0, 0, 0.500413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.222946,-99) , 
2, 0.0033638, 1, 0, 0.490082,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0706439);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481245,-99) , 
4, 6137.76, 1, 0, 0.518523,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373321,-99) , 
2, 0.00115013, 1, 0, 0.469683,-99) , 
6, 2.25136, 1, 0, 0.511005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364693,-99) , 
2, 0.00397743, 1, 0, 0.507112,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0277485);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497336,-99) , 
3, 6.86009, 0, 0, 0.501689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376021,-99) , 
0, 6.18721, 1, 0, 0.499065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.228489,-99) , 
2, 0.00426724, 1, 0, 0.494259,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0334127);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481111,-99) , 
6, 0.214874, 0, 0, 0.499764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425496,-99) , 
0, 6.1604, 1, 0, 0.498071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321724,-99) , 
2, 0.00421002, 1, 0, 0.494317,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0484479);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338288,-99) , 
2, 0.00257455, 1, 0, 0.498795,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316338,-99) , 
2, 0.00251688, 1, 0, 0.465726,-99) , 
0, 4.56706, 1, 0, 0.492666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.20758,-99) , 
2, 0.004707, 1, 0, 0.48899,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0472473);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51712,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480994,-99) , 
5, 0.927105, 1, 0, 0.503978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343018,-99) , 
0, 6.19216, 1, 0, 0.50085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.270935,-99) , 
2, 0.0045821, 1, 0, 0.497437,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.043931);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497565,-99) , 
4, 2465.08, 1, 0, 0.513911,-99) , 
NN(
0, 
0, 
-1, 0.00195441, 1, -1, 0.485275,-99) , 
3, 4.57454, 0, 0, 0.499058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.253649,-99) , 
2, 0.00371199, 1, 0, 0.492616,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0247492);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539875,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447234,-99) , 
6, 2.66875, 1, 0, 0.499836,-99) , 
6, 3.89163, 0, 0, 0.502318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339752,-99) , 
2, 0.00400584, 1, 0, 0.498566,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0746502);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264158,-99) , 
2, 0.00228832, 1, 0, 0.51722,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480759,-99) , 
4, 5130.68, 0, 0, 0.490894,-99) , 
5, 1.15442, 0, 0, 0.499593,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289808,-99) , 
2, 0.00371205, 1, 0, 0.493884,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0213572);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500881,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447637,-99) , 
3, 2.13104, 0, 0, 0.496734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391126,-99) , 
0, 6.1972, 1, 0, 0.494449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.163149,-99) , 
2, 0.00484396, 1, 0, 0.490895,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0424299);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484678,-99) , 
3, 5.49806, 0, 0, 0.492208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387031,-99) , 
2, 0.0038423, 1, 0, 0.490607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357432,-99) , 
0, 6.07467, 1, 0, 0.486234,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0537342);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335556,-99) , 
2, 0.00181634, 1, 0, 0.53497,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.281501,-99) , 
2, 0.00318836, 1, 0, 0.495091,-99) , 
5, 0.0556484, 1, 0, 0.502165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.170005,-99) , 
2, 0.00427012, 1, 0, 0.497206,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0382894);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491804,-99) , 
0, 5.20038, 0, 0, 0.496357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.244937,-99) , 
2, 0.00159415, 1, 0, 0.443326,-99) , 
5, 2.93112, 1, 0, 0.490795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286234,-99) , 
2, 0.00481005, 1, 0, 0.488301,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.070141);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397285,-99) , 
2, 0.0018858, 1, 0, 0.517125,-99) , 
NN(
0, 
0, 
-1, 0.00324584, 1, -1, 0.482443,-99) , 
6, 0.996601, 0, 0, 0.495497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.155994,-99) , 
2, 0.0048434, 1, 0, 0.492147,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0384382);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498003,-99) , 
4, 2884.17, 1, 0, 0.509864,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.294847,-99) , 
2, 0.00167029, 1, 0, 0.460857,-99) , 
5, 2.83601, 1, 0, 0.504549,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.258905,-99) , 
2, 0.00484844, 1, 0, 0.501841,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0673885);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606182,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456753,-99) , 
0, 4.32325, 1, 0, 0.502478,-99) , 
0, 5.71921, 0, 0, 0.510571,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467915,-99) , 
5, 0.207986, 1, 0, 0.492024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321908,-99) , 
2, 0.00209694, 1, 0, 0.46638,-99) , 
6, 1.39663, 1, 0, 0.49867,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0445614);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515561,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341177,-99) , 
2, 0.00320837, 1, 0, 0.510995,-99) , 
NN(
0, 
0, 
-1, 0.00259465, 1, -1, 0.483609,-99) , 
5, 0.844463, 1, 0, 0.500317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.212868,-99) , 
2, 0.00424613, 1, 0, 0.495942,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0339802);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478388,-99) , 
4, 5566.06, 1, 0, 0.504474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390145,-99) , 
2, 0.00479332, 1, 0, 0.50295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448601,-99) , 
5, 3.10107, 1, 0, 0.497984,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0564899);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570871,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4805,-99) , 
6, 0.120054, 1, 0, 0.489656,-99) , 
0, 5.70132, 0, 0, 0.493303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311844,-99) , 
2, 0.00316628, 1, 0, 0.485233,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0408381);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 6.3844, 0, 1, 0.525654,-99) , 
NN(
0, 
0, 
-1, 1655.88, 0, -1, 0.488699,-99) , 
0, 3.92089, 0, 0, 0.50079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295825,-99) , 
2, 0.00374629, 1, 0, 0.495985,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0430222);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433141,-99) , 
2, 0.00209062, 1, 0, 0.520783,-99) , 
NN(
0, 
0, 
-1, 5.05873, 1, -1, 0.487429,-99) , 
4, 1370.9, 1, 0, 0.491197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295922,-99) , 
2, 0.00374685, 1, 0, 0.486488,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0531716);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461674,-99) , 
5, 2.63651, 1, 0, 0.508586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.300875,-99) , 
2, 0.00322249, 1, 0, 0.504699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412295,-99) , 
0, 5.37317, 1, 0, 0.497309,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0713332);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454962,-99) , 
2, 0.00090885, 1, 0, 0.521467,-99) , 
NN(
0, 
0, 
-1, 5.88933, 1, -1, 0.484866,-99) , 
5, 1.53122, 0, 0, 0.494685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.235037,-99) , 
2, 0.00384274, 1, 0, 0.489544,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0416765);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584063,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512844,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380316,-99) , 
2, 0.00321624, 1, 0, 0.510314,-99) , 
3, 6.96015, 0, 0, 0.513429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37181,-99) , 
0, 6.16419, 1, 0, 0.509553,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.014338);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00356574, 0, 1, 0.502003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459507,-99) , 
0, 5.32234, 1, 0, 0.498746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29066,-99) , 
0, 6.72032, 1, 0, 0.49649,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0203222);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399882,-99) , 
2, 0.00371211, 1, 0, 0.501424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458119,-99) , 
3, 2.14449, 0, 0, 0.497989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.21843,-99) , 
2, 0.00479931, 1, 0, 0.495292,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0247139);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496433,-99) , 
0, 5.82221, 0, 0, 0.499823,-99) , 
NN(
0, 
0, 
-1, 0.00173401, 1, -1, 0.461253,-99) , 
5, 2.80101, 1, 0, 0.495478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286177,-99) , 
2, 0.00480302, 1, 0, 0.49328,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0236551);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491758,-99) , 
4, 2530.2, 1, 0, 0.497525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422234,-99) , 
0, 6.18736, 1, 0, 0.495959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347643,-99) , 
2, 0.00448368, 1, 0, 0.493876,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0595603);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.28579, 0, 1, 0.520031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370916,-99) , 
2, 0.00173962, 1, 0, 0.503031,-99) , 
NN(
0, 
0, 
-1, 0.00484357, 1, -1, 0.475108,-99) , 
0, 3.75736, 1, 0, 0.493006,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0209728);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564408,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.277777,-99) , 
2, 0.00301773, 1, 0, 0.49475,-99) , 
3, 6.90187, 0, 0, 0.498165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.300062,-99) , 
2, 0.00484371, 1, 0, 0.496113,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0233567);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549559,-99) , 
NN(
0, 
0, 
-1, 0.00334823, 1, -1, 0.491833,-99) , 
0, 5.82166, 0, 0, 0.494554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378102,-99) , 
2, 0.00451614, 1, 0, 0.492931,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0568193);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372291,-99) , 
2, 0.00332475, 1, 0, 0.515435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423111,-99) , 
0, 6.18107, 1, 0, 0.510811,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480976,-99) , 
4, 4734.52, 0, 0, 0.492251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293193,-99) , 
2, 0.00199283, 1, 0, 0.483343,-99) , 
3, 4.48285, 0, 0, 0.497544,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.04666);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488198,-99) , 
4, 4270.43, 1, 0, 0.50204,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356235,-99) , 
2, 0.00163003, 1, 0, 0.463437,-99) , 
4, 1690.13, 0, 0, 0.496208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361157,-99) , 
2, 0.00347941, 1, 0, 0.492074,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.05534);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493238,-99) , 
0, 4.85129, 0, 0, 0.499736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363739,-99) , 
2, 0.00367749, 1, 0, 0.49634,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482912,-99) , 
0, 2.84585, 0, 0, 0.510608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320549,-99) , 
2, 0.00163179, 1, 0, 0.462971,-99) , 
6, 0.134239, 0, 0, 0.487856,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0505071);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320485,-99) , 
2, 0.00299955, 1, 0, 0.50553,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455961,-99) , 
0, 3.81563, 0, 0, 0.480652,-99) , 
4, 2776.96, 0, 0, 0.496152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286539,-99) , 
2, 0.00484809, 1, 0, 0.494186,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0487621);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.58836, 0, 1, 0.511221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43159,-99) , 
2, 0.00242777, 1, 0, 0.502663,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477682,-99) , 
0, 4.03989, 0, 0, 0.491979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342917,-99) , 
2, 0.00257998, 1, 0, 0.479926,-99) , 
6, 0.321097, 0, 0, 0.493879,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.029915);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576126,-99) , 
NN(
0, 
0, 
-1, 1031.87, 0, -1, 0.490969,-99) , 
3, 6.94646, 0, 0, 0.494386,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33567,-99) , 
2, 0.00377144, 1, 0, 0.491026,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0408475);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580362,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488084,-99) , 
6, 0.914441, 1, 0, 0.505434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329543,-99) , 
2, 0.00342416, 1, 0, 0.502477,-99) , 
3, 6.94672, 0, 0, 0.506805,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0355884);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493903,-99) , 
6, 1.22928, 0, 0, 0.509342,-99) , 
NN(
0, 
0, 
-1, 0.00249978, 1, -1, 0.484155,-99) , 
4, 2961.74, 1, 0, 0.495075,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370978,-99) , 
2, 0.00483635, 1, 0, 0.493813,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0436249);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401766,-99) , 
2, 0.00317533, 1, 0, 0.508308,-99) , 
NN(
0, 
0, 
-1, 0.00205573, 1, -1, 0.468566,-99) , 
5, 1.88554, 1, 0, 0.500504,-99) , 
NN(
0, 
0, 
-1, 0.00178575, 1, -1, 0.459701,-99) , 
6, 0.024046, 0, 0, 0.496209,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0188365);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557776,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464642,-99) , 
0, 5.05301, 1, 0, 0.498568,-99) , 
3, 6.98549, 0, 0, 0.500937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334892,-99) , 
2, 0.00432246, 1, 0, 0.498691,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0472422);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593664,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388185,-99) , 
2, 0.00238643, 1, 0, 0.497594,-99) , 
3, 5.97178, 0, 0, 0.513834,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508721,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477816,-99) , 
0, 3.0798, 1, 0, 0.49371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336128,-99) , 
2, 0.0030886, 1, 0, 0.488738,-99) , 
4, 2575.72, 1, 0, 0.497662,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0286296);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49206,-99) , 
0, 5.82164, 0, 0, 0.494842,-99) , 
2, 0.00401359, 0, 0, 0.497115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435379,-99) , 
3, 6.96111, 1, 0, 0.494595,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0342573);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447752,-99) , 
6, 2.33839, 1, 0, 0.516844,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355469,-99) , 
2, 0.00227423, 1, 0, 0.49644,-99) , 
0, 3.96977, 0, 0, 0.502919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345095,-99) , 
2, 0.00483954, 1, 0, 0.501384,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0216669);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59661,-99) , 
NN(
0, 
0, 
-1, 6.69772, 1, -1, 0.493151,-99) , 
3, 7.21938, 0, 0, 0.496064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329563,-99) , 
2, 0.00482459, 1, 0, 0.49456,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0356658);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639151,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490346,-99) , 
0, 3.96974, 0, 0, 0.50042,-99) , 
2, 0.00395018, 0, 0, 0.502517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.168455,-99) , 
2, 0.0048739, 1, 0, 0.500123,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0247064);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498885,-99) , 
2, 0.00427928, 0, 0, 0.500599,-99) , 
NN(
0, 
0, 
-1, 2.4648, 1, -1, 0.456084,-99) , 
3, 3.00987, 0, 0, 0.493067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359283,-99) , 
3, 7.31232, 1, 0, 0.490411,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0455033);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598151,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443792,-99) , 
2, 0.00174299, 1, 0, 0.533183,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32103,-99) , 
2, 0.00297355, 1, 0, 0.499157,-99) , 
6, 1.86505, 0, 0, 0.506561,-99) , 
2, 0.00399169, 0, 0, 0.509102,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.0260331);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495695,-99) , 
2, 0.00354661, 0, 0, 0.49916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412264,-99) , 
4, 844.041, 0, 0, 0.4959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362278,-99) , 
0, 6.34691, 1, 0, 0.493305,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0630042);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.79476, 0, 1, 0.519495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350145,-99) , 
2, 0.00211368, 1, 0, 0.509597,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47435,-99) , 
0, 5.71934, 0, 0, 0.488849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370425,-99) , 
2, 0.00322741, 1, 0, 0.475694,-99) , 
0, 4.07214, 1, 0, 0.500036,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.0213882);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534563,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426057,-99) , 
0, 6.04607, 1, 0, 0.498099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441465,-99) , 
4, 1790.54, 0, 0, 0.493014,-99) , 
4, 1260.58, 1, 0, 0.497127,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.0379612);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480633,-99) , 
0, 2.90805, 0, 0, 0.49842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390255,-99) , 
0, 6.1811, 1, 0, 0.496443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369345,-99) , 
2, 0.00424694, 1, 0, 0.494591,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.0635558);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449916,-99) , 
2, 0.00213994, 1, 0, 0.540027,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40978,-99) , 
2, 0.0016534, 1, 0, 0.49991,-99) , 
NN(
0, 
0, 
-1, 0.0024436, 1, -1, 0.47074,-99) , 
0, 3.10867, 1, 0, 0.486844,-99) , 
0, 5.18432, 0, 0, 0.493106,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.0577355);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480704,-99) , 
4, 2945.35, 1, 0, 0.544839,-99) , 
NN(
0, 
0, 
-1, 0.00282859, 1, -1, 0.481484,-99) , 
3, 6.04818, 0, 0, 0.490995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.230713,-99) , 
2, 0.00414325, 1, 0, 0.48772,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.0397939);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493447,-99) , 
0, 4.0291, 0, 0, 0.505945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412115,-99) , 
2, 0.00294165, 1, 0, 0.501927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412354,-99) , 
0, 6.38939, 1, 0, 0.500223,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.0626314);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431552,-99) , 
0, 5.62738, 1, 0, 0.507545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.299422,-99) , 
2, 0.00458766, 1, 0, 0.505436,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442472,-99) , 
3, 4.3432, 0, 0, 0.492812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348472,-99) , 
2, 0.00170063, 1, 0, 0.459161,-99) , 
6, 0.132518, 0, 0, 0.493984,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0297471);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536956,-99) , 
NN(
0, 
0, 
-1, 4.87282, 1, -1, 0.489177,-99) , 
3, 6.4175, 0, 0, 0.493602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394288,-99) , 
0, 6.38939, 1, 0, 0.491856,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.0238166);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557466,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50274,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466563,-99) , 
0, 4.63565, 1, 0, 0.499346,-99) , 
0, 5.36405, 0, 0, 0.503697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405787,-99) , 
2, 0.00346319, 1, 0, 0.500917,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.0290964);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593004,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474954,-99) , 
0, 2.83548, 0, 0, 0.489281,-99) , 
0, 6.0098, 0, 0, 0.49216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383403,-99) , 
0, 6.58264, 1, 0, 0.490777,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.0471033);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521838,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531156,-99) , 
NN(
0, 
0, 
-1, 1971.24, 0, -1, 0.476996,-99) , 
4, 1151.79, 1, 0, 0.481757,-99) , 
0, 0.827572, 1, 0, 0.48573,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.0424128);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626806,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4769,-99) , 
4, 2740.1, 0, 0, 0.49952,-99) , 
2, 0.00355079, 0, 0, 0.501627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445995,-99) , 
0, 5.31907, 1, 0, 0.496986,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.0418024);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474912,-99) , 
2, 0.00122649, 1, 0, 0.534613,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493605,-99) , 
5, 0.0165257, 1, 0, 0.498767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.247947,-99) , 
2, 0.00479571, 1, 0, 0.496837,-99) , 
6, 0.068186, 1, 0, 0.504353,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.0528604);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448645,-99) , 
2, 0.00128482, 1, 0, 0.521648,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551404,-99) , 
NN(
0, 
0, 
-1, 5.35522, 1, -1, 0.486605,-99) , 
0, 5.97352, 0, 0, 0.489429,-99) , 
5, 1.66628, 0, 0, 0.497308,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.0145293);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637803,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498507,-99) , 
0, 6.13605, 0, 0, 0.500755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313685,-99) , 
2, 0.00457854, 1, 0, 0.499553,-99) , 
3, 7.6163, 0, 0, 0.502077,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.0640895);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593934,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.174772,-99) , 
2, 0.00251938, 1, 0, 0.510968,-99) , 
3, 6.35189, 0, 0, 0.520861,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492411,-99) , 
3, 5.3044, 0, 0, 0.505897,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334206,-99) , 
2, 0.0027892, 1, 0, 0.496105,-99) , 
6, 0.379267, 1, 0, 0.506823,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.0312077);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0742836, 1, 1, 0.513773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48419,-99) , 
0, 1.45185, 0, 0, 0.509009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39885,-99) , 
0, 6.38944, 1, 0, 0.507113,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.0346584);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.66041,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486793,-99) , 
3, 5.01716, 1, 0, 0.503587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346025,-99) , 
0, 6.38669, 1, 0, 0.501532,-99) , 
3, 7.59213, 0, 0, 0.504703,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.0436958);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.48771, 0, 1, 0.512495,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.28538,-99) , 
2, 0.0019695, 1, 0, 0.475623,-99) , 
6, 0.275182, 0, 0, 0.499425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359125,-99) , 
2, 0.00368176, 1, 0, 0.49652,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.027588);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622222,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498229,-99) , 
4, 2360.97, 1, 0, 0.506792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459028,-99) , 
4, 1167.99, 0, 0, 0.503291,-99) , 
3, 7.60419, 0, 0, 0.505462,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.0522632);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.625379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476529,-99) , 
0, 3.61129, 0, 0, 0.547818,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38554,-99) , 
2, 0.00263026, 1, 0, 0.510918,-99) , 
NN(
0, 
0, 
-1, 0.00261285, 1, -1, 0.48471,-99) , 
5, 0.51597, 0, 0, 0.498292,-99) , 
4, 1299.08, 1, 0, 0.503745,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.0430307);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499109,-99) , 
4, 2927.8, 1, 0, 0.513825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446702,-99) , 
5, 0.00727403, 0, 0, 0.510101,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496315,-99) , 
0, 2.62446, 0, 0, 0.508546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328924,-99) , 
2, 0.00107402, 1, 0, 0.476902,-99) , 
3, 3.16287, 0, 0, 0.503727,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.0372665);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695519,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470179,-99) , 
5, 1.87672, 1, 0, 0.495764,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349539,-99) , 
2, 0.00219451, 1, 0, 0.448145,-99) , 
0, 4.95616, 1, 0, 0.490173,-99) , 
2, 0.00527961, 0, 0, 0.492978,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.0260612);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.90402, 0, 1, 0.509932,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464161,-99) , 
5, 0.00818121, 0, 0, 0.50709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.301351,-99) , 
2, 0.00478434, 1, 0, 0.505455,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.0395353);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658731,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4873,-99) , 
6, 0.662022, 0, 0, 0.501359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441629,-99) , 
0, 5.31977, 1, 0, 0.496878,-99) , 
2, 0.00526737, 0, 0, 0.498789,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.0640251);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.07158, 0, 1, 0.535398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393963,-99) , 
2, 0.00201939, 1, 0, 0.51383,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477925,-99) , 
3, 5.09234, 0, 0, 0.490145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396901,-99) , 
2, 0.00292166, 1, 0, 0.485389,-99) , 
5, 0.229602, 1, 0, 0.495278,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.0143637);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586766,-99) , 
NN(
NN(
0, 
0, 
-1, 5.71943, 0, 1, 0.50279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45384,-99) , 
6, 0.00738106, 0, 0, 0.499927,-99) , 
2, 0.00401188, 0, 0, 0.501905,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.0372896);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 5.26025, 0, 1, 0.555829,-99) , 
NN(
0, 
0, 
-1, 4.86433, 1, -1, 0.485824,-99) , 
3, 6.41443, 0, 0, 0.49332,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.0221833);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585768,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495107,-99) , 
2, 0.00396488, 0, 0, 0.496402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437401,-99) , 
5, 3.8941, 1, 0, 0.493449,-99) , 
0, 6.28375, 0, 0, 0.496109,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.015932);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610446,-99) , 
NN(
0, 
0, 
-1, 959.264, 0, -1, 0.493737,-99) , 
0, 6.68149, 0, 0, 0.495645,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.0247963);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645745,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495594,-99) , 
3, 6.98544, 0, 0, 0.498602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.198954,-99) , 
2, 0.00420548, 1, 0, 0.496625,-99) , 
0, 6.48273, 0, 0, 0.500289,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.025635);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587615,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493644,-99) , 
0, 3.48251, 1, 0, 0.505069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34409,-99) , 
2, 0.00412064, 1, 0, 0.503549,-99) , 
3, 7.62657, 0, 0, 0.504891,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0424335);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480315,-99) , 
6, 0.0964185, 0, 0, 0.508831,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.283589,-99) , 
2, 0.00225356, 1, 0, 0.485957,-99) , 
5, 1.01902, 1, 0, 0.501018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33957,-99) , 
2, 0.00480948, 1, 0, 0.499675,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.0141066);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641704,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499481,-99) , 
0, 5.91836, 0, 0, 0.50222,-99) , 
2, 0.00358355, 0, 0, 0.504633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380548,-99) , 
2, 0.00428778, 1, 0, 0.503069,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.0202229);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570276,-99) , 
NN(
NN(
0, 
0, 
-1, 5.14775, 0, 1, 0.504771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407534,-99) , 
0, 6.1048, 1, 0, 0.503031,-99) , 
3, 6.85547, 0, 0, 0.506996,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.0296653);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589108,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490621,-99) , 
6, 0.0136486, 1, 0, 0.494036,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.276152,-99) , 
2, 0.00389704, 1, 0, 0.491879,-99) , 
3, 7.50084, 0, 0, 0.493888,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.035018);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609344,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477986,-99) , 
3, 5.42018, 1, 0, 0.502364,-99) , 
3, 7.22149, 0, 0, 0.505468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.216088,-99) , 
2, 0.00470885, 1, 0, 0.503309,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.0434057);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639081,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427087,-99) , 
4, 867.784, 0, 0, 0.508263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42503,-99) , 
0, 5.52328, 1, 0, 0.505833,-99) , 
0, 6.00921, 0, 0, 0.512175,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.0266435);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54713,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491698,-99) , 
6, 2.90694, 0, 0, 0.495578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334081,-99) , 
2, 0.00374249, 1, 0, 0.493947,-99) , 
0, 6.01285, 0, 0, 0.496094,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.0257425);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616169,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503897,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470973,-99) , 
3, 5.83301, 1, 0, 0.49846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450698,-99) , 
4, 7434.64, 1, 0, 0.494927,-99) , 
2, 0.00453144, 0, 0, 0.496969,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.0397358);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571526,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483857,-99) , 
0, 3.28145, 0, 0, 0.497082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371842,-99) , 
2, 0.00327658, 1, 0, 0.494873,-99) , 
3, 6.89699, 0, 0, 0.499124,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.0380405);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454326,-99) , 
2, 0.00231535, 1, 0, 0.531111,-99) , 
NN(
0, 
0, 
-1, 6.20121, 1, -1, 0.491627,-99) , 
0, 4.70711, 0, 0, 0.497833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346869,-99) , 
0, 6.28389, 1, 0, 0.494988,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.0445632);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573435,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410181,-99) , 
2, 0.00320859, 1, 0, 0.513052,-99) , 
0, 6.31109, 0, 0, 0.514683,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512939,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383125,-99) , 
2, 0.00159632, 1, 0, 0.479997,-99) , 
6, 2.24046, 1, 0, 0.509218,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.0600786);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429561,-99) , 
2, 0.00217757, 1, 0, 0.51916,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481654,-99) , 
4, 4831.44, 0, 0, 0.489895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.272191,-99) , 
2, 0.00289547, 1, 0, 0.486199,-99) , 
3, 6.0533, 0, 0, 0.491188,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.0157191);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382731,-99) , 
2, 0.00321048, 1, 0, 0.500292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44166,-99) , 
3, 6.62746, 1, 0, 0.497209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41335,-99) , 
0, 6.18734, 1, 0, 0.495259,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.0391184);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545159,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488424,-99) , 
0, 2.13676, 1, 0, 0.497146,-99) , 
5, 2.0489, 0, 0, 0.501545,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.245978,-99) , 
2, 0.00179961, 1, 0, 0.463087,-99) , 
5, 2.91731, 1, 0, 0.497641,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.0459677);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420384,-99) , 
2, 0.0014918, 1, 0, 0.525987,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477256,-99) , 
4, 4468.85, 1, 0, 0.494106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377597,-99) , 
2, 0.00367752, 1, 0, 0.491801,-99) , 
6, 0.0743577, 1, 0, 0.498852,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.0289489);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636965,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499584,-99) , 
5, 2.04989, 0, 0, 0.514087,-99) , 
NN(
0, 
0, 
-1, 0.00212616, 1, -1, 0.488767,-99) , 
3, 5.49559, 0, 0, 0.495026,-99) , 
3, 7.59532, 0, 0, 0.497718,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.02685);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614325,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497071,-99) , 
3, 6.43003, 0, 0, 0.50093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443757,-99) , 
4, 1127.84, 0, 0, 0.49709,-99) , 
0, 6.15503, 0, 0, 0.501333,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.0294516);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.685091,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497448,-99) , 
6, 0.0720516, 1, 0, 0.504616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.105232,-99) , 
2, 0.00405427, 1, 0, 0.501838,-99) , 
0, 6.70669, 0, 0, 0.505364,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.0332764);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.66496,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542409,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482731,-99) , 
3, 3.82807, 0, 0, 0.499555,-99) , 
4, 1200.81, 1, 0, 0.503357,-99) , 
2, 0.00445653, 0, 0, 0.506521,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.030715);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618102,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544205,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446045,-99) , 
4, 1162.91, 0, 0, 0.502852,-99) , 
6, 3.39529, 0, 0, 0.50643,-99) , 
3, 7.61926, 0, 0, 0.508363,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.0209919);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.680037,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444651,-99) , 
4, 1009.7, 0, 0, 0.497411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453347,-99) , 
3, 2.22026, 0, 0, 0.493786,-99) , 
2, 0.00445969, 0, 0, 0.497748,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.031324);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598658,-99) , 
NN(
0, 
0, 
-1, 5.39022, 1, -1, 0.490913,-99) , 
0, 5.81778, 0, 0, 0.495865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35386,-99) , 
2, 0.00371199, 1, 0, 0.493243,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.0403395);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563498,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495742,-99) , 
6, 1.64415, 0, 0, 0.502812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520828,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350587,-99) , 
2, 0.00140078, 1, 0, 0.469676,-99) , 
6, 2.26549, 1, 0, 0.497757,-99) , 
4, 874.313, 1, 0, 0.500986,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.0432011);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638678,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425424,-99) , 
2, 0.00342025, 1, 0, 0.51393,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388087,-99) , 
2, 0.00156896, 1, 0, 0.483503,-99) , 
5, 2.56137, 1, 0, 0.50998,-99) , 
2, 0.00426053, 0, 0, 0.512664,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.0662059);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477115,-99) , 
0, 2.2665, 0, 0, 0.514727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38698,-99) , 
2, 0.00277035, 1, 0, 0.507642,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478795,-99) , 
3, 5.23277, 0, 0, 0.492763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377054,-99) , 
2, 0.00239071, 1, 0, 0.482147,-99) , 
6, 0.735713, 1, 0, 0.496808,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.0320544);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607487,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495652,-99) , 
3, 3.42179, 1, 0, 0.502936,-99) , 
2, 0.00352607, 0, 0, 0.506571,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388295,-99) , 
2, 0.00139754, 1, 0, 0.467164,-99) , 
6, 2.65335, 1, 0, 0.501907,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.0433026);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485501,-99) , 
4, 3286.19, 1, 0, 0.518216,-99) , 
NN(
0, 
0, 
-1, 4.91447, 1, -1, 0.489196,-99) , 
3, 5.17979, 0, 0, 0.499061,-99) , 
NN(
0, 
0, 
-1, 0.001565, 1, -1, 0.448552,-99) , 
6, 0.0239058, 0, 0, 0.493789,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.0364839);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574011,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498547,-99) , 
6, 0.749749, 0, 0, 0.510552,-99) , 
0, 5.45617, 0, 0, 0.515038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390529,-99) , 
2, 0.00375001, 1, 0, 0.512783,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.0373461);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622445,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423369,-99) , 
2, 0.0028794, 1, 0, 0.512861,-99) , 
2, 0.00356178, 0, 0, 0.514575,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46336,-99) , 
0, 5.55729, 1, 0, 0.511491,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.0358263);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.38346, 1, 1, 0.523751,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54063,-99) , 
NN(
0, 
0, 
-1, 2.63748, 1, -1, 0.486473,-99) , 
4, 1253.57, 1, 0, 0.492037,-99) , 
0, 1.73806, 1, 0, 0.49883,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.0293418);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607765,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482854,-99) , 
0, 1.67303, 0, 0, 0.50362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358287,-99) , 
2, 0.00370323, 1, 0, 0.501945,-99) , 
0, 6.28378, 0, 0, 0.505083,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.026777);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660352,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494991,-99) , 
0, 4.00498, 0, 0, 0.502006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419389,-99) , 
3, 7.06878, 1, 0, 0.500409,-99) , 
3, 7.60471, 0, 0, 0.503522,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.0299143);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531532,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532385,-99) , 
NN(
0, 
0, 
-1, 1560.06, 0, -1, 0.489273,-99) , 
4, 1299.22, 1, 0, 0.493922,-99) , 
0, 0.84361, 1, 0, 0.497771,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.0507908);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.628664,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454047,-99) , 
4, 1415.43, 0, 0, 0.51778,-99) , 
NN(
0, 
0, 
-1, 6.64169, 1, -1, 0.482261,-99) , 
0, 3.43626, 1, 0, 0.503112,-99) , 
3, 7.5923, 0, 0, 0.50545,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.0332278);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496407,-99) , 
4, 2701.96, 0, 0, 0.51531,-99) , 
NN(
0, 
0, 
-1, 0.00227124, 1, -1, 0.487633,-99) , 
5, 0.72655, 1, 0, 0.503701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303462,-99) , 
2, 0.00522426, 1, 0, 0.502538,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.0499883);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568726,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480199,-99) , 
0, 4.31259, 1, 0, 0.510919,-99) , 
4, 931.99, 1, 0, 0.514231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317985,-99) , 
0, 6.19707, 1, 0, 0.51035,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.0298089);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607256,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491963,-99) , 
0, 3.86188, 0, 0, 0.500104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434601,-99) , 
0, 5.7024, 1, 0, 0.497618,-99) , 
0, 6.68159, 0, 0, 0.499363,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.0425375);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667717,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480798,-99) , 
4, 1640.93, 0, 0, 0.504518,-99) , 
0, 6.48275, 0, 0, 0.508702,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351132,-99) , 
2, 0.00124842, 1, 0, 0.4497,-99) , 
6, 2.27815, 1, 0, 0.499819,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.0356198);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596846,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449456,-99) , 
4, 1186.87, 0, 0, 0.503752,-99) , 
2, 0.00329329, 0, 0, 0.507754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452273,-99) , 
6, 2.98838, 1, 0, 0.502438,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.0310941);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562877,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489985,-99) , 
5, 3.59758, 0, 0, 0.493059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362045,-99) , 
2, 0.00355093, 1, 0, 0.491559,-99) , 
0, 5.8664, 0, 0, 0.49511,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.0328186);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605719,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45683,-99) , 
3, 4.17488, 0, 0, 0.532627,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339142,-99) , 
2, 0.00253998, 1, 0, 0.497289,-99) , 
0, 4.4655, 0, 0, 0.5045,-99) , 
2, 0.00401147, 0, 0, 0.50673,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.0620162);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.70091, 0, 1, 0.538253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393336,-99) , 
2, 0.00121916, 1, 0, 0.517742,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479867,-99) , 
4, 2064.87, 1, 0, 0.490006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394187,-99) , 
2, 0.00303984, 1, 0, 0.484918,-99) , 
3, 3.43505, 1, 0, 0.493403,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.0210947);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552412,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411419,-99) , 
2, 0.00258356, 1, 0, 0.499114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454302,-99) , 
3, 6.23554, 1, 0, 0.495321,-99) , 
0, 5.44034, 0, 0, 0.500007,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.0378656);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597456,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494329,-99) , 
4, 1260.72, 1, 0, 0.50484,-99) , 
NN(
0, 
0, 
-1, 0.00201891, 1, -1, 0.481582,-99) , 
0, 3.86104, 0, 0, 0.489253,-99) , 
3, 7.50115, 0, 0, 0.491501,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.0450819);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419199,-99) , 
2, 0.0025527, 1, 0, 0.520166,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469939,-99) , 
5, 0.742898, 1, 0, 0.48819,-99) , 
3, 5.95467, 0, 0, 0.493302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.202976,-99) , 
2, 0.00483962, 1, 0, 0.491452,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.0716571);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.09624, 0, 1, 0.524594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400832,-99) , 
2, 0.00204231, 1, 0, 0.512904,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414463,-99) , 
2, 0.00158597, 1, 0, 0.516021,-99) , 
NN(
0, 
0, 
-1, 0.00439341, 1, -1, 0.474067,-99) , 
6, 0.166933, 1, 0, 0.486963,-99) , 
4, 4222.82, 0, 0, 0.496262,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.0170677);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603041,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459333,-99) , 
5, 3.13704, 1, 0, 0.498091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349148,-99) , 
0, 6.38945, 1, 0, 0.49628,-99) , 
3, 7.61852, 0, 0, 0.498045,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.0526376);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530527,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479906,-99) , 
0, 2.24928, 0, 0, 0.496556,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359641,-99) , 
2, 0.0018527, 1, 0, 0.469472,-99) , 
3, 5.52026, 1, 0, 0.491043,-99) , 
0, 5.36467, 0, 0, 0.49439,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.0360815);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490254,-99) , 
3, 6.29881, 0, 0, 0.495463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331637,-99) , 
2, 0.00479899, 1, 0, 0.494212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428958,-99) , 
5, 0.0109774, 0, 0, 0.489609,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.038714);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559977,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470918,-99) , 
4, 5455.94, 1, 0, 0.503633,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370056,-99) , 
2, 0.000983918, 1, 0, 0.473457,-99) , 
3, 3.16717, 0, 0, 0.497468,-99) , 
3, 6.86016, 0, 0, 0.500955,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.0193345);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00358369, 0, 1, 0.504605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4575,-99) , 
3, 6.65833, 1, 0, 0.501753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449652,-99) , 
6, 0.00880131, 0, 0, 0.498436,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.0348444);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490745,-99) , 
4, 1493.31, 1, 0, 0.495019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444449,-99) , 
4, 1195.06, 0, 0, 0.491243,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.218377,-99) , 
2, 0.00482024, 1, 0, 0.489491,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.0722326);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.21471, 0, 1, 0.540233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388801,-99) , 
2, 0.00113126, 1, 0, 0.513009,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468511,-99) , 
4, 3011.55, 0, 0, 0.489207,-99) , 
NN(
0, 
0, 
-1, 0.00158416, 1, -1, 0.445637,-99) , 
6, 1.41223, 1, 0, 0.477649,-99) , 
3, 3.86122, 1, 0, 0.490281,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.0424535);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487468,-99) , 
0, 3.44531, 0, 0, 0.532498,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47712,-99) , 
5, 0.765453, 0, 0, 0.488377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41058,-99) , 
0, 6.19778, 1, 0, 0.486506,-99) , 
4, 1679.31, 1, 0, 0.494049,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.0302835);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648632,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403293,-99) , 
2, 0.00409466, 1, 0, 0.504467,-99) , 
NN(
0, 
0, 
-1, 0.000920092, 1, -1, 0.464324,-99) , 
3, 3.18045, 0, 0, 0.496425,-99) , 
0, 6.56201, 0, 0, 0.499516,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.0389221);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644937,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278153,-99) , 
2, 0.00319672, 1, 0, 0.503186,-99) , 
3, 6.94205, 0, 0, 0.509703,-99) , 
NN(
0, 
0, 
-1, 0.00262604, 1, -1, 0.481276,-99) , 
4, 3062.49, 1, 0, 0.494046,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.0223089);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608326,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34683,-99) , 
2, 0.00329289, 1, 0, 0.497661,-99) , 
0, 6.56238, 0, 0, 0.499681,-99) , 
NN(
0, 
0, 
-1, 0.00192856, 1, -1, 0.458708,-99) , 
5, 2.21714, 1, 0, 0.493264,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.0376416);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580184,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472813,-99) , 
5, 0.290023, 0, 0, 0.493,-99) , 
3, 6.53993, 0, 0, 0.49732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406051,-99) , 
3, 7.04738, 1, 0, 0.494535,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.0346362);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545711,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481028,-99) , 
4, 4164.94, 1, 0, 0.496497,-99) , 
NN(
0, 
0, 
-1, 0.00137407, 1, -1, 0.452748,-99) , 
6, 0.0377644, 0, 0, 0.490717,-99) , 
5, 3.44652, 0, 0, 0.49539,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.0557647);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485292,-99) , 
4, 3515.18, 0, 0, 0.514157,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476006,-99) , 
0, 5.10248, 0, 0, 0.483566,-99) , 
0, 2.08283, 1, 0, 0.492101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351697,-99) , 
2, 0.00378604, 1, 0, 0.48988,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.0479164);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548849,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532613,-99) , 
NN(
0, 
0, 
-1, 0.00321649, 1, -1, 0.478681,-99) , 
4, 1245.77, 1, 0, 0.484077,-99) , 
3, 6.8342, 0, 0, 0.487735,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.034109);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.628471,-99) , 
NN(
NN(
0, 
0, 
-1, 0.424324, 1, 1, 0.505767,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461398,-99) , 
5, 0.20942, 1, 0, 0.478392,-99) , 
6, 0.315568, 0, 0, 0.495357,-99) , 
2, 0.00407875, 0, 0, 0.498228,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.051395);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476913,-99) , 
6, 2.27205, 1, 0, 0.50599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451372,-99) , 
4, 1036.57, 0, 0, 0.502935,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538403,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465039,-99) , 
4, 2238.89, 1, 0, 0.48671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425324,-99) , 
6, 0.122114, 1, 0, 0.475167,-99) , 
6, 0.195856, 0, 0, 0.494565,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.0308983);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547414,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489393,-99) , 
6, 3.25202, 0, 0, 0.493141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335852,-99) , 
2, 0.00483243, 1, 0, 0.491964,-99) , 
6, 0.00536224, 1, 0, 0.49519,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.0434623);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.2957, 1, 1, 0.512566,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38328,-99) , 
2, 0.00113157, 1, 0, 0.489039,-99) , 
3, 4.04128, 0, 0, 0.50365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332318,-99) , 
2, 0.00458066, 1, 0, 0.502205,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.0385275);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587294,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489038,-99) , 
6, 0.162537, 1, 0, 0.497148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451574,-99) , 
6, 0.0232704, 0, 0, 0.492545,-99) , 
2, 0.00409477, 0, 0, 0.494412,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.0229256);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588271,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468651,-99) , 
5, 2.82573, 1, 0, 0.501718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423947,-99) , 
0, 6.10666, 1, 0, 0.500144,-99) , 
2, 0.00412066, 0, 0, 0.50184,-99)    );
   return;
};
 
// Clean up
inline void Read2012_BDT_0::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double Read2012_BDT_0::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
