#include "Variables_Analysis.h"

Bc2Dmunu::Variables_Analysis::Variables_Analysis(){}
Bc2Dmunu::Variables_Analysis::~Variables_Analysis(){}

void Bc2Dmunu::Variables_Analysis::setInputBranches(TTree *tree) {
  tree->SetBranchAddress("Bplus_IPCHI2_OWNPV"                    , &Bplus_IPCHI2_OWNPV                      );
  tree->SetBranchAddress("Bplus_IP_OWNPV"                        , &Bplus_IP_OWNPV                          );
  tree->SetBranchAddress("Bplus_MINIP"                           , &Bplus_MINIP                             );
  tree->SetBranchAddress("Bplus_MINIPCHI2"                       , &Bplus_MINIPCHI2                         );
  tree->SetBranchAddress("Bplus_P"                               , &Bplus_P                                 );
  tree->SetBranchAddress("Bplus_PT"                              , &Bplus_PT                                );
  tree->SetBranchAddress("Bplus_PE"                              , &Bplus_PE                                );
  tree->SetBranchAddress("Bplus_PX"                              , &Bplus_PX                                );
  tree->SetBranchAddress("Bplus_PY"                              , &Bplus_PY                                );
  tree->SetBranchAddress("Bplus_PZ"                              , &Bplus_PZ                                );
  tree->SetBranchAddress("Bplus_MM"                              , &Bplus_MM                                );
  tree->SetBranchAddress("Bplus_MMERR"                           , &Bplus_MMERR                             );
  tree->SetBranchAddress("Bplus_M"                               , &Bplus_M                                 );
  tree->SetBranchAddress("Bplus_DIRA_OWNPV"                      , &Bplus_DIRA_OWNPV                        );
  tree->SetBranchAddress("Bplus_DTF_CHI2"                        , &Bplus_DTF_CHI2                          );
  tree->SetBranchAddress("Bplus_ENDVERTEX_CHI2"                  , &Bplus_ENDVERTEX_CHI2                    );
  tree->SetBranchAddress("Bplus_FD_CHI2"                         , &Bplus_FD_CHI2                           );
  tree->SetBranchAddress("Bplus_Mcorr"                           , &Bplus_Mcorr                             );
  tree->SetBranchAddress("Bplus_TAU"                             , &Bplus_TAU                               );
  tree->SetBranchAddress("Bplus_L0Global_Dec"                    , &Bplus_L0Global_Dec                      );
  tree->SetBranchAddress("Bplus_L0Global_TIS"                    , &Bplus_L0Global_TIS                      );
  tree->SetBranchAddress("Bplus_L0Global_TOS"                    , &Bplus_L0Global_TOS                      );
  tree->SetBranchAddress("Bplus_Hlt1Global_Dec"                  , &Bplus_Hlt1Global_Dec                    );
  tree->SetBranchAddress("Bplus_Hlt1Global_TIS"                  , &Bplus_Hlt1Global_TIS                    );
  tree->SetBranchAddress("Bplus_Hlt1Global_TOS"                  , &Bplus_Hlt1Global_TOS                    );
  tree->SetBranchAddress("Bplus_Hlt1Phys_Dec"                    , &Bplus_Hlt1Phys_Dec                      );
  tree->SetBranchAddress("Bplus_Hlt1Phys_TIS"                    , &Bplus_Hlt1Phys_TIS                      );
  tree->SetBranchAddress("Bplus_Hlt1Phys_TOS"                    , &Bplus_Hlt1Phys_TOS                      );
  tree->SetBranchAddress("Bplus_Hlt2Global_Dec"                  , &Bplus_Hlt2Global_Dec                    );
  tree->SetBranchAddress("Bplus_Hlt2Global_TIS"                  , &Bplus_Hlt2Global_TIS                    );
  tree->SetBranchAddress("Bplus_Hlt2Global_TOS"                  , &Bplus_Hlt2Global_TOS                    );
  tree->SetBranchAddress("Bplus_Hlt2Phys_Dec"                    , &Bplus_Hlt2Phys_Dec                      );
  tree->SetBranchAddress("Bplus_Hlt2Phys_TIS"                    , &Bplus_Hlt2Phys_TIS                      );
  tree->SetBranchAddress("Bplus_Hlt2Phys_TOS"                    , &Bplus_Hlt2Phys_TOS                      );
  tree->SetBranchAddress("Bplus_L0MuonDecision_Dec"              , &Bplus_L0MuonDecision_Dec                );
  tree->SetBranchAddress("Bplus_L0MuonDecision_TIS"              , &Bplus_L0MuonDecision_TIS                );
  tree->SetBranchAddress("Bplus_L0MuonDecision_TOS"              , &Bplus_L0MuonDecision_TOS                );
  tree->SetBranchAddress("Bplus_Hlt1TrackMuonDecision_Dec"       , &Bplus_Hlt1TrackMuonDecision_Dec         );
  tree->SetBranchAddress("Bplus_Hlt1TrackMuonDecision_TIS"       , &Bplus_Hlt1TrackMuonDecision_TIS         );
  tree->SetBranchAddress("Bplus_Hlt1TrackMuonDecision_TOS"       , &Bplus_Hlt1TrackMuonDecision_TOS         );
  tree->SetBranchAddress("Bplus_Hlt2TopoMu2BodyBBDTDecision_Dec" , &Bplus_Hlt2TopoMu2BodyBBDTDecision_Dec   );
  tree->SetBranchAddress("Bplus_Hlt2TopoMu2BodyBBDTDecision_TIS" , &Bplus_Hlt2TopoMu2BodyBBDTDecision_TIS   );
  tree->SetBranchAddress("Bplus_Hlt2TopoMu2BodyBBDTDecision_TOS" , &Bplus_Hlt2TopoMu2BodyBBDTDecision_TOS   );
  tree->SetBranchAddress("Bplus_Hlt2TopoMu3BodyBBDTDecision_Dec" , &Bplus_Hlt2TopoMu3BodyBBDTDecision_Dec   );
  tree->SetBranchAddress("Bplus_Hlt2TopoMu3BodyBBDTDecision_TIS" , &Bplus_Hlt2TopoMu3BodyBBDTDecision_TIS   );
  tree->SetBranchAddress("Bplus_Hlt2TopoMu3BodyBBDTDecision_TOS" , &Bplus_Hlt2TopoMu3BodyBBDTDecision_TOS   );
  tree->SetBranchAddress("Bplus_Hlt2SingleMuonDecision_Dec"      , &Bplus_Hlt2SingleMuonDecision_Dec        );
  tree->SetBranchAddress("Bplus_Hlt2SingleMuonDecision_TIS"      , &Bplus_Hlt2SingleMuonDecision_TIS        );
  tree->SetBranchAddress("Bplus_Hlt2SingleMuonDecision_TOS"      , &Bplus_Hlt2SingleMuonDecision_TOS        );
  tree->SetBranchAddress("D0_IPCHI2_OWNPV"                       , &D0_IPCHI2_OWNPV                         );
  tree->SetBranchAddress("D0_IP_OWNPV"                           , &D0_IP_OWNPV                             );
  tree->SetBranchAddress("D0_MINIP"                              , &D0_MINIP                                );
  tree->SetBranchAddress("D0_MINIPCHI2"                          , &D0_MINIPCHI2                            );
  tree->SetBranchAddress("D0_P"                                  , &D0_P                                    );
  tree->SetBranchAddress("D0_PT"                                 , &D0_PT                                   );
  tree->SetBranchAddress("D0_PE"                                 , &D0_PE                                   );
  tree->SetBranchAddress("D0_PX"                                 , &D0_PX                                   );
  tree->SetBranchAddress("D0_PY"                                 , &D0_PY                                   );
  tree->SetBranchAddress("D0_PZ"                                 , &D0_PZ                                   );
  tree->SetBranchAddress("D0_MM"                                 , &D0_MM                                   );
  tree->SetBranchAddress("D0_MMERR"                              , &D0_MMERR                                );
  tree->SetBranchAddress("D0_M"                                  , &D0_M                                    );
  tree->SetBranchAddress("D0_DIRA_OWNPV"                         , &D0_DIRA_OWNPV                           );
  tree->SetBranchAddress("D0_DTF_CHI2"                           , &D0_DTF_CHI2                             );
  tree->SetBranchAddress("D0_ENDVERTEX_CHI2"                     , &D0_ENDVERTEX_CHI2                       );
  tree->SetBranchAddress("D0_FD_CHI2"                            , &D0_FD_CHI2                              );
  tree->SetBranchAddress("D0_ID"                                 , &D0_ID                                   );
  tree->SetBranchAddress("D0_TAU"                                , &D0_TAU                                  );
  tree->SetBranchAddress("Kminus_IPCHI2_OWNPV"                   , &Kminus_IPCHI2_OWNPV                     );
  tree->SetBranchAddress("Kminus_IP_OWNPV"                       , &Kminus_IP_OWNPV                         );
  tree->SetBranchAddress("Kminus_MINIP"                          , &Kminus_MINIP                            );
  tree->SetBranchAddress("Kminus_MINIPCHI2"                      , &Kminus_MINIPCHI2                        );
  tree->SetBranchAddress("Kminus_P"                              , &Kminus_P                                );
  tree->SetBranchAddress("Kminus_PT"                             , &Kminus_PT                               );
  tree->SetBranchAddress("Kminus_PE"                             , &Kminus_PE                               );
  tree->SetBranchAddress("Kminus_PX"                             , &Kminus_PX                               );
  tree->SetBranchAddress("Kminus_PY"                             , &Kminus_PY                               );
  tree->SetBranchAddress("Kminus_PZ"                             , &Kminus_PZ                               );
  tree->SetBranchAddress("Kminus_M"                              , &Kminus_M                                );
  tree->SetBranchAddress("Kminus_NNK"                            , &Kminus_NNK                              );
  tree->SetBranchAddress("Kminus_NNKmu"                          , &Kminus_NNKmu                            );
  tree->SetBranchAddress("Kminus_NNKpi"                          , &Kminus_NNKpi                            );
  tree->SetBranchAddress("Kminus_NNmu"                           , &Kminus_NNmu                             );
  tree->SetBranchAddress("Kminus_NNpi"                           , &Kminus_NNpi                             );
  tree->SetBranchAddress("Kminus_PIDK"                           , &Kminus_PIDK                             );
  tree->SetBranchAddress("Kminus_PIDmu"                          , &Kminus_PIDmu                            );
  tree->SetBranchAddress("Kminus_TRACK_CHI2"                     , &Kminus_TRACK_CHI2                       );
  tree->SetBranchAddress("Kminus_ghost"                          , &Kminus_ghost                            );
  tree->SetBranchAddress("Kminus_inMuon"                         , &Kminus_inMuon                           );
  tree->SetBranchAddress("Kminus_isMuon"                         , &Kminus_isMuon                           );
  tree->SetBranchAddress("Kminus_isMuonLoose"                    , &Kminus_isMuonLoose                      );
  tree->SetBranchAddress("piplus_IPCHI2_OWNPV"                   , &piplus_IPCHI2_OWNPV                     );
  tree->SetBranchAddress("piplus_IP_OWNPV"                       , &piplus_IP_OWNPV                         );
  tree->SetBranchAddress("piplus_MINIP"                          , &piplus_MINIP                            );
  tree->SetBranchAddress("piplus_MINIPCHI2"                      , &piplus_MINIPCHI2                        );
  tree->SetBranchAddress("piplus_P"                              , &piplus_P                                );
  tree->SetBranchAddress("piplus_PT"                             , &piplus_PT                               );
  tree->SetBranchAddress("piplus_PE"                             , &piplus_PE                               );
  tree->SetBranchAddress("piplus_PX"                             , &piplus_PX                               );
  tree->SetBranchAddress("piplus_PY"                             , &piplus_PY                               );
  tree->SetBranchAddress("piplus_PZ"                             , &piplus_PZ                               );
  tree->SetBranchAddress("piplus_M"                              , &piplus_M                                );
  tree->SetBranchAddress("piplus_NNK"                            , &piplus_NNK                              );
  tree->SetBranchAddress("piplus_NNKmu"                          , &piplus_NNKmu                            );
  tree->SetBranchAddress("piplus_NNKpi"                          , &piplus_NNKpi                            );
  tree->SetBranchAddress("piplus_NNmu"                           , &piplus_NNmu                             );
  tree->SetBranchAddress("piplus_NNpi"                           , &piplus_NNpi                             );
  tree->SetBranchAddress("piplus_PIDK"                           , &piplus_PIDK                             );
  tree->SetBranchAddress("piplus_PIDmu"                          , &piplus_PIDmu                            );
  tree->SetBranchAddress("piplus_TRACK_CHI2"                     , &piplus_TRACK_CHI2                       );
  tree->SetBranchAddress("piplus_ghost"                          , &piplus_ghost                            );
  tree->SetBranchAddress("piplus_inMuon"                         , &piplus_inMuon                           );
  tree->SetBranchAddress("piplus_isMuon"                         , &piplus_isMuon                           );
  tree->SetBranchAddress("piplus_isMuonLoose"                    , &piplus_isMuonLoose                      );
  tree->SetBranchAddress("muplus_IPCHI2_OWNPV"                   , &muplus_IPCHI2_OWNPV                     );
  tree->SetBranchAddress("muplus_IP_OWNPV"                       , &muplus_IP_OWNPV                         );
  tree->SetBranchAddress("muplus_MINIP"                          , &muplus_MINIP                            );
  tree->SetBranchAddress("muplus_MINIPCHI2"                      , &muplus_MINIPCHI2                        );
  tree->SetBranchAddress("muplus_P"                              , &muplus_P                                );
  tree->SetBranchAddress("muplus_PT"                             , &muplus_PT                               );
  tree->SetBranchAddress("muplus_PE"                             , &muplus_PE                               );
  tree->SetBranchAddress("muplus_PX"                             , &muplus_PX                               );
  tree->SetBranchAddress("muplus_PY"                             , &muplus_PY                               );
  tree->SetBranchAddress("muplus_PZ"                             , &muplus_PZ                               );
  tree->SetBranchAddress("muplus_M"                              , &muplus_M                                );
  tree->SetBranchAddress("muplus_NNK"                            , &muplus_NNK                              );
  tree->SetBranchAddress("muplus_NNKmu"                          , &muplus_NNKmu                            );
  tree->SetBranchAddress("muplus_NNKpi"                          , &muplus_NNKpi                            );
  tree->SetBranchAddress("muplus_NNmu"                           , &muplus_NNmu                             );
  tree->SetBranchAddress("muplus_NNpi"                           , &muplus_NNpi                             );
  tree->SetBranchAddress("muplus_PIDK"                           , &muplus_PIDK                             );
  tree->SetBranchAddress("muplus_PIDmu"                          , &muplus_PIDmu                            );
  tree->SetBranchAddress("muplus_TRACK_CHI2"                     , &muplus_TRACK_CHI2                       );
  tree->SetBranchAddress("muplus_ghost"                          , &muplus_ghost                            );
  tree->SetBranchAddress("muplus_inMuon"                         , &muplus_inMuon                           );
  tree->SetBranchAddress("muplus_isMuon"                         , &muplus_isMuon                           );
  tree->SetBranchAddress("muplus_isMuonLoose"                    , &muplus_isMuonLoose                      );
  tree->SetBranchAddress("nCandidate"                            , &nCandidate                              );
  tree->SetBranchAddress("totCandidates"                         , &totCandidates                           );
  tree->SetBranchAddress("EventInSequence"                       , &EventInSequence                         );
  tree->SetBranchAddress("runNumber"                             , &runNumber                               );
  tree->SetBranchAddress("eventNumber"                           , &eventNumber                             );
  tree->SetBranchAddress("BCID"                                  , &BCID                                    );
  tree->SetBranchAddress("BCType"                                , &BCType                                  );
  tree->SetBranchAddress("OdinTCK"                               , &OdinTCK                                 );
  tree->SetBranchAddress("L0DUTCK"                               , &L0DUTCK                                 );
  tree->SetBranchAddress("HLT1TCK"                               , &HLT1TCK                                 );
  tree->SetBranchAddress("HLT2TCK"                               , &HLT2TCK                                 );
  tree->SetBranchAddress("GpsTime"                               , &GpsTime                                 );
  tree->SetBranchAddress("Polarity"                              , &Polarity                                );
  tree->SetBranchAddress("nPVs"                                  , &nPVs                                    );
  tree->SetBranchAddress("nTracks"                               , &nTracks                                 );
  tree->SetBranchAddress("nLongTracks"                           , &nLongTracks                             );
  tree->SetBranchAddress("nDownstreamTracks"                     , &nDownstreamTracks                       );
  tree->SetBranchAddress("nUpstreamTracks"                       , &nUpstreamTracks                         );
  tree->SetBranchAddress("nVeloTracks"                           , &nVeloTracks                             );
  tree->SetBranchAddress("nTTracks"                              , &nTTracks                                );
  tree->SetBranchAddress("nBackTracks"                           , &nBackTracks                             );
  tree->SetBranchAddress("nRich1Hits"                            , &nRich1Hits                              );
  tree->SetBranchAddress("nRich2Hits"                            , &nRich2Hits                              );
  tree->SetBranchAddress("nVeloClusters"                         , &nVeloClusters                           );
  tree->SetBranchAddress("nITClusters"                           , &nITClusters                             );
  tree->SetBranchAddress("nTTClusters"                           , &nTTClusters                             );
  tree->SetBranchAddress("nOTClusters"                           , &nOTClusters                             );
  tree->SetBranchAddress("nSPDHits"                              , &nSPDHits                                );
  tree->SetBranchAddress("nMuonCoordsS0"                         , &nMuonCoordsS0                           );
  tree->SetBranchAddress("nMuonCoordsS1"                         , &nMuonCoordsS1                           );
  tree->SetBranchAddress("nMuonCoordsS2"                         , &nMuonCoordsS2                           );
  tree->SetBranchAddress("nMuonCoordsS3"                         , &nMuonCoordsS3                           );
  tree->SetBranchAddress("nMuonCoordsS4"                         , &nMuonCoordsS4                           );
  tree->SetBranchAddress("nMuonTracks"                           , &nMuonTracks                             );
}

void Bc2Dmunu::Variables_Analysis::setOutputBranches(TTree *tree) {
  tree->Branch("itype"                                 , &itype                                   );
  tree->Branch("sqrts"                                 , &sqrts                                   );
  tree->Branch("evname"                                , &evname                                  );
  tree->Branch("year"                                  , &year                                    );

  tree->Branch("Bplus_IPCHI2_OWNPV"                    , &Bplus_IPCHI2_OWNPV                      , "Bplus_IPCHI2_OWNPV/D"                  );
  tree->Branch("Bplus_IP_OWNPV"                        , &Bplus_IP_OWNPV                          , "Bplus_IP_OWNPV/D"                      );
  tree->Branch("Bplus_MINIP"                           , &Bplus_MINIP                             , "Bplus_MINIP/D"                         );
  tree->Branch("Bplus_MINIPCHI2"                       , &Bplus_MINIPCHI2                         , "Bplus_MINIPCHI2/D"                     );
  tree->Branch("Bplus_P"                               , &Bplus_P                                 , "Bplus_P/D"                             );
  tree->Branch("Bplus_PT"                              , &Bplus_PT                                , "Bplus_PT/D"                            );
  tree->Branch("Bplus_PE"                              , &Bplus_PE                                , "Bplus_PE/D"                            );
  tree->Branch("Bplus_PX"                              , &Bplus_PX                                , "Bplus_PX/D"                            );
  tree->Branch("Bplus_PY"                              , &Bplus_PY                                , "Bplus_PY/D"                            );
  tree->Branch("Bplus_PZ"                              , &Bplus_PZ                                , "Bplus_PZ/D"                            );
  tree->Branch("Bplus_MM"                              , &Bplus_MM                                , "Bplus_MM/D"                            );
  tree->Branch("Bplus_MMERR"                           , &Bplus_MMERR                             , "Bplus_MMERR/D"                         );
  tree->Branch("Bplus_M"                               , &Bplus_M                                 , "Bplus_M/D"                             );
  tree->Branch("Bplus_DIRA_OWNPV"                      , &Bplus_DIRA_OWNPV                        , "Bplus_DIRA_OWNPV/D"                    );
  tree->Branch("Bplus_DTF_CHI2"                        , &Bplus_DTF_CHI2                          , "Bplus_DTF_CHI2/D"                      );
  tree->Branch("Bplus_ENDVERTEX_CHI2"                  , &Bplus_ENDVERTEX_CHI2                    , "Bplus_ENDVERTEX_CHI2/D"                );
  tree->Branch("Bplus_FD_CHI2"                         , &Bplus_FD_CHI2                           , "Bplus_FD_CHI2/D"                       );
  tree->Branch("Bplus_Mcorr"                           , &Bplus_Mcorr                             , "Bplus_Mcorr/D"                         );
  tree->Branch("Bplus_TAU"                             , &Bplus_TAU                               , "Bplus_TAU/D"                           );
  tree->Branch("Bplus_L0Global_Dec"                    , &Bplus_L0Global_Dec                      , "Bplus_L0Global_Dec/O"                  );
  tree->Branch("Bplus_L0Global_TIS"                    , &Bplus_L0Global_TIS                      , "Bplus_L0Global_TIS/O"                  );
  tree->Branch("Bplus_L0Global_TOS"                    , &Bplus_L0Global_TOS                      , "Bplus_L0Global_TOS/O"                  );
  tree->Branch("Bplus_Hlt1Global_Dec"                  , &Bplus_Hlt1Global_Dec                    , "Bplus_Hlt1Global_Dec/O"                );
  tree->Branch("Bplus_Hlt1Global_TIS"                  , &Bplus_Hlt1Global_TIS                    , "Bplus_Hlt1Global_TIS/O"                );
  tree->Branch("Bplus_Hlt1Global_TOS"                  , &Bplus_Hlt1Global_TOS                    , "Bplus_Hlt1Global_TOS/O"                );
  tree->Branch("Bplus_Hlt1Phys_Dec"                    , &Bplus_Hlt1Phys_Dec                      , "Bplus_Hlt1Phys_Dec/O"                  );
  tree->Branch("Bplus_Hlt1Phys_TIS"                    , &Bplus_Hlt1Phys_TIS                      , "Bplus_Hlt1Phys_TIS/O"                  );
  tree->Branch("Bplus_Hlt1Phys_TOS"                    , &Bplus_Hlt1Phys_TOS                      , "Bplus_Hlt1Phys_TOS/O"                  );
  tree->Branch("Bplus_Hlt2Global_Dec"                  , &Bplus_Hlt2Global_Dec                    , "Bplus_Hlt2Global_Dec/O"                );
  tree->Branch("Bplus_Hlt2Global_TIS"                  , &Bplus_Hlt2Global_TIS                    , "Bplus_Hlt2Global_TIS/O"                );
  tree->Branch("Bplus_Hlt2Global_TOS"                  , &Bplus_Hlt2Global_TOS                    , "Bplus_Hlt2Global_TOS/O"                );
  tree->Branch("Bplus_Hlt2Phys_Dec"                    , &Bplus_Hlt2Phys_Dec                      , "Bplus_Hlt2Phys_Dec/O"                  );
  tree->Branch("Bplus_Hlt2Phys_TIS"                    , &Bplus_Hlt2Phys_TIS                      , "Bplus_Hlt2Phys_TIS/O"                  );
  tree->Branch("Bplus_Hlt2Phys_TOS"                    , &Bplus_Hlt2Phys_TOS                      , "Bplus_Hlt2Phys_TOS/O"                  );
  tree->Branch("Bplus_L0MuonDecision_Dec"              , &Bplus_L0MuonDecision_Dec                , "Bplus_L0MuonDecision_Dec/O"            );
  tree->Branch("Bplus_L0MuonDecision_TIS"              , &Bplus_L0MuonDecision_TIS                , "Bplus_L0MuonDecision_TIS/O"            );
  tree->Branch("Bplus_L0MuonDecision_TOS"              , &Bplus_L0MuonDecision_TOS                , "Bplus_L0MuonDecision_TOS/O"            );
  tree->Branch("Bplus_Hlt1TrackMuonDecision_Dec"       , &Bplus_Hlt1TrackMuonDecision_Dec         , "Bplus_Hlt1TrackMuonDecision_Dec/O"     );
  tree->Branch("Bplus_Hlt1TrackMuonDecision_TIS"       , &Bplus_Hlt1TrackMuonDecision_TIS         , "Bplus_Hlt1TrackMuonDecision_TIS/O"     );
  tree->Branch("Bplus_Hlt1TrackMuonDecision_TOS"       , &Bplus_Hlt1TrackMuonDecision_TOS         , "Bplus_Hlt1TrackMuonDecision_TOS/O"     );
  tree->Branch("Bplus_Hlt2TopoMu2BodyBBDTDecision_Dec" , &Bplus_Hlt2TopoMu2BodyBBDTDecision_Dec   , "Bplus_Hlt2TopoMu2BodyBBDTDecision_Dec/O");
  tree->Branch("Bplus_Hlt2TopoMu2BodyBBDTDecision_TIS" , &Bplus_Hlt2TopoMu2BodyBBDTDecision_TIS   , "Bplus_Hlt2TopoMu2BodyBBDTDecision_TIS/O");
  tree->Branch("Bplus_Hlt2TopoMu2BodyBBDTDecision_TOS" , &Bplus_Hlt2TopoMu2BodyBBDTDecision_TOS   , "Bplus_Hlt2TopoMu2BodyBBDTDecision_TOS/O");
  tree->Branch("Bplus_Hlt2TopoMu3BodyBBDTDecision_Dec" , &Bplus_Hlt2TopoMu3BodyBBDTDecision_Dec   , "Bplus_Hlt2TopoMu3BodyBBDTDecision_Dec/O");
  tree->Branch("Bplus_Hlt2TopoMu3BodyBBDTDecision_TIS" , &Bplus_Hlt2TopoMu3BodyBBDTDecision_TIS   , "Bplus_Hlt2TopoMu3BodyBBDTDecision_TIS/O");
  tree->Branch("Bplus_Hlt2TopoMu3BodyBBDTDecision_TOS" , &Bplus_Hlt2TopoMu3BodyBBDTDecision_TOS   , "Bplus_Hlt2TopoMu3BodyBBDTDecision_TOS/O");
  tree->Branch("Bplus_Hlt2SingleMuonDecision_Dec"      , &Bplus_Hlt2SingleMuonDecision_Dec        , "Bplus_Hlt2SingleMuonDecision_Dec/O"    );
  tree->Branch("Bplus_Hlt2SingleMuonDecision_TIS"      , &Bplus_Hlt2SingleMuonDecision_TIS        , "Bplus_Hlt2SingleMuonDecision_TIS/O"    );
  tree->Branch("Bplus_Hlt2SingleMuonDecision_TOS"      , &Bplus_Hlt2SingleMuonDecision_TOS        , "Bplus_Hlt2SingleMuonDecision_TOS/O"    );
  tree->Branch("D0_IPCHI2_OWNPV"                       , &D0_IPCHI2_OWNPV                         , "D0_IPCHI2_OWNPV/D"                     );
  tree->Branch("D0_IP_OWNPV"                           , &D0_IP_OWNPV                             , "D0_IP_OWNPV/D"                         );
  tree->Branch("D0_MINIP"                              , &D0_MINIP                                , "D0_MINIP/D"                            );
  tree->Branch("D0_MINIPCHI2"                          , &D0_MINIPCHI2                            , "D0_MINIPCHI2/D"                        );
  tree->Branch("D0_P"                                  , &D0_P                                    , "D0_P/D"                                );
  tree->Branch("D0_PT"                                 , &D0_PT                                   , "D0_PT/D"                               );
  tree->Branch("D0_PE"                                 , &D0_PE                                   , "D0_PE/D"                               );
  tree->Branch("D0_PX"                                 , &D0_PX                                   , "D0_PX/D"                               );
  tree->Branch("D0_PY"                                 , &D0_PY                                   , "D0_PY/D"                               );
  tree->Branch("D0_PZ"                                 , &D0_PZ                                   , "D0_PZ/D"                               );
  tree->Branch("D0_MM"                                 , &D0_MM                                   , "D0_MM/D"                               );
  tree->Branch("D0_MMERR"                              , &D0_MMERR                                , "D0_MMERR/D"                            );
  tree->Branch("D0_M"                                  , &D0_M                                    , "D0_M/D"                                );
  tree->Branch("D0_DIRA_OWNPV"                         , &D0_DIRA_OWNPV                           , "D0_DIRA_OWNPV/D"                       );
  tree->Branch("D0_DTF_CHI2"                           , &D0_DTF_CHI2                             , "D0_DTF_CHI2/D"                         );
  tree->Branch("D0_ENDVERTEX_CHI2"                     , &D0_ENDVERTEX_CHI2                       , "D0_ENDVERTEX_CHI2/D"                   );
  tree->Branch("D0_FD_CHI2"                            , &D0_FD_CHI2                              , "D0_FD_CHI2/D"                          );
  tree->Branch("D0_ID"                                 , &D0_ID                                   , "D0_ID/D"                               );
  tree->Branch("D0_TAU"                                , &D0_TAU                                  , "D0_TAU/D"                              );
  tree->Branch("Kminus_IPCHI2_OWNPV"                   , &Kminus_IPCHI2_OWNPV                     , "Kminus_IPCHI2_OWNPV/D"                 );
  tree->Branch("Kminus_IP_OWNPV"                       , &Kminus_IP_OWNPV                         , "Kminus_IP_OWNPV/D"                     );
  tree->Branch("Kminus_MINIP"                          , &Kminus_MINIP                            , "Kminus_MINIP/D"                        );
  tree->Branch("Kminus_MINIPCHI2"                      , &Kminus_MINIPCHI2                        , "Kminus_MINIPCHI2/D"                    );
  tree->Branch("Kminus_P"                              , &Kminus_P                                , "Kminus_P/D"                            );
  tree->Branch("Kminus_PT"                             , &Kminus_PT                               , "Kminus_PT/D"                           );
  tree->Branch("Kminus_PE"                             , &Kminus_PE                               , "Kminus_PE/D"                           );
  tree->Branch("Kminus_PX"                             , &Kminus_PX                               , "Kminus_PX/D"                           );
  tree->Branch("Kminus_PY"                             , &Kminus_PY                               , "Kminus_PY/D"                           );
  tree->Branch("Kminus_PZ"                             , &Kminus_PZ                               , "Kminus_PZ/D"                           );
  tree->Branch("Kminus_M"                              , &Kminus_M                                , "Kminus_M/D"                            );
  tree->Branch("Kminus_NNK"                            , &Kminus_NNK                              , "Kminus_NNK/D"                          );
  tree->Branch("Kminus_NNKmu"                          , &Kminus_NNKmu                            , "Kminus_NNKmu/D"                        );
  tree->Branch("Kminus_NNKpi"                          , &Kminus_NNKpi                            , "Kminus_NNKpi/D"                        );
  tree->Branch("Kminus_NNmu"                           , &Kminus_NNmu                             , "Kminus_NNmu/D"                         );
  tree->Branch("Kminus_NNpi"                           , &Kminus_NNpi                             , "Kminus_NNpi/D"                         );
  tree->Branch("Kminus_PIDK"                           , &Kminus_PIDK                             , "Kminus_PIDK/D"                         );
  tree->Branch("Kminus_PIDmu"                          , &Kminus_PIDmu                            , "Kminus_PIDmu/D"                        );
  tree->Branch("Kminus_TRACK_CHI2"                     , &Kminus_TRACK_CHI2                       , "Kminus_TRACK_CHI2/D"                   );
  tree->Branch("Kminus_ghost"                          , &Kminus_ghost                            , "Kminus_ghost/D"                        );
  tree->Branch("Kminus_inMuon"                         , &Kminus_inMuon                           , "Kminus_inMuon/D"                       );
  tree->Branch("Kminus_isMuon"                         , &Kminus_isMuon                           , "Kminus_isMuon/D"                       );
  tree->Branch("Kminus_isMuonLoose"                    , &Kminus_isMuonLoose                      , "Kminus_isMuonLoose/D"                  );
  tree->Branch("piplus_IPCHI2_OWNPV"                   , &piplus_IPCHI2_OWNPV                     , "piplus_IPCHI2_OWNPV/D"                 );
  tree->Branch("piplus_IP_OWNPV"                       , &piplus_IP_OWNPV                         , "piplus_IP_OWNPV/D"                     );
  tree->Branch("piplus_MINIP"                          , &piplus_MINIP                            , "piplus_MINIP/D"                        );
  tree->Branch("piplus_MINIPCHI2"                      , &piplus_MINIPCHI2                        , "piplus_MINIPCHI2/D"                    );
  tree->Branch("piplus_P"                              , &piplus_P                                , "piplus_P/D"                            );
  tree->Branch("piplus_PT"                             , &piplus_PT                               , "piplus_PT/D"                           );
  tree->Branch("piplus_PE"                             , &piplus_PE                               , "piplus_PE/D"                           );
  tree->Branch("piplus_PX"                             , &piplus_PX                               , "piplus_PX/D"                           );
  tree->Branch("piplus_PY"                             , &piplus_PY                               , "piplus_PY/D"                           );
  tree->Branch("piplus_PZ"                             , &piplus_PZ                               , "piplus_PZ/D"                           );
  tree->Branch("piplus_M"                              , &piplus_M                                , "piplus_M/D"                            );
  tree->Branch("piplus_NNK"                            , &piplus_NNK                              , "piplus_NNK/D"                          );
  tree->Branch("piplus_NNKmu"                          , &piplus_NNKmu                            , "piplus_NNKmu/D"                        );
  tree->Branch("piplus_NNKpi"                          , &piplus_NNKpi                            , "piplus_NNKpi/D"                        );
  tree->Branch("piplus_NNmu"                           , &piplus_NNmu                             , "piplus_NNmu/D"                         );
  tree->Branch("piplus_NNpi"                           , &piplus_NNpi                             , "piplus_NNpi/D"                         );
  tree->Branch("piplus_PIDK"                           , &piplus_PIDK                             , "piplus_PIDK/D"                         );
  tree->Branch("piplus_PIDmu"                          , &piplus_PIDmu                            , "piplus_PIDmu/D"                        );
  tree->Branch("piplus_TRACK_CHI2"                     , &piplus_TRACK_CHI2                       , "piplus_TRACK_CHI2/D"                   );
  tree->Branch("piplus_ghost"                          , &piplus_ghost                            , "piplus_ghost/D"                        );
  tree->Branch("piplus_inMuon"                         , &piplus_inMuon                           , "piplus_inMuon/D"                       );
  tree->Branch("piplus_isMuon"                         , &piplus_isMuon                           , "piplus_isMuon/D"                       );
  tree->Branch("piplus_isMuonLoose"                    , &piplus_isMuonLoose                      , "piplus_isMuonLoose/D"                  );
  tree->Branch("muplus_IPCHI2_OWNPV"                   , &muplus_IPCHI2_OWNPV                     , "muplus_IPCHI2_OWNPV/D"                 );
  tree->Branch("muplus_IP_OWNPV"                       , &muplus_IP_OWNPV                         , "muplus_IP_OWNPV/D"                     );
  tree->Branch("muplus_MINIP"                          , &muplus_MINIP                            , "muplus_MINIP/D"                        );
  tree->Branch("muplus_MINIPCHI2"                      , &muplus_MINIPCHI2                        , "muplus_MINIPCHI2/D"                    );
  tree->Branch("muplus_P"                              , &muplus_P                                , "muplus_P/D"                            );
  tree->Branch("muplus_PT"                             , &muplus_PT                               , "muplus_PT/D"                           );
  tree->Branch("muplus_PE"                             , &muplus_PE                               , "muplus_PE/D"                           );
  tree->Branch("muplus_PX"                             , &muplus_PX                               , "muplus_PX/D"                           );
  tree->Branch("muplus_PY"                             , &muplus_PY                               , "muplus_PY/D"                           );
  tree->Branch("muplus_PZ"                             , &muplus_PZ                               , "muplus_PZ/D"                           );
  tree->Branch("muplus_M"                              , &muplus_M                                , "muplus_M/D"                            );
  tree->Branch("muplus_NNK"                            , &muplus_NNK                              , "muplus_NNK/D"                          );
  tree->Branch("muplus_NNKmu"                          , &muplus_NNKmu                            , "muplus_NNKmu/D"                        );
  tree->Branch("muplus_NNKpi"                          , &muplus_NNKpi                            , "muplus_NNKpi/D"                        );
  tree->Branch("muplus_NNmu"                           , &muplus_NNmu                             , "muplus_NNmu/D"                         );
  tree->Branch("muplus_NNpi"                           , &muplus_NNpi                             , "muplus_NNpi/D"                         );
  tree->Branch("muplus_PIDK"                           , &muplus_PIDK                             , "muplus_PIDK/D"                         );
  tree->Branch("muplus_PIDmu"                          , &muplus_PIDmu                            , "muplus_PIDmu/D"                        );
  tree->Branch("muplus_TRACK_CHI2"                     , &muplus_TRACK_CHI2                       , "muplus_TRACK_CHI2/D"                   );
  tree->Branch("muplus_ghost"                          , &muplus_ghost                            , "muplus_ghost/D"                        );
  tree->Branch("muplus_inMuon"                         , &muplus_inMuon                           , "muplus_inMuon/D"                       );
  tree->Branch("muplus_isMuon"                         , &muplus_isMuon                           , "muplus_isMuon/D"                       );
  tree->Branch("muplus_isMuonLoose"                    , &muplus_isMuonLoose                      , "muplus_isMuonLoose/D"                  );
  tree->Branch("nCandidate"                            , &nCandidate                              , "nCandidate/i"                          );
  tree->Branch("totCandidates"                         , &totCandidates                           , "totCandidates/l"                       );
  tree->Branch("EventInSequence"                       , &EventInSequence                         , "EventInSequence/l"                     );
  tree->Branch("runNumber"                             , &runNumber                               , "runNumber/i"                           );
  tree->Branch("eventNumber"                           , &eventNumber                             , "eventNumber/l"                         );
  tree->Branch("BCID"                                  , &BCID                                    , "BCID/i"                                );
  tree->Branch("BCType"                                , &BCType                                  , "BCType/I"                              );
  tree->Branch("OdinTCK"                               , &OdinTCK                                 , "OdinTCK/i"                             );
  tree->Branch("L0DUTCK"                               , &L0DUTCK                                 , "L0DUTCK/i"                             );
  tree->Branch("HLT1TCK"                               , &HLT1TCK                                 , "HLT1TCK/i"                             );
  tree->Branch("HLT2TCK"                               , &HLT2TCK                                 , "HLT2TCK/i"                             );
  tree->Branch("GpsTime"                               , &GpsTime                                 , "GpsTime/l"                             );
  tree->Branch("Polarity"                              , &Polarity                                , "Polarity/S"                            );
  tree->Branch("nPVs"                                  , &nPVs                                    , "nPVs/I"                                );
  tree->Branch("nTracks"                               , &nTracks                                 , "nTracks/I"                             );
  tree->Branch("nLongTracks"                           , &nLongTracks                             , "nLongTracks/I"                         );
  tree->Branch("nDownstreamTracks"                     , &nDownstreamTracks                       , "nDownstreamTracks/I"                   );
  tree->Branch("nUpstreamTracks"                       , &nUpstreamTracks                         , "nUpstreamTracks/I"                     );
  tree->Branch("nVeloTracks"                           , &nVeloTracks                             , "nVeloTracks/I"                         );
  tree->Branch("nTTracks"                              , &nTTracks                                , "nTTracks/I"                            );
  tree->Branch("nBackTracks"                           , &nBackTracks                             , "nBackTracks/I"                         );
  tree->Branch("nRich1Hits"                            , &nRich1Hits                              , "nRich1Hits/I"                          );
  tree->Branch("nRich2Hits"                            , &nRich2Hits                              , "nRich2Hits/I"                          );
  tree->Branch("nVeloClusters"                         , &nVeloClusters                           , "nVeloClusters/I"                       );
  tree->Branch("nITClusters"                           , &nITClusters                             , "nITClusters/I"                         );
  tree->Branch("nTTClusters"                           , &nTTClusters                             , "nTTClusters/I"                         );
  tree->Branch("nOTClusters"                           , &nOTClusters                             , "nOTClusters/I"                         );
  tree->Branch("nSPDHits"                              , &nSPDHits                                , "nSPDHits/I"                            );
  tree->Branch("nMuonCoordsS0"                         , &nMuonCoordsS0                           , "nMuonCoordsS0/I"                       );
  tree->Branch("nMuonCoordsS1"                         , &nMuonCoordsS1                           , "nMuonCoordsS1/I"                       );
  tree->Branch("nMuonCoordsS2"                         , &nMuonCoordsS2                           , "nMuonCoordsS2/I"                       );
  tree->Branch("nMuonCoordsS3"                         , &nMuonCoordsS3                           , "nMuonCoordsS3/I"                       );
  tree->Branch("nMuonCoordsS4"                         , &nMuonCoordsS4                           , "nMuonCoordsS4/I"                       );
  tree->Branch("nMuonTracks"                           , &nMuonTracks                             , "nMuonTracks/I"                         );
}

